### ISSUE TITLE
Add a grid control?

### ISSUE THREAD

**Issue by MichaelGoulding** [ArthurSonzogni/FTXUI#114]
It would be great to have a control that lets you have a fixed set of rows and columns fit to a space.

**Comment by ArthurSonzogni** [comment]
That sounds like a good idea.

Note that you can use a `vbox` of `hbox`:
```
vbox({
  hbox({ a11, a12, a13}),
  hbox({ a21, a22, a23}),
  hbox({ a31, a32, a33}),
})
```

However, a gridbox would ensure a shared width/height for every elements in the same column/line.
I will take a look. This sounds useful.

**Comment by MichaelGoulding** [comment]
This [repository ](https://github.com/MichaelGoulding/vcpkg-ftxui-sample) shows where I used vboxes of hboxes, but it doesn't work well.

**Comment by ArthurSonzogni** [comment]
I tried your example.
It doesn't look bad. What the problem?

https://user-images.githubusercontent.com/4759106/124128355-fff55480-da7c-11eb-9afe-35f4b5c1632e.mp4

**Comment by ArthurSonzogni** [comment]
Fixed by:
https://github.com/ArthurSonzogni/FTXUI/pull/190

See example:
https://github.com/ArthurSonzogni/FTXUI/blob/51850f118983efe3e98c1d2731d848483db03176/src/ftxui/dom/gridbox_test.cpp#L75:L95

Does this fit your needs?

**Comment by MichaelGoulding** [comment]
Thanks!  The sizing behavior appears to be what I needed.  I'll take a closer look at it when I get back from vacation. 
Is there a way to change the borders to straight corners?

**Comment by MattBystrin** [comment]
Waiting for straight corners too

**Comment by ArthurSonzogni** [comment]
I would like to add some class to build some fancy tables with different style for the grid and the element. That will come at some point.

About rounded/straight border. I switched to [rounded](https://github.com/ArthurSonzogni/FTXUI/pull/175/files) recently, because developers like it a lot better. However, I would have like make it configurable to fit every one wishes.

Would you have some API suggestions?
Something global?

Two functions, `border` being straight.
```cpp
Element border(Element) // Straight
Element roundedBorder(Element)
```
Two functions, `border` being rounded.
```cpp
Element border(Element) // Rounded
Element straightBorder(Element)
```

Some options:
```cpp
Element border(Element, bool rounded = true);
```

**Comment by MattBystrin** [comment]
@ArthurSonzogni , what do you think about one more "double lined" border  ( inspired by mc ) style ?
By the way the first option ( different names ) is really suits me .

**Comment by ArthurSonzogni** [comment]
> @ArthurSonzogni , what do you think about one more "double lined" border ( inspired by mc ) style ?

This is now supported, via the API:
```cpp
Element separator(void);
Element separatorLight();
Element separatorHeavy();
Element separatorDouble();
Element separatorStyled(BorderStyle);

Element border(Element);
Element borderLight(Element);
Element borderHeavy(Element);
Element borderDouble(Element);
Element borderRounded(Element);
Decorator borderStyled(BorderStyle);
```

**Comment by ArthurSonzogni** [comment]
The original issue as been address via the `gridbox` element.
