### ISSUE TITLE
to_wstring may get invalid UTF-8 string sent by user intentionally

### ISSUE THREAD

**Issue by eugenechouy** [ArthurSonzogni/FTXUI#118]
Hi, we recently tested the library through fuzzing rgb-tui, and we found out there are crashes when feeding into non-UTF8 string. I think it would be great to check it first before `std::wstring to_wstring(const std::string& s)`. 

> terminate called after throwing an instance of 'std::range_error'
  what():  wstring_convert::from_bytes
[1]       3142 abort (core dumped)     ./rgb-tui < 
m35:113;34m35;115;35m35;116;35

**Comment by ArthurSonzogni** [comment]
Thanks for reporting this!

I secretly spied on your work here two week ago:
https://github.com/u1f383/rgb-tui/commit/d25e9ba524c1d2181887dc54ff1fa2f4bcfcca7a
(Assuming this is you)

Do you have previous experience setup on github a fuzzer that would run automatically and try to warn when we introduce bugs like this one? Any suggestions are welcome.

**Comment by u1f383** [comment]
Sorry for late reply. I and @eugenechouy are researching how to automatically run fuzz to help you, and we plan to response you or commit after we finish it.

**Comment by ArthurSonzogni** [comment]
Hey @eugenechouy and @u1f383,

I added a fuzzer and and fixed the parsing of UTF8 characters.
I updated the rgb-tui to the latest version of the library.

In theory, things should be fixed. Could you confirm your aren't experiencing the same problem anymore?

**Comment by eugenechouy** [comment]
It looks good for me, crash won't happen anymore for our test case.  👍

**Comment by ArthurSonzogni** [comment]
Great! Thank you!
