### ISSUE TITLE
How can I get frame to actual scroll the content?

### ISSUE THREAD

**Issue by MichaelGoulding** [ArthurSonzogni/FTXUI#125]
If you look at this sample, https://github.com/MichaelGoulding/vcpkg-ftxui-sample, if you enter enough text, the input box gets squashed and the content doesn't scroll.

What am I doing wrong?

Thanks!

**Comment by ArthurSonzogni** [comment]
Inside a frame, you need to specify which element has the focus, so that FTXUI knows which element it needs to focus one.

You can get:
[![asciicast](https://asciinema.org/a/3I4OGgPyhlvBGwQ9CvHIbJjr7.svg)](https://asciinema.org/a/3I4OGgPyhlvBGwQ9CvHIbJjr7)

if you replace:
```cpp
g_cmdHistoryContainer->Render() | yframe | flex_grow,
```
```cpp
vbox({
  g_cmdHistoryContainer->Render(),
  text(L"Focus") | focus,
}) | yframe | yflex,
```

I added an element `text(L"Focus")` at the bottom and used `focus` to bring focus to it.

**Comment by matthesoundman** [comment]
> Inside a frame, you need to specify which element has the focus, so that FTXUI knows which element it needs to focus one.
> 
> You can get:
> [![asciicast](https://camo.githubusercontent.com/9e9e1f1ca2437be963124e71aa1e366a222134f6618ad70b80735c149a387916/68747470733a2f2f61736369696e656d612e6f72672f612f3349344f47675079686c76424777513943764849624a6a72372e737667)](https://asciinema.org/a/3I4OGgPyhlvBGwQ9CvHIbJjr7)
> 
> if you replace:
> 
> ```c++
> g_cmdHistoryContainer->Render() | yframe | flex_grow,
> ```
> 
> ```c++
> vbox({
>   g_cmdHistoryContainer->Render(),
>   text(L"Focus") | focus,
> }) | yframe | yflex,
> ```
> 
> I added an element `text(L"Focus")` at the bottom and used `focus` to bring focus to it.

I am interested in understanding how to make a list of entries dynamically scroll. This suggestion does work, however I was not able to scroll back the history to see the commands that scroll out of focus. Any other suggestions here?

**Comment by ArthurSonzogni** [comment]
@matthesoundman, I replied in:
https://github.com/ArthurSonzogni/FTXUI/issues/130

**Comment by MichaelGoulding** [comment]
I ended up using this:
```

// A vertical component that places the focus always on the last child,
// allowing an outer frame to keep that child in view.
class KeepLastInFocusComponent : public ftxui::ComponentBase
{
public:
    void Clear()
    {
        children_.clear();
    }


    ftxui::Element Render() override
    {
        std::vector<ftxui::Element> elements;

        const size_t lastItem = (children_.size() - 1);
        for (size_t i = 0; i < children_.size(); ++i)
        {
            // Set focus on the last line so that the outer frame keeps it in view.
            if (lastItem != i)
            {
                elements.emplace_back(children_[i]->Render());
            }
            else
            {
                elements.emplace_back(children_[i]->Render() | ftxui::focus);
            }
        }

        return vbox(std::move(elements));
    }
};
```

**Comment by MichaelGoulding** [comment]
The ability to scroll up would be good, but I don't want any selection of the text, and I would want the focus to move down to the bottom if new text was added.

**Comment by ArthurSonzogni** [comment]
git-tui uses a Scroller component. I might one day make it built in into FTXUI:
https://github.com/ArthurSonzogni/git-tui/blob/master/src/scroller.cpp
Feel free to copy paste.

**Comment by ArthurSonzogni** [comment]
> I ended up using this:
[...]

Alternatively, your Component could have been a dom element, since it doesn't have to deal with user's input.

```cpp
Element AddFocusBottom(Elements list) {
  if (list.size() != 0)
    list.back() = focus(std::move(list.back());
  return std::move(list)
}
```

And then replace:
```cpp
vbox(list)
```
by:
```cpp
vbox(AddFocusBottom(list))
```

**Comment by ArthurSonzogni** [comment]
I can add some dom element that put the focus on one side of the component.
```
Decorator focusTop();
Decorator focusBottom()
Decorator focusLeft()
Decorator focusRight()
```

**Comment by ArthurSonzogni** [comment]
This can be closed.

I added `focusPositionRelative(x,y)` to move the focus to one direction within the frame.
```
big_document() | focusPositionRelative(0, 1) | yframe
```
