### ISSUE TITLE
Feature request: A menu of components?

### ISSUE THREAD

**Issue by ArthurSonzogni** [ArthurSonzogni/FTXUI#126]
It would be nice adding a Menu of components, instead of being a menu of focusable text.

This would be useful for beagle-config, which was using a group of 3 submenu.

**Comment by SAtacker** [comment]
Hi @ArthurSonzogni  how about 
[![asciicast](https://asciinema.org/a/YLWllRq0PIx5s1cjzetr6VuW4.svg)](https://asciinema.org/a/YLWllRq0PIx5s1cjzetr6VuW4)

**Comment by SAtacker** [comment]
If that's okay, I can send a PR right now.
