### ISSUE TITLE
Scroll a Vertical Container

### ISSUE THREAD

**Issue by matthesoundman** [ArthurSonzogni/FTXUI#130]
I want to be able to scroll through a Vertical container during runtime. I have ideas to populate the container with messages and other various strings. With the strings being dynamically added during runtime I can't seem to figure out how to scroll the container's history after it has filled passed the screen height.

```cpp
auto message_container {ftxui::Container::Vertical({})};
auto message_view_renderer {Renderer(layout, [&] {
  return vbox({
    text(L"Basic Message Viewer") | center,
      vbox({ message_container->Render() | yflex }) | border | flex
  });
})};
```
I would then have another process running in another thread adding new lines as they arrive.
```cpp
message_container->Add(ftxui::Renderer([] {}));
```

Is it possible to scroll the contents of the container?

**Comment by ArthurSonzogni** [comment]
It is because ftxui::Renderer do not use `focus` or `select` when focused/selected.

You can add:
```cpp
// A simple text highlighted when focused.
class Focusable : public ComponentBase {
 public:
  Focusable(const std::wstring& title) : title_(title) {}
  Element Render() final {
    if (Focused())
      return text(title_) | inverted | focus;
    else
      return text(title_);
  }

 private:
  std::wstring title_;
};
```

And then:
```cpp
message_container->Add(Make<Focusable>(L"Text"))
```

It might worth it adding a builtin component like Focusable in the library.

**Comment by ArthurSonzogni** [comment]
BTW, at this point, you could simply use the builtin `Menu()`

**Comment by matthesoundman** [comment]
Cool. Let me give ```Menu()``` a try. BTW really am liking this library.
