### ISSUE TITLE
Embedding plots ?

### ISSUE THREAD

**Issue by chromafunk** [ArthurSonzogni/FTXUI#134]
Is it somehow possible or would it be possible to embed Plplot inside FTXUI containers ?

http://plplot.sourceforge.net/ 

Thanks !

**Comment by ArthurSonzogni** [comment]
Hi!

I don't understand the question. Can Plplot output something that could be drawn inside a terminal, with a grid of characters?

Or maybe you would like to use brailles characters to have extra definition for plotting function like:
https://github.com/tammoippen/plotille
?

**Comment by chromafunk** [comment]
From the Plplot site :
```
PLplot is a cross-platform software package for creating scientific plots whose (UTF-8) plot symbols and text are limited in practice only by what Unicode-aware system fonts are installed on a user's computer. The PLplot software, which is primarily licensed under the LGPL, has a clean architecture that is organized as a core C library, separate language bindings for that library, and separate device drivers that are dynamically loaded by the core library which control how the plots are presented in noninteractive and interactive plotting contexts.
```
Plplot is a terminal plotter, and it's honestly fantastic. Written in C but also has C++ bindings. In my oppinion is the best terminal plotting software. It would amazing if we could add plotting functions and embed them on FTXUI containers.

I'm not sure if this would be possible though, but if was, this would the ultimate solution!

**Comment by ArthurSonzogni** [comment]
This doesn't seems hard to make an adapter that will draw the output of plplot into a ftxui::screen as a ftxui dom element.
I won't force anyone to pay the cost of embedding directly plplot into FTXUI, but that an use case I want for people to be easy to support. I can make a demo and make it public for other people to do it.

I don't see an image on internet showing the output of plplot into a terminal. Do you have one?

**Comment by chromafunk** [comment]
Sounds great 

I've been looking in to some old images taken when I was coding some plot functions and saved screenshots straight from a full screen terminal, but I don't have any where you can actually see the terminal. I'd just use some of the pictures available at the Plplot site, and I can make some detailed screenshots for you once I have it running again ? Let me know

**Comment by chromafunk** [comment]
Taking a deeper look in to this, since I'm pretty sure you can plot to a terminal ... I just retrieved an old project and I used xwin to plot tho. Will get back to you

**Comment by chromafunk** [comment]
sorry, got totally confused as it's been a good three years since I don't use Plplot and forgot that you can't plot to an actual terminal :) Maybe then, the correct way to do this would be something like plotille

**Comment by ArthurSonzogni** [comment]
;-) that's what I suspected about Plplot.

Note that you can use ftxui::graph to plot some functions:
https://arthursonzogni.com/FTXUI/examples/?file=./dom/graph.js

Note as nice as plotille, but this one is already available.
