### ISSUE TITLE
Document how to enable truecolor on Windows

### ISSUE THREAD

**Issue by MichaelGoulding** [ArthurSonzogni/FTXUI#135]
The code looks for the environment variable
```
COLORTERM
```
to enable true color.

Windows 10 has supported true color in the console for a while now, but FTXUI doesn't do the right thing without the environment variable set:

![image](https://user-images.githubusercontent.com/18077959/123858633-9b00f980-d8d8-11eb-9cd3-ae242058b3e2.png)

**Comment by ArthurSonzogni** [comment]
I am sorry this terminal on Windows doesn't set the COLORTERM variable.

Maybe there standard ways in the specification:
https://invisible-island.net/xterm/ctlseqs/ctlseqs.html
to query directly the terminal support for colors.

The cost would be some communication with the terminal via stdin/stdout.
Maybe 
```cpp
ftxui::QueryColorSupport()
```

**Comment by ArthurSonzogni** [comment]
Hey @MichaelGoulding,

Do you think we should close this issue, given the latest patch?
