### ISSUE TITLE
Error building FTXUI : txui/component/event_input_listener.hpp not found

### ISSUE THREAD

**Issue by MoronGamer** [ArthurSonzogni/FTXUI#142]
Below error is generated by make:

/src/FTXUI/src/ftxui/component/screen_interactive.cpp:12:10: fatal error: ftxui/component/event_input_listener.hpp: No such file or directory
 #include "ftxui/component/event_input_listener.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/component.dir/build.make:154: CMakeFiles/component.dir/src/ftxui/component/screen_interactive.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:275: CMakeFiles/component.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by MoronGamer** [comment]
updated source code and compiled fine

**Comment by ArthurSonzogni** [comment]
The file is here:
https://github.com/ArthurSonzogni/FTXUI/blob/master/src/ftxui/component/terminal_input_parser.hpp

The library compile correctly. What did you do exactly?

**Comment by MoronGamer** [comment]
i have no idea how i ended up doing git clone https://github.com/mauve/FTXUI.git
