### ISSUE TITLE
Compile error on cygwin

### ISSUE THREAD

**Issue by zhangtianli2006** [ArthurSonzogni/FTXUI#149]
![error img](https://user-images.githubusercontent.com/49156174/125386565-141b4900-e3cf-11eb-8b9e-3e15380ee630.PNG)

On windows7
gcc version 10.2.0

**Comment by ArthurSonzogni** [comment]
Hmm, that's true.
I followed the UTF8 spec a bit too closely.

Do you want to submit a PR removing this?

**Comment by ArthurSonzogni** [comment]
I will make a PR soon tonight.

**Comment by ArthurSonzogni** [comment]
This might be fixed.
@zhangtianli2006, could you please double check?
