### ISSUE TITLE
Multipe bugs introduced with last commit

### ISSUE THREAD

**Issue by GiuseppeCesarano** [ArthurSonzogni/FTXUI#16]
If i compile my project with cccbe5baa96438fd4668e47f6b732e6fdae3dd0c, the produced binary starts its UI misaligned with the terminal using st terminal, in kitty terminal the UI works fine, however it crashes after handling some keyboard events

**Comment by GiuseppeCesarano** [comment]
Investigating further I noticed that the bug also occurs in the kitty terminal, but probably for the different implementation, in kitty the UI remains aligned but only half is printed on the screen

**Comment by ArthurSonzogni** [comment]
I will take a look at your project to confirm the bug.

**Comment by ArthurSonzogni** [comment]
Everything looks all right. Could you please be more specific about the issue?

Here is what I get:
[![asciicast](https://asciinema.org/a/p6F2eSUx65QHAqNhdGoNqaY4q.svg)](https://asciinema.org/a/p6F2eSUx65QHAqNhdGoNqaY4q)

**Comment by GiuseppeCesarano** [comment]
![screenshot](https://i.ibb.co/qkN5cvW/s.png)

As you can see, the UI isn't centered anymore, also the no inputs are ignored. Sometimes for some reason the UI starts at the correct location and inputs work as expected but only for a short time period. I'm compiling with GCC 9.3.0

**Comment by GiuseppeCesarano** [comment]
I just installed Alacritty to test that out, it seems that the bug is terminal related since it doesn't effects Alacritty

**Comment by ArthurSonzogni** [comment]
I tried kitty and gnome-terminal. Everything was working fine.

Could you try again after patch:
https://github.com/GiuseppeCesarano/just-fast/commit/df013890a8936febff7012a6e3e5f3843e3ed51c
?

What terminal are you using?

**Comment by ArthurSonzogni** [comment]
Wait... I am able to reproduce using gnome-teminal. I will take a look.

**Comment by GiuseppeCesarano** [comment]
Okay maybe I'm on something, i think is not about compiler or terminal but the window itself, if i run the application in a window that's half the screen size it runs as usual, if the terminal is full screen the bug can appear, but it's inconsistent since sometimes i got it on half screen too (the screenshot was on half screen)

**Comment by ArthurSonzogni** [comment]
Okay. I found the issue.
Thanks for reporting this!

Could you please confirm this fixed your bug?

**Comment by GiuseppeCesarano** [comment]
Fixed! Thanks!
