### ISSUE TITLE
Implementation of simple debug component

### ISSUE THREAD

**Issue by SAtacker** [ArthurSonzogni/FTXUI#164]
An [example](https://github.com/SAtacker/FTXUI/blob/satacker-debug-comp/examples/component/debug.cpp) of my version of debug
```cpp
  auto debug = Debug(L"Ohhoy:\n");

  debug << "Debug it here\n";
  auto screen = ScreenInteractive::TerminalOutput();
  screen.Loop(debug);
```
It would be nice to have this
[![asciicast](https://asciinema.org/a/426721.svg)](https://asciinema.org/a/426721)

**Comment by ArthurSonzogni** [comment]
I am not sure this is worthwhile.

User can already use:
```cpp
std::vector<wstring> debug;
```

Then append log using:
```cpp
debug.push_back("Debug line");
```

Then rendering it using:
```cpp
Elements out;
for(auto& it : debug)
  out.push_back(text(it));
return hbox(it) | yframe;
```


It sounds easier to do it yourself than using a builtin component. Moreover, I am not so sure to be able to make a built-in elements that would fit all purposes.

**Comment by SAtacker** [comment]
Ohh, right :+1:  . I'll close this issue then. Thanks .
