### ISSUE TITLE
SharedArrayBuffer is deprecated outside of cross-origin isolated environments.

### ISSUE THREAD

**Issue by ArthurSonzogni** [ArthurSonzogni/FTXUI#169]
Since @tusharpm patch:
https://github.com/ArthurSonzogni/FTXUI/pull/166#pullrequestreview-714337259
The documentation and webassembly examples are automatically deployed on https://arthursonzogni.github.io instead of https://arthursonzogni.com

The examples are using webassembly threads and shared memory. This requires in Firefox and Chrome >=92 to be in cross-origin isolated environments using those two headers:
```
cross-origin-embedder-policy: require-corp
cross-origin-opener-policy: same-origin
```

But I don't own arthursonzogni.github.io and can't configure the headers.

In the meantime we should revert back to https://arthursonzogni.com/FTXUI/examples/ so that Firefox and Chrome-beta users can use them.

**Comment by tusharpm** [comment]
Agreed. The examples fail to work on Firefox with a `SharedArrayBuffer is not defined` error.
[A GitHub Support Community post](https://github.community/t/github-page-headers-and-webassembly/139483?u=tusharpm) describes this limitation of GitHub pages and requests a mechanism to add those headers.
Until GitHub addresses this, reverting the examples link is the correct solution.
