### ISSUE TITLE
Stable branch to not break dependent projects

### ISSUE THREAD

**Issue by GiuseppeCesarano** [ArthurSonzogni/FTXUI#17]
What do you think of a stable branch where the changes are tested so as not to temporarily break other projects? Since [ftxui-starter](https://github.com/ArthurSonzogni/ftxui-starter) downloads the master branch that could happen a lot

**Comment by ArthurSonzogni** [comment]
Yes, this is possible. However I am worried nobody is going to test the develop version. I am most likely going to merge everything into master/ and break clients the same way.

Maybe you should depend on a specific hash instead of master?

**Comment by GiuseppeCesarano** [comment]
I considered using a specific git hash, however since FTXUI is a fast moving project it will be a bit annoying update it frequently. But you're right, manually testing every time a change is done is not sustainable.

**Comment by GiuseppeCesarano** [comment]
I considered using a specific git hash, however since FTXUI is a fast moving project it will be a bit annoying update it frequently. But you're right, manually testing every time a change is done is not sustainable.

**Comment by ArthurSonzogni** [comment]
I will close this issue.

I think I will make a develop/ branch once FTXUI is used more widely. Maybe also some git tag and versions. This way people can depends on well known version that are fully tested.
