### ISSUE TITLE
A way to copy into input fields?

### ISSUE THREAD

**Issue by Creapermann** [ArthurSonzogni/FTXUI#174]
Is there any ways to copy content per e.g. ctrl+v or right-click into the input field?

**Comment by ArthurSonzogni** [comment]
FTXUI uses only one API: reading/writing to stdout/stdin by following the terminal specification.
Accessing the clipboard is usually a specific API specific to each OSs, which FTXUI do not use.

However, on most terminal, pressing ctrl+v should paste the content of the OS's clipboard to stdin, which implement "pasting" correctly. At least it works great on my terminal emulator.

Outside of this, support for clipboard is null in FTXUI.

In the terminal specification, I see there are some API defined about the clipboard:
https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#:~:text=clipboard%2C%20primary%2C%20secondary
maybe this could be used one day?

I am not sure a lot of terminal implement it however. I see microsoft just did it very recently:
https://github.com/microsoft/terminal/issues/2946

About right click, FTXUI reports right click. You can try the example "print_key_press". This should display "right" from here:
https://github.com/ArthurSonzogni/FTXUI/blob/26e26fd41a4c7c938d4a97c7106746b27cc4520a/examples/component/print_key_press.cpp#L38

**Comment by Creapermann** [comment]
> 
> 
> FTXUI uses only one API: reading/writing to stdout/stdin by following the terminal specification.
> Accessing the clipboard is usually a specific API specific to each OSs, which FTXUI do not use.
> 
> However, on most terminal, pressing ctrl+v should paste the content of the OS's clipboard to stdin, which implement "pasting" correctly. At least it works great on my terminal emulator.
> 
> Outside of this, support for clipboard is null in FTXUI.
> 
> In the terminal specification, I see there are some API defined about the clipboard:
> https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#:~:text=clipboard%2C%20primary%2C%20secondary
> maybe this could be used one day?
> 
> I am not sure a lot of terminal implement it however. I see microsoft just did it very recently:
> [microsoft/terminal#2946](https://github.com/microsoft/terminal/issues/2946)
> 
> About right click, FTXUI reports right click. You can try the example "print_key_press". This should display "right" from here:
> 
> https://github.com/ArthurSonzogni/FTXUI/blob/26e26fd41a4c7c938d4a97c7106746b27cc4520a/examples/component/print_key_press.cpp#L38

I will, thanks
