### ISSUE TITLE
Make Element to be a function.

### ISSUE THREAD

**Issue by ArthurSonzogni** [ArthurSonzogni/FTXUI#18]
Currently we have:
~~~cpp
using Element = std::unique_ptr<Node>();
~~~
It means an Element is not copyable. It can't be put in an initializer list either.
Instead, I think we should have used:
~~~cpp
using Element = std::function<std::unique_ptr<Node>()>;
~~~

---------------------

If we do this, then every Element become copyable. This would allow users to do:
```cpp
  // old
  return window(L"window", std::move(renderWindow()));

  // new
  return window(L"window", renderWindow());
```

and
```cpp
  // old
  return vbox(
    text("L upper"),
    text("L lower"),
  );

  // new
  return vbox({
    text("L upper"),
    text("L lower")
  });
```

Benefits:
------------
- Being able to use initializer list would make tool like clang-format able to properly format the C++ Code.
- Not being forced to use std::move()

+CC users of the projects I know using FTXUI. (@AnisBdz, @mibli, @GiuseppeCesarano) If you have some comments, please let me know.

Note: This shouldn't break most of the users. Only the one that have defined their own Elements.
I think only https://github.com/AnisBdz/CPU will be slightly broken. I will prepare a fix for you.

**Comment by AnisBdz** [comment]
Hi, Thanks for letting me know about it.

What do you think about using shared pointers instead `std::shared_ptr`?
That would allow to move elements without using `std::move`, but I'm not sure if initializer lists can be used as intended.

**Comment by ArthurSonzogni** [comment]
Using std::shared_ptr might be another solution indeed!
I will try that instead.
