### ISSUE TITLE
Errors when trying to build the lib

### ISSUE THREAD

**Issue by Creapermann** [ArthurSonzogni/FTXUI#183]
Hey, i m trying to build ftxui in a project(vs19) and then link the lib. Im getting unresolved external errors on the color class tho, saying smth like this: LNK2001	unresolved external symbol "class std::function<class std::shared_ptr<class ftxui::Node> __cdecl(class std::shared_ptr<class ftxui::Node>)> __cdecl ftxui::color(class ftxui::Color)" (?color@ftxui@@YA?AV?$function@$$A6A?AV?$shared_ptr@VNode@ftxui@@@std@@V12@@Z@std@@VColor@1@@Z) Could this be due to the 2 files which are both named "color.cpp"?

**Comment by ArthurSonzogni** [comment]
Is this a compilation error, or an error about some kind of helper provided by visual studio?

I remember @tweeks111 talked about something similar last week with visual studio.

**Comment by ArthurSonzogni** [comment]
Could you provide more informations about how you are compiling the library and linking against your project? Are you using cmake?

**Comment by Creapermann** [comment]
> Is this a compilation error, or an error about some kind of helper provided by visual studio?
> 
> I remember @tweeks111 talked about something similar last week with visual studio.
> 
> 

Oh sry, i wrote it wrong, its a linking error. I wanted to write "When i build the project"

**Comment by Creapermann** [comment]
> Could you provide more informations about how you are compiling the library and linking against your project? Are you using cmake?

I was using cmake before but i Switched to vs19 build System now, i added the forders src/ and include/ and set up the "explicit include directories" right. Then i made the output of my project be a .lib (static library) file and then referenced it to my Main project.

Btw. I did the same with another lib (sqlite3) and it worked all fine, the problem is really just the linking errors (had also some other probably vs relaxed compile errors before but fixed them with flags)

Thank you in advance

**Comment by ArthurSonzogni** [comment]
> I was using cmake before but i Switched to vs19 build System now, i added the forders src/ and include/ and set up the "explicit include directories" right.

Well, If you decide to do it on your own, then you are on your own. I don't recommand it.

You will miss some definitions from:
https://github.com/ArthurSonzogni/FTXUI/blob/master/cmake/ftxui_set_options.cmake

In particular:
- FTXUI_MICROSOFT_TERMINAL_FALLBACK
- UNICODE

---

However, the error is different thought. It means you probably forgot to compile one `color.cpp` file.

**Comment by Creapermann** [comment]
> 
> 
> > I was using cmake before but i Switched to vs19 build System now, i added the forders src/ and include/ and set up the "explicit include directories" right.
> 
> Well, If you decide to do it on your own, then you are on your own. I don't recommand it.
> 
> You will miss some definitions from:
> https://github.com/ArthurSonzogni/FTXUI/blob/master/cmake/ftxui_set_options.cmake
> 
> In particular:
> 
>     * FTXUI_MICROSOFT_TERMINAL_FALLBACK
> 
>     * UNICODE
> 
> 
> However, the error is different thought. It means you probably forgot to compile one `color.cpp` file.

What are my other options tho? I want to use it in visual studio but there are no precompiled binaries (Im not really experienced with the usage of libraries in general)

**Comment by ArthurSonzogni** [comment]
> What are my other options tho? I want to use it in visual studio but there are no precompiled binaries. Which way would you recommend me to use ftxui in vs19?

I would recommend using cmake. What makes you feel this isn't the best choice for you?

**Comment by Creapermann** [comment]
> 
> 
> > What are my other options tho? I want to use it in visual studio but there are no precompiled binaries. Which way would you recommend me to use ftxui in vs19?
> 
> I would recommend using cmake. What makes you feel this isn't the best choice for you?

I got it, i just cloned the repo, build with cmake and linked the lib. I just didnt want to use cmake as my projects build system, but everything works fine now, Thanks for your help!

**Comment by Creapermann** [comment]
@ArthurSonzogni, but now when running my program, the whole TUI looks weird, its not the same flow (stuff are in different positions) as it were before. Do you have any idea why this could be? I m running x64 btw, mbe this info could help

**Comment by ArthurSonzogni** [comment]
Yes, sorry.
A bad patch broke the layout and was passing all the existing test. It landed and was reverted within 6 hours:
https://github.com/ArthurSonzogni/FTXUI/commit/98f49a581c63abe4399a99a207d384e969ca1260

You probably should take the latest version using the revert.

**Comment by Creapermann** [comment]
> 
> 
> Yes, sorry.
> A bad patch broke the layout and was passing all the existing test. It landed and was reverted within 6 hours:
> [98f49a5](https://github.com/ArthurSonzogni/FTXUI/commit/98f49a581c63abe4399a99a207d384e969ca1260)
> 
> You probably should take the latest version using the revert.

Thanks for the tip and the quick fix of the problem! It's all working fine now!!

Btw. could you maybe check out the issue i put on the arrow keys input for the windows console, thanks in advance
