### ISSUE TITLE
Segmantation fault launching every example after last commit

### ISSUE THREAD

**Issue by GiuseppeCesarano** [ArthurSonzogni/FTXUI#19]
I was doing the small changes required by the last commit to my code base. Running my application i was getting a "segmentation fault", so i decided to test with the examples, every example crashed for the same reason.

**Comment by ArthurSonzogni** [comment]
Thanks for reporting this. I don't get the same issue. I will investigate.

**Comment by ArthurSonzogni** [comment]
This was introduced by:
https://github.com/ArthurSonzogni/FTXUI/commit/e34f051f7aa31538f22b03130ec0656022a39419

And this failed the tests:
https://travis-ci.com/github/ArthurSonzogni/FTXUI/builds/167512229

**Comment by ArthurSonzogni** [comment]
I just added protection on the master branch to prevent merge that haven't pass the tests.
This will prevent future regressions.
