### ISSUE TITLE
Escape symbols in rendering text

### ISSUE THREAD

**Issue by CYB3RR0N1N** [ArthurSonzogni/FTXUI#192]
Hello and thanks for the lib ! I am trying to pass shell commands output into `text()` object, but it ignores '\n' symbols. Maybe I have missed something in docs?
Is there any builtin method to make it work ? 
I.e.
`
std::string test("Hello,\n World");
...
text(test);
...
`
Would cause output such as:
| Hello,
| World

Thanks !

**Comment by ArthurSonzogni** [comment]
Thanks!

What you could do is using `vbox` like:
```cpp
vbox({
  text("Hello,"),
  text("Wold")
})
```

If you need something that break automatically for every '\n', you could use:
```cpp
Elements split(std::string the_text) {
  Elements output;
  std::stringstream ss(the_text);
  std::string line;
  while (std::getline(ss, line))
    output.push_back(text(line));
  return output;
}
```

And then:
```cpp
vbox(split(the_text))
```

You might also want to take a look at the effects of:
```cpp
hflow(paragraph(the_text))  | size(HEIGHT, GREATER_THAN, 10)
```

**Comment by CYB3RR0N1N** [comment]
Thaks for a quick reply! I've tried the first option and it works pretty good )
