### ISSUE TITLE
HeartBeat Spinner

### ISSUE THREAD

**Issue by jonk4m** [ArthurSonzogni/FTXUI#198]
It would be really cool to have a spinner that looks like a heartbeat going across a horizontal line. 
![heartbeat](https://user-images.githubusercontent.com/17990160/130622979-57e54d51-e2de-47cc-9a0f-7bfa895a08a4.png)

**Comment by jonk4m** [comment]
Would've added the "enhancement" label to this but I don't know how, sorry!

**Comment by ArthurSonzogni** [comment]
Yes. That would be nice.

Do you want to add it?

**Comment by jonk4m** [comment]
My first time contributing to a project, but I can try! @ArthurSonzogni

**Comment by ArthurSonzogni** [comment]
I think this would require adding a couple a frame representing the animation inside:
https://github.com/ArthurSonzogni/FTXUI/blob/master/src/ftxui/dom/spinner.cpp

You can try if you want.

**Comment by ArthurSonzogni** [comment]
Implemented by @Suryced !
