### ISSUE TITLE
Add drop-down menu

### ISSUE THREAD

**Issue by MattBystrin** [ArthurSonzogni/FTXUI#204]
Hello! It would be really nice to have a drop-down menu widget in lib !
Thanks!

**Comment by ArthurSonzogni** [comment]
It can easily be build from other components I believe.

I will try to make one. That's a good idea I believe.

**Comment by ArthurSonzogni** [comment]
Some try:

https://user-images.githubusercontent.com/4759106/132992647-8338d1ba-0a9b-4f8d-a8a4-e364a62827e7.mp4

**Comment by ArthurSonzogni** [comment]
Some progress:
https://www.youtube.com/watch?v=14yGVIX2Tiw

Now with some the "vscroll_indicator" DOM element.

**Comment by MattBystrin** [comment]
@ArthurSonzogni looks cool ! Thank you!  Waiting for release !

**Comment by ArthurSonzogni** [comment]
I merged the patch to the dev branch. There are still minor glitches to fix. I am working on it.
