### ISSUE TITLE
Feature request: Support multi-paragraph text layout

### ISSUE THREAD

**Issue by Zjl37** [ArthurSonzogni/FTXUI#247]
I was enjoying the amazing library when I got crazy to find out that...

There is no proper way I can make two paragraphs (with word wrap) adjacent!

<details>
    <summary>I've tried...</summary>
this:

```cpp
	auto si = ScreenInteractive::Fullscreen();
	
	auto ui = Renderer([]() {
		return vbox({
			text("... title goes here ..."),
			hflow(paragraph("    To celebrate Dragon Boat Festival, an underwater dance performance titled Pray was aired on Henan TV last Saturday night, the first day of the holiday.")),
			hflow(paragraph("    Featuring the goddess of Luo River – a mysterious beauty best known in the poetry of Cao Zhi during the Three Kingdoms period, the dancer Haohao He, a former synchronized swimmer, recreated the elegance of this ancient Chinese goddess.")),
		});
	});

	si.Loop(ui);
```

... which spares the vertical space evenly for the two paragraphs, and this:

```cpp
	auto ui = Container::Vertical({
		Renderer([]() { return text("... title goes here ..."); }),
		Renderer([]() {
			return vbox({
				hflow(paragraph("    To celebrate Dragon Boat Festival, an underwater dance performance titled Pray was aired on Henan TV last Saturday night, the first day of the holiday.")),
				hflow(paragraph("    Featuring the goddess of Luo River – a mysterious beauty best known in the poetry of Cao Zhi during the Three Kingdoms period, the dancer Haohao He, a former synchronized swimmer, recreated the elegance of this ancient Chinese goddess.")),
			});
		})
	});
```

... where paragraphs collapse and only one line is visible, with a weird `g` at the top left corner:

```
g.. title goes here ...                                                         
    To celebrate Dragon Boat Festival, an underwater dance performance titled   
    Featuring the goddess of Luo River – a mysterious beauty best known in the  
```
</details>

And I notices this: <https://github.com/ArthurSonzogni/FTXUI/issues/68#issuecomment-762807087>

So FTXUI is missing an important and very basic feature for displaying longer texts, and the solution seems not clear.

I think a discussion about solution is needed here.

**Comment by ArthurSonzogni** [comment]
I took ~2 weeks of reflection and I am now ready to build something for supporting this feature. Wish me luck ;-)

**Comment by ArthurSonzogni** [comment]
Day 1: We are starting to see something! Here is an example with several complicated flow layout within vertical and horizontal flex box:

https://user-images.githubusercontent.com/4759106/141368881-3d570e6e-045e-4239-9fe6-45a6c91ba343.mp4

**Comment by ArthurSonzogni** [comment]
Another one:
https://user-images.githubusercontent.com/4759106/141370461-764a223b-5a03-497b-a8c3-fb6f26d22a37.mp4

**Comment by Zjl37** [comment]
Exciting to see that!

Actually I also looked into the code and tried to think of a practical and detailed approach. But as I also want to take "width-depends-on-height" elements into account (say, we might have "vflow" in the future), I found it very difficult.

Can you explain what changes you have currently made to the layout system?

**Comment by ArthurSonzogni** [comment]
Thanks!

The problem with the "with-depends-on-height" algorithm above are:
- I have to break API to make the computation to be split for X then Y.
- This doesn't support "height-depends-on-width", if I wanted to support vertical flow layout, as opposed to horizontal ones.

Here is my WIP patch:
https://github.com/ArthurSonzogni/FTXUI/commit/8197591a2d6afef900e41862c701800c9fadf4e1

What I did was defining a new optional signal going through the elements, indicating the current iteration and asking if a new iteration is needed. I used a struct, in order to be extendable in the future, without breaking the API.
```cpp
  // Layout may not resolve within a single iteration for some elements. This
  // allows them to request additionnal iterations. This signal must be
  // forwarded to children at least once.
  struct Status {
    int iteration = 0;
    bool need_iteration = false;
  };
  virtual void Check(Status* status);
```

Default implementation is:
```cpp
void Node::Check(Status* status) {
  for (auto& child : children_)
    child->Check(status);
  status->need_iteration |= (status->iteration == 0);
}
```
Which propagate the signal to every element, and return it needs one iteration of the layout algorithm.


The Render algorithm become:
```cpp
/// @brief Display an element on a ftxui::Screen.
/// @ingroup dom
void Render(Screen& screen, Node* node) {
  Box box;
  box.x_min = 0;
  box.y_min = 0;
  box.x_max = screen.dimx() - 1;
  box.y_max = screen.dimy() - 1;

  Node::Status status;
  node->Check(&status);
  while (status.need_iteration && status.iteration < 20) {
    // Step 1: Find what dimension this elements wants to be.
    node->ComputeRequirement();

    // Step 2: Assign a dimension to the element.
    node->SetBox(box);

    // Check if the element needs another iteration of the layout algorithm.
    status.need_iteration = false;
    status.iteration++;
    node->Check(&status);
  }

  // Step 3: Draw the element.
  screen.stencil = box;
  node->Render(screen);

  // Step 4: Apply shaders
  screen.ApplyShader();
}
```

The, we have to provide an alternative implementation for the `hflow` element. At iteration zero, it is configured with `dim_x_to_ask = infinity`. In `ComputeRequirement`, it returns width=dim_x_to_ask and height computed given its width. In `SetBox`, it reduces `dim_x_to_ask` if given less than asked and starts a new iteration.

There are still a lot of work for convincing me this is good enough. I will have to work on some tests.

**Comment by Zjl37** [comment]
Hmm, after looking though your implementation, I found it quite different to what I thought, and I doubt that multiple iteration be reliable.

I would like to post my solution here for a reference:

### My solution

(just thought, no code written yet)

1. A new variable should be added to `struct Requirement` to indicate whether the node's "height is depend on width" and its "width is depend on height", let's call it "dimension dependency" for now, call the values "HDW" and "WDH" for short.
2. The general idea is to calculate different parts of requirements separately -- set the depend-on dimension first, then compute the other dimension.
3. methods of `class Node` -- `virtual void ComputeRequirement()` and `virtual void SetBox(Box box);` is broken into the following several methods: (the name not sure yet, and the actual way to implement may differ)
    - `virtual void ComputeRequirementBegin()`, to compute "dimension dependency", propagated bottom-up.
    - `virtual pair<std::optional<int>, std::optional<int>> ComputeDimension(<** an enum value that can be COMPUTE_X, COMPUTE_Y or COMPUTE_XY **>)`
    - `virtual void SetDimension(std::optional<int> x, std::optional<int> y)`
    - `virtual void ComputeRequirementEnd()`, to compute selection and selected box.
5. Procedure:
    - First call `ComputeRequirementBegin`, and the all elements know the "dimension dependency". Then the root element do according to this dependency:
        * if dependency is none, call `ComputeDimension(COMPUTE_XY) -> SetDimension(x, y)`
        * if dependency is HDW, call `SetDimension(x, std::nullopt_t) -> ComputeDimension(COMPUTE_Y) -> SetDimension(std:nullopt_t, y)`
        * if dependency is WDH, call `SetDimension(std::nullopt_t, y) -> ComputeDimension(COMPUTE_X) -> SetDimension(x, std:nullopt_t)`
        * if dependency is (HDW | WDH), call `SetDimension(x, y)`.
    - The (HDW | WDH) case is really hard. I juggled with a html+css page and found some rules: On `SetDimension` called (here both dimensions must be available), 
        * A (HDW | WDH) hbox should first compute its WDH children's width, giving them a maximum initial height. Then spare the remaining width with other HDB and (HDW | WDH) children (evenly? or using a proportion?).
        * A (HDW | WDH) vbox should do similarily. (compute HDW children's height first...)
    - On each method call, (still) the same method of the children is called, except that when `SetDimension` is called, a (HDW | WDH) element may call its children's `ComputeDimension`.

### Comment

The `dimx_to_ask_` logic is hard to understand. Maybe `dimx_to_ask_ = std::min(dimx_to_ask_, given);` isn't at a good place, or its name is awful. (Why dimx_to_ask_ gets shrank when the available height is not enough?)

**Comment by Zjl37** [comment]
### question

I noticed that, in the second video you posted, the nested hbox's width is always about twice as the remaining space in that row, which I'm aware that previous version can't do (, and my solution can't do either). (I mean the nested hbox and the paragraph left to it are just two elements of a hbox. Normally when both's `flex-grow` is set, they should have 1:1 width.) Can you explain this? Is this some side effect?

**Comment by ArthurSonzogni** [comment]
Thanks @Zjl37 for the feedback!

Indeed, what I prototyped yesterday is still a prototype. Definitively not ready yet. 

Maybe I can learn from Chrome's [implementation](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/third_party/blink/renderer/core/layout/ng/README.md) for new ideas.

I took a look at your proposition. I don't understand fully for now. I will try taking more time to get it. I think it would help if you could show on a simple example how this works recursively.

----

> ### question
> I noticed that, in the second video you posted, the nested hbox's width is always about twice as the remaining space in that row, which I'm aware that previous version can't do (, and my solution can't do either). (I mean the nested hbox and the paragraph left to it are just two elements of a hbox. Normally when both's `flex-grow` is set, they should have 1:1 width.) Can you explain this? Is this some side effect?

It is the side effect of the current algoritm implementing `vbox` and `hbox`. See:
https://github.com/ArthurSonzogni/FTXUI/blob/master/src/ftxui/dom/box_helper.cpp

Note that there are two kind of flexibility. The flexibility to shrink and the flexibility to grow.

When the size we got is lower than what we asked to render the full `hbox`'s children, and dispatching the negative space into `shrinkable` children won't be enough, we need to dispatch the negative space into normal elements. We don't take any flex coefficients into account, because they aren't shrinkable, we just remove from what they asked the negative space proportionally to what they require.

In our case when the children are `hflow` elements, they asked at iteration=0 with=`infinity` on the left and the groups of elements on the right asked right 2×`infinity.
As a result, we dispatch proportionally the negative space on the two sides. As a results, they conserve the 1/3 2/3 ratios.

```cpp
// Called when the size allowed is lower than the requested size, and the
// shrinkable element can not absorbe the (negative) extra_space. This assign
// zero to shrinkable elements and distribute the remaining (negative)
// extra_space toward the other non shrinkable elements.
void ComputeShrinkHard(std::vector<Element>* elements,
                       int extra_space,
                       int size) {
  for (Element& element : *elements) {
    if (element.flex_shrink) {
      element.size = 0;
      continue;
    }

    int added_space = extra_space * element.min_size / std::max(1, size);
    extra_space -= added_space;
    size -= element.min_size;

    element.size = element.min_size + added_space;
  }
}
```

**Comment by ArthurSonzogni** [comment]
One interesting video:
https://www.youtube.com/watch?v=SyUBuio_ooE&t=1592s

**Comment by Zjl37** [comment]
Hi @ArthurSonzogni , thanks for the explanation on size calculation. Now I understand. In fact, I'm not familiar with web, and when I went reading CSS flexbox tutorials, I found some similarity: the required width in first iteration in your prototype is like `flex-basis` in CSS, except that in CSS it's not set to infinity for paragraphs, but instead `max-content` size(, as suggested [in this MDN document](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Controlling_Ratios_of_Flex_Items_Along_the_Main_Ax#the_flex-basis_property)).

The size calculation is not a key point here, but we may keep an eye for it when evaluating solutions.

---

> Indeed, what I prototyped yesterday is still a prototype. Definitively not ready yet.

I see.

**Comment by ArthurSonzogni** [comment]
I would like to support vertical flow and a few other variations. Here is a tentative API to describe this:
```cpp
Element flow(Elements, FlowConfig)
```

```cpp
struct FlowConfig {
  enum Direction {
    Row,
    RowInversed,
    Column,
    ColumnInversed,
  };

  enum Wrap {
    NoWrap,
    Wrap,
    WrapInversed,
  }

  enum Align {
    Start,
    Center,
    End
    Stretch,
    SpaceBetween,
    SpaceAround,
    SpaceEvenly,
  }

  Direction direction = Row;
  Wrap wrap = Wrap;
  Align align_main_axis = Start;
  Align align_cross_axis = Start;
  int gap_main_axis = 0;
  int gap_cross_axis = 0;

  // Constructor pattern. For use like:
  // ```
  // FlowConfig()
  //    .SetDirection(FlowConfig::Row)
  //    .SetWrap(FlowConfig::Wrap);
  // ```
  FlowConfig& SetDirection(FlowConfig::Direction direction);
  FlowConfig& SetWrap(FlowConfig::Wrap wrap);
  FlowConfig& SetAlignMainAxis(FlowConfig::Align align);
  FlowConfig& SetAlignCrossAxis(FlowConfig::Align align);
  FlowConfig& SetGapMainAxis(int gap);
  FlowConfig& SetGapCrossAxis(int gap);
}
```

**Comment by Zjl37** [comment]
I just modified and edited my proposition, which looks clearer and more practical. Please have a look again.

**Comment by ArthurSonzogni** [comment]
Sorry for this long week without any update...

I worked on implementing all the possible flexbox layout. Having a way to test both height-depends-on-width and width-depends-on-height is going to be very helpful building test and selecting the right algorithm.

FlowConfig::Direction::Row:
-------------------------------------

https://user-images.githubusercontent.com/4759106/142773234-641eb35d-279a-40b3-922c-af09dc4cc026.mp4

FlowConfig::Direction::Inversed:
-------------------------------------

https://user-images.githubusercontent.com/4759106/142773245-cbf9fdb8-0da0-40ba-9966-6b47ff7966ff.mp4


FlowConfig::Direction::ColumnInversed:
-------------------------------------

https://user-images.githubusercontent.com/4759106/142773252-bad4b52e-7cee-47d7-8993-0b09620bec47.mp4

FlowConfig::Direction::Column:
-------------------------------------

https://user-images.githubusercontent.com/4759106/142773248-e60adf13-31b5-4bf3-b732-4d8249981138.mp4

**Comment by ArthurSonzogni** [comment]
I made a component to test the different flexbox options:
WIP:

https://user-images.githubusercontent.com/4759106/142777071-f21b2a6b-b845-46be-bee6-ba1ae747f3e0.mp4

**Comment by ArthurSonzogni** [comment]
Some new videos. I will soon be able to publish it.

https://user-images.githubusercontent.com/4759106/145106956-7f360ad2-d948-40f6-ad61-962a650e17b8.mp4

https://user-images.githubusercontent.com/4759106/145107473-af45759b-99dd-4710-8a3c-66b5cd257221.mp4

**Comment by ArthurSonzogni** [comment]
@Zjl37, I landed the flexbox change.

This brings the following elements:
- `flexbox`
And the following built from `flexbox`:
- `paragraph`
- `paragraphAlignLeft`
- `paragraphAlignRight`
- `paragraphAlignCenter`
- `paragraphAlignJustify`
- `hflow`
- `vflow`

This is a breaking change and it will be included inside version 2.0

Could you please let's give it a try and give your opinions?

**Comment by ArthurSonzogni** [comment]
(Marking this as fixed)

**Comment by Zjl37** [comment]
Hi @ArthurSonzogni , it's exciting to see the feature landed!

From the user's view, the change is great and inspiring, everything working as expected, and I'll of course happily use it. However, as I have studied the code, I'm mostly concerned about the core changes to `Node` -- the many-iteration approach:

1. In some cases, the current implementation unnecessarily slows down the size calculation process, which could have took only 2 iterations in theory if we know more information. More specifically, this happens when   
    - there is no enough space for all flexbox content at all.
    - row flexbox and column flexbox inside the same flexbox.

2. The "many iteration" approach hides the real demand of an element, which sounds like a defective design. Its intent is not clear at first sight. I mean when someone wants to implement a new kind of element, they might write not functioning code more easily. And that passing `Node::Status` to children's `Check` by pointer -- what if they change `int iteration`?   
If this is for extensibility, I can't think of any other circumstances that needs more than 2 iterations.

**Comment by ArthurSonzogni** [comment]
![image](https://user-images.githubusercontent.com/4759106/146256043-62ba80b5-4fde-42c0-9a8a-8fb5f5e0ca33.png)

I agree this is not ideal.

This can even give some unexpected results when using nested flexbox.

I should aim for better before releasing 2.0. However I am not sure how. I know there is the solution you kindly provided in: https://github.com/ArthurSonzogni/FTXUI/issues/247#issuecomment-967122836 but I can't really convince it works or won't, and I am afraid breaking existing users to much.

Maybe I should ask directly Chromium engineer, or try to learn from other C++ projects like: https://yogalayout.com/

**Comment by Zjl37** [comment]
> and I am afraid breaking existing users to much.

I see.

May I ask what is a version 2.0? We're now in 0.11, are we jumping across major version 1?

**Comment by ArthurSonzogni** [comment]
> May I ask what is a version 2.0? We're now in 0.11, are we jumping across major version 1?

The flexbox change modified the behavior of `hbox` and `paragraph`. Updating FTXUI will break folks using it. So I have to move from 0.11 to 1.0

(Yes, I said 2.0 wrongly)
