### ISSUE TITLE
Reference to input content not functioning correctly

### ISSUE THREAD

**Issue by YottaYocta** [ArthurSonzogni/FTXUI#251]
I downloaded and ran the "homescreen" example; after hitting "enter" on input field, input is not cleared
```c++
  std::vector<std::string> input_entries;
  int input_selected = 0;
  Component input = Menu(&input_entries, &input_selected);
 
  auto input_option = InputOption();
  std::string input_add_content;
  input_option.on_enter = [&] {
    input_entries.push_back(input_add_content);
    input_add_content = "";
  };
  Component input_add = Input(&input_add_content, "input files", input_option);
```
instead, _add_content_ is added to _input_entries_, but the input is not cleared. I also ran into this issue in a personal project

**Comment by YottaYocta** [comment]
I think I may have found the issue; in ftxui/component/ input.cpp, a stringref is being dereferenced and passed into a wstring converter. This creates a copy, which causes ftxui to lose the reference to the user-specified value

```c++

class InputBase : public WideInputBase {
  public:
    InputBase(StringRef content,
      ConstStringRef placeholder,
      Ref<InputOption> option)
        : WideInputBase(&wrapped_content_,
                        std::move(placeholder),
                         std::move(option)),
           content_(std::move(content)),
           wrapped_content_(to_wstring(*content_)) {}

```

**Comment by ArthurSonzogni** [comment]
Indeed! I will fix it.

The problem is that changes from outside are not reflected inside.

**Comment by YottaYocta** [comment]
Alright, thanks again for the amazing library!

**Comment by ArthurSonzogni** [comment]
(Fixed)
