### ISSUE TITLE
Windows can not be used normally

### ISSUE THREAD

**Issue by YuzukiTsuru** [ArthurSonzogni/FTXUI#27]
![image](https://user-images.githubusercontent.com/12003087/87326567-7d227380-c565-11ea-9ad9-7f1f9c921488.png)

```cpp
std::string reset_position;
    auto document =
            ftxui::vbox({
                                ftxui::text(L"GNU Affero General Public License v3.0") | ftxui::bold | color(ftxui::Color::Green) | ftxui::border,
                         hflow(
                                 ftxui::paragraph(L"The GNU Affero General Public License is a free, copyleft license for"
                                           L"software and other kinds of works, specifically designed to ensure"
                                           L"cooperation with the community in the case of network server software."
                                           L"The licenses for most software and other practical works are designed"
                                           L"to take away your freedom to share and change the works.  By contrast,"
                                           L"our General Public Licenses are intended to guarantee your freedom to"
                                           L"share and change all versions of a program--to make sure it remains free"
                                           L"software for all its users.\n"
                                           L"When we speak of free software, we are referring to freedom, not"
                                           L"price.  Our General Public Licenses are designed to make sure that you"
                                           L"have the freedom to distribute copies of free software (and charge for"
                                           L"them if you wish), that you receive source code or can get it if you"
                                           L"want it, that you can change the software or use pieces of it in new"
                                           L"free programs, and that you know you can do these things.  "
                                           L"Developers that use our General Public Licenses protect your rights"
                                           L"with two steps: (1) assert copyright on the software, and (2) offer"
                                           L"you this License which gives you legal permission to copy, distribute"
                                           L"and/or modify the software.")) |
                                 ftxui::border,
                 });

    auto screen = ftxui::Screen::Create(ftxui::Dimension::Full());
    Render(screen, document);
    std::cout << reset_position << screen.ToString() << std::flush;
    reset_position = screen.ResetPosition();
    getchar();
    return 0;
```

**Comment by YuzukiTsuru** [comment]
and `ftxui::Menu` can not select

**Comment by ArthurSonzogni** [comment]
Thank for reporting this. I will take a look shortly.

**Comment by ArthurSonzogni** [comment]
Here is what I got:
https://asciinema.org/a/l0EAt5kwQLDkXEgUDDeJn5G5W

It seems to work as expected to me. Could you describe what do you think is a problem?

**Comment by YuzukiTsuru** [comment]
I tested that all third-party terminals on Windows display normal, but only Windows CMD, PowerShell displays abnormal

PowerShell
![image](https://user-images.githubusercontent.com/12003087/87503930-01751380-c698-11ea-8d62-7977ad0f8de2.png)

Windows CMD
![image](https://user-images.githubusercontent.com/12003087/87503948-105bc600-c698-11ea-8554-3f8cc350a6bf.png)

Windows Terminal CMD
![image](https://user-images.githubusercontent.com/12003087/87504012-2ec1c180-c698-11ea-8f06-acc8b891aa87.png)

Windows Terminal PowerShell
![image](https://user-images.githubusercontent.com/12003087/87504045-44cf8200-c698-11ea-9089-74508abf9c2c.png)

**Comment by YuzukiTsuru** [comment]
Although `Windows Terminal` it can be displayed, the display screen is blinking

**Comment by ArthurSonzogni** [comment]
Thanks for the screenshot!

It looks like support for ANSI/VT100 codes on some windows terminal is not supported / disabled by default.
See this answer:
https://stackoverflow.com/a/51681675/5112390

I don't own a Windows desktop, but we just need to call SetConsoleMode. I already did that when using a ScreenInteractive:
https://github.com/ArthurSonzogni/FTXUI/blob/7f7775ba622140435af9fe8c0b442c3539ab5056/src/ftxui/component/screen_interactive.cpp#L217

I just need to add support for Screen. I will try today.

**Comment by ArthurSonzogni** [comment]
I took a Windows desktop, learn how to develop on it (it was unexpectedly hard), but I finally made it. I just uploaded a patch fixing most of your issues (on branch origin/dev)

I am also seeing a few more issues on windows. I will fix them soon.

**Comment by YuzukiTsuru** [comment]
Thanks, it can be displayed now, but there is still a problem with the menu component. No way to select items.

![D__GitHub_lr_cmake-build-release-visual-studio-any-cpu_A](https://user-images.githubusercontent.com/12003087/87762331-8d786e00-c845-11ea-850d-107871698631.gif)

the code is:
https://github.com/ArthurSonzogni/FTXUI/blob/22afacc28badb35680e7fe03461680c52acbe507/examples/component/menu.cpp#L5-L25

**Comment by ArthurSonzogni** [comment]
I don't fully remember what is

**Comment by ArthurSonzogni** [comment]
I guess this is fixed right? I don't fully remember.

**Comment by iganinja** [comment]
I'm using tag 3.0.0 in Windows 8 CMD and it looks not very well

![image](https://user-images.githubusercontent.com/8440619/174335603-e1699ee8-461b-48d1-aa08-ddb12d1ee220.png)

This is the starter example/project

**Comment by ArthurSonzogni** [comment]
Hello @iganinja,
Could you specify how you are building and linking FTXUI?

**Comment by iganinja** [comment]
Sure @ArthurSonzogni 

This is the whole CMakeLists.txt:

`cmake_minimum_required(VERSION 3.5)

project(TMSE LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(TMSE main.cpp)

include(FetchContent)

FetchContent_Declare(ftxui
  GIT_REPOSITORY https://github.com/ArthurSonzogni/ftxui
  GIT_TAG v3.0.0
)

FetchContent_GetProperties(ftxui)
if(NOT ftxui_POPULATED)
  FetchContent_Populate(ftxui)
  add_subdirectory(${ftxui_SOURCE_DIR} ${ftxui_BINARY_DIR} EXCLUDE_FROM_ALL)
endif()

target_link_libraries(TMSE
  PRIVATE ftxui::screen
  PRIVATE ftxui::dom
  PRIVATE ftxui::component
)
`
