### ISSUE TITLE
throw_bad_array_new_lenghtv runtime error

### ISSUE THREAD

**Issue by KitCarson03** [ArthurSonzogni/FTXUI#276]
i got a throw_bad_array_new_lenghtv runtime error when  running examples coming with the sources and program i tried to do.

cmake build correctly on:
Windows 10
MSYS2 Mingw-w64
iwyu not set

**Comment by ArthurSonzogni** [comment]
Could you provide the source you have tried compiling?

**Comment by KitCarson03** [comment]
Also the examples provided with the library source show this issue

**Comment by ArthurSonzogni** [comment]
Would you mind providing a stack trace for me to know where this error is coming from?

You can use gdb for instance:
https://www.cs.toronto.edu/~krueger/csc209h/tut/gdb_tutorial.html#:~:text=%22backtrace%22%20command%20tells%20gdb%20to%20list%20all%20the%20function%20calls%20(that%20leads%20to

**Comment by ArthurSonzogni** [comment]
Hi @KitCarson03,
Would you have any updates?

**Comment by ArthurSonzogni** [comment]
Hi @KitCarson03,
Would you have any updates?
