### ISSUE TITLE
Do not merge box characters that does not belong to separator

### ISSUE THREAD

**Issue by Zjl37** [ArthurSonzogni/FTXUI#285]
Hi, I'm migrating my tui game to use FTXUI, and find this annoying.

See [the `dev` branch of my `planeFight2`](https://github.com/Zjl37/planeFight2/tree/dev).

I use box drawing characters to represent plane shape. This causes unwanted effect for some map arrangements.

**Comment by ArthurSonzogni** [comment]
I think this is solvable. I could add a bit to the screen's Pixel telling: "This cell is allowed to merge".

I will take a look.
