### ISSUE TITLE
P conversion makes FTXUI stop working

### ISSUE THREAD

**Issue by GiuseppeCesarano** [ArthurSonzogni/FTXUI#31]
While using an input box writing "P" makes the program crash.

**Comment by ArthurSonzogni** [comment]
Windows is very weird ;-)

I now have a dual boot on Windows. I will take a look. I can reproduce.

**Comment by GiuseppeCesarano** [comment]
I was talking about the bug fixed with the pull request. _I'm on Arch btw_
