### ISSUE TITLE
Add support for SIGSTP

### ISSUE THREAD

**Issue by ArthurSonzogni** [ArthurSonzogni/FTXUI#330]
### Discussed in https://github.com/ArthurSonzogni/FTXUI/discussions/309

<div type='discussions-op-text'>

<sup>Originally posted by **MattBystrin** January 12, 2022</sup>
Hi, @ArthurSonzogni ! 
Today I've noticed that ScreenInteracitve do not works with SIGSTP. I've rarely use ctrl+z in term in case i usualy work with tmux, but maybe someone finds it handy. What do you think ?
</div>

**Comment by MattBystrin** [comment]
Sorry, I misspelled the signal name. The right version is SIGTSTP

**Comment by ArthurSonzogni** [comment]
Fixed.

**Comment by MattBystrin** [comment]
Hello @ArthurSonzogni ! 
I've checked the improvements - everything is working as expected. 
Great job !

**Comment by ArthurSonzogni** [comment]
Thanks!
