### ISSUE TITLE
on_enter callback doesn't work

### ISSUE THREAD

**Issue by brokensword2018** [ArthurSonzogni/FTXUI#337]
Normally, it works well。
in ubuntu, when I use bind command to start my program based on FTXUI. the on_enter callback of input doesn,t work.
like this. add "bind -x '"\C-g":<my_program>" to ~/.bashrc. so I can use 'ctrl+g' to start my program.

**Comment by ArthurSonzogni** [comment]
What are trying to achieve with bind, and ctrl+g?

**Comment by brokensword2018** [comment]
> 

my program based on FTXUI

**Comment by brokensword2018** [comment]
> 
my program based on FTXUI, I use ctrl+g to start my program

**Comment by ArthurSonzogni** [comment]
Could you execute the example:
https://arthursonzogni.com/FTXUI/examples/?file=component/print_key_press
Using your "bind"?

And see what is sent for the "enter" and "space" characters?

**Comment by ArthurSonzogni** [comment]
@brokensword2018  ?

**Comment by brokensword2018** [comment]
> 

enter is ( 13 ) -> (special)                                                                                                                                            │
space is ( 32 ) -> character( )

**Comment by brokensword2018** [comment]
> @brokensword2018 ?

enter is ( 13 ) -> (special) 
space is ( 32 ) -> character( )

**Comment by ArthurSonzogni** [comment]
It seems to be working fine.
If you believe this is a bug in FTXUI, could you post a reproducer?

It is probably an issue with you program. I can't really say what, because you haven't posted it.

**Comment by brokensword2018** [comment]
> It seems to be working fine. If you believe this is a bug in FTXUI, could you post a reproducer?
> 
> It is probably an issue with you program. I can't really say what, because you haven't posted it.

https://github.com/brokensword2018/ftxui-starter  you can use this to reproduce the problem .
add 
bind -x '"\C-m":<the abs path of ftxui-starter>' 
to ~/.bashrc , then source ~/.bashrc, and press ctrl + m.
use the way to start the program, there no "press enter" int 1.log。
and enter will start the program.

**Comment by ArthurSonzogni** [comment]
Thanks!
I can reproduce.

Instead of sending "10" (New line) when pressing Enter, it sounds like we get "13" (Carriage Return) when going through "bind". I am not sure why bind works this way.

**Comment by ArthurSonzogni** [comment]
I think what I can do, is converting 10/13 code into one of the two. This would make Window / non-Window consistent. This would also make Linux / Linux+Bind consistent.
