### ISSUE TITLE
[Question] Is it possible to disable SIGTSTP handling?

### ISSUE THREAD

**Issue by vnepogodin** [ArthurSonzogni/FTXUI#348]
![image](https://user-images.githubusercontent.com/37552959/155805214-a1c8fcd7-85b2-46a6-a6b0-7f4ec17e7a7d.png)

I saw that started to happen when I updated ftxui to your master branch with SIGTSTP handling support

For example:
I want to execute bash interactively, and after exit back to ftxui context without suspending the parent program it self

**Comment by ArthurSonzogni** [comment]
SIGTSTP handling is only about "uninstalling" all the terminal hooks previously installed, before the actual SIGTSTP handler. I don't believe it exists any good reasons to disable SIGTSTP handler.

I don't really understand your example. You can get back to FTXUI, only once you have exited bash. Isn't it?

**Comment by ArthurSonzogni** [comment]
Hey @vnepogodin would you have answers to my previous comment?

**Comment by vnepogodin** [comment]
> SIGTSTP handling is only about "uninstalling" all the terminal hooks previously installed, before the actual SIGTSTP handler. I don't believe it exists any good reasons to disable SIGTSTP handler.
> 
> I don't really understand your example. You can get back to FTXUI, only once you have exited bash. Isn't it?

Yes I can get back once I exited bash. In general it should not suspend the program, just "installing" and getting back to TUI screen

**Comment by vnepogodin** [comment]
> Hey @vnepogodin would you have answers to my previous comment?

I have a question:
How can I disable SIGTSTP handling?

I guess this one should be enough:
https://github.com/ArthurSonzogni/FTXUI/blob/master/src/ftxui/component/screen_interactive.cpp#L427

**Comment by vnepogodin** [comment]
As far as I can see it should be it
Because after it receives SIGTSTP  it do "uninstall", and throws SIGTSTP again(idk why it should work like that), and then installs again at the end
![image](https://user-images.githubusercontent.com/37552959/159140037-78417f2c-c0e3-4c65-9410-06cda05182b7.png)

**Comment by ArthurSonzogni** [comment]
`std::raise(SIGTSTP)` invoke the "default" SIGSTP handler.

The default handler for SIGTSTP is to wait for a "SIG_UNBLOCK" using:
https://man7.org/linux/man-pages/man2/sigprocmask.2.html

It just means the application will do nothing anymore, up until the user get back to it later.

**Comment by ArthurSonzogni** [comment]
I didn't hear back. Please let me know if there are anything I can do. Otherwise, I will close this issue.
