### ISSUE TITLE
CPU load at 100%

### ISSUE THREAD

**Issue by thelex0** [ArthurSonzogni/FTXUI#381]
after rendering the table, the program crashes and the CPU usage rises to 100%
```
void Table1(const vector<vector<string>>& vec) {
    auto screen = ScreenInteractive::FitComponent();
    auto table = new Table(vec);
    auto back_button = Button("Back", screen.ExitLoopClosure());
    auto layout = Container::Vertical({
        back_button
        });
    auto renderer = Renderer(layout, [&] {
        return vbox({
            text("TableClass"),
            separator(),
            table->Render(),
            back_button->Render(),
            }) |
            border;
    });
    screen.Loop(renderer);
}
```
Here is the question - what did I do wrong?

**Comment by ArthurSonzogni** [comment]
I don't see anything wrong, except that you are leaking the Table object.

CPU usage should be close to zero, as long as you don't move the mouse or
type on your keyboard. I only expect a 2 threads to wake up 60 time per
seconds for a potential animation that wouldn't come.

How big is the table?

**Comment by thelex0** [comment]
> I don't see anything wrong, except that you are leaking the Table object. CPU usage should be close to zero, as long as you don't move the mouse or type on your keyboard. I only expect a 2 threads to wake up 60 time per seconds for a potential animation that wouldn't come. How big is the table? Le mar. 19 avr. 2022, 23:15, thelex0 ***@***.***> a écrit :
> […](#)

Just a couple of lines. Here is the program code where this function is executed. No complex logic [https://pastebin.com/pCP71Gc3](Click)
After briefly reading the documentation, I could not find dangerous moments that may arise here.

**Comment by ArthurSonzogni** [comment]
I get it.
You aren't meant to reuse the "Table". It is lost after you render it:
https://github.com/ArthurSonzogni/FTXUI/blob/master/src/ftxui/dom/table.cpp#L177

I should probably make it easier to debug for the next developer.

Correct code is:
```cpp
void Table1(const vector<vector<string>>& vec) {
  auto screen = ScreenInteractive::FitComponent();
  auto back_button = Button("Back", screen.ExitLoopClosure());

  auto renderer = Renderer(back_button, [&] {
    auto table = Table(vec);
    return vbox({
               text("TableClass"),
               separator(),
                   ->Render(),
               back_button->Render(),
           }) |
           border;
  });
  screen.Loop(renderer);
}
```
