### ISSUE TITLE
How to make Elements in a vbox scroll, as the number of elements exceeds what can be displayed on the screen

### ISSUE THREAD

**Issue by VedantParanjape** [ArthurSonzogni/FTXUI#39]
Reference code: https://github.com/VedantParanjape/simpPRU/blob/ad3d0fb804aa7a0b3585906a36b73e6be75f5348/src/console/console.cpp#L147

https://asciinema.org/a/SYtxNwZLMhx6OBQKs2ohPyWRx

Please take a look at this video, when vbox is completely filled, adding new elements, doesn't display them, can we do something like it scrolls down like in a terminal.

**Comment by ArthurSonzogni** [comment]
Yes, this is already built in. You have to wrap your element inside the "frame" decorator. (Or xframe, yframe)

There is an example here:
https://github.com/ArthurSonzogni/FTXUI/blob/master/examples/component/checkbox_in_frame.cpp

**Comment by VedantParanjape** [comment]
Hey,
https://asciinema.org/a/929mFrhSQZkVCP0UCCCQFwpDS

i did this
```
hbox({
                    hflow({
                        vbox({
                            output_box | frame,
                        }),
                    }) | border,
```

It doesn't work

**Comment by ArthurSonzogni** [comment]
It needs to know where to focus the view.
You need to decorate the focused element using 'selected' or 'focus' 
That's what the implementation of every component are using, for instance RadioBox.cpp

**Comment by ArthurSonzogni** [comment]
You could write:
```cpp
vbox({
  output_box ,
  text(L"") | select
})
```

**Comment by VedantParanjape** [comment]
Still doesnot work.

Here my complete render function call

```cpp
Element Render() override 
        {
            return border(vbox({
                // Console and PRU selection
                hbox({
                    hflow({
                        vbox({
                            vbox(output_box),
                            text(L"") | ftxui::focus,
                            }) | frame | border,
                    }) | border,
                                        
                    vbox({
                        hcenter(bold(text(L"PRU"))),
                        separator(),
                        right_menu.Render(),
                    }) | border,
                }) | flex,
                
                // Input box and PRU start/stop
                vbox({
                    hbox({
                        text(L" send : "),
                        input_box.Render(),
                        separator(),
                        pru_start_top.Render(),
                    }),
                }) | border,
            }));
        }
```

**Comment by ArthurSonzogni** [comment]
It is because in your code, you selected every elements. Only one needs to be selected, otherwise it won't know which one to select.
You need to remove "select" here:
https://github.com/VedantParanjape/simpPRU/blob/ad3d0fb804aa7a0b3585906a36b73e6be75f5348/src/console/console.cpp#L183

In your code, I replaced:
```cpp
hflow({
  vbox({
      output_box ,
  }),
}) | border,
```
by:
```cpp
vbox({
    vbox({output_box}),
    text(L"...") | ftxui::select,
}) | frame | border,
```

and it was correctly working.

**Comment by VedantParanjape** [comment]
> It is because in your code, you selected every elements. Only one needs to be selected, otherwise it won't know which one to select.
> You need to remove "select" here:
> https://github.com/VedantParanjape/simpPRU/blob/ad3d0fb804aa7a0b3585906a36b73e6be75f5348/src/console/console.cpp#L183

Damn, I'm an idiot. I don't even know how that `select` got there 😭 

That code you provided just did the job, thanks for the help buddy.

I am using this in my google summer of code project, can you add this project to README, "projects made using" section.

Thanks and Regards,
Vedant Paranjape
