### ISSUE TITLE
Segfault when calling ScreenInteractive.PostEvent()

### ISSUE THREAD

**Issue by XNUConner** [ArthurSonzogni/FTXUI#402]
If `ScreenInteractive` is not in a `.Loop()` and `.PostEvent()` is called it will cause a segfault:
```cpp
#include "ftxui/component/event.hpp"
#include "ftxui/component/screen_interactive.hpp"

int main(void) {
  auto screen = ftxui::ScreenInteractive::TerminalOutput();
  screen.PostEvent(ftxui::Event::Custom);
}
```

```
./ftxui-starter 
Segmentation fault (core dumped)
```
Can this be changed so that `PostEvent()` does nothing when `screen` is not active?

**Comment by XNUConner** [comment]
Made PR to fix this [here](https://github.com/ArthurSonzogni/FTXUI/pull/403).

**Comment by ArthurSonzogni** [comment]
Thanks! PR merged.
