### ISSUE TITLE
Can't build on termux and can't example on termux

### ISSUE THREAD

**Issue by toomails9999** [ArthurSonzogni/FTXUI#404]
Please help me 
Clang version 14.0.1

**Comment by ArthurSonzogni** [comment]
Hello,

> Please help me

This isn't helpful. Could you provide something relevant to your specific problem. What do you mean by "can't build"? What are you trying to do? What command are you trying?

**Comment by ArthurSonzogni** [comment]
Let me close this issue for inactivity. Please reopen if there are any updates.
