### ISSUE TITLE
Add support for pop-up box that floats above the tui (and takes focus)

### ISSUE THREAD

**Issue by BlackEdder** [ArthurSonzogni/FTXUI#410]
It would be nice to have support for a pop-up style window, which opens floating above the centre of the screen (and takes focus). Similar to how the menu shows up in the lazygit tui.

Maybe I am missing something and this is already possible? If so, some pointers would be greatly appreciated!

**Comment by BlackEdder** [comment]
Nevermind, I seem to have found my answer here: https://github.com/ArthurSonzogni/FTXUI/blob/master/examples/component/modal_dialog.cpp

**Comment by ArthurSonzogni** [comment]
Yes, that's a good question and the right answer ;-)

Maybe we can think about adding ways to make it more straightforward, in a functional way if possible.

**Comment by BlackEdder** [comment]
There could be something similar to ftxui::Maybe(<element>, <flag>), called ftxui::Popup(<element>, <flag>), which will render an element at the centre of the screen on top of the current screen if the flag is set, (and take focus). But maybe that is too limiting/specific an implementation.

**Comment by ArthurSonzogni** [comment]
I added `Modal` in the PR. What do you think of it?

**Comment by lanza** [comment]
Yup, that's a reasonable implementation! Thanks!
