### ISSUE TITLE
Rendering issue with diming the lower layer

### ISSUE THREAD

**Issue by BlackEdder** [ArthurSonzogni/FTXUI#411]
I implemented a popup window and would like to dim the rest of the window when it opens. This works well, except that I have found a small rendering issue. As you can see, the right-hand side of the top bar is not dimmed properly.

![render_issue_ftxui](https://user-images.githubusercontent.com/845741/171809878-830f4002-1a75-4ca3-a667-8181f2b87a14.png)

Relevant code can be found here: https://gitlab.com/BlackEdder/rttt/-/blob/feature/ftxui/src/main.cpp#L169

**Comment by ArthurSonzogni** [comment]
This might be fixed thanks to:
https://github.com/ArthurSonzogni/FTXUI/pull/460
