### ISSUE TITLE
vcpkg package fails to configure

### ISSUE THREAD

**Issue by stnkl** [ArthurSonzogni/FTXUI#417]
When configuring the CMake project using the vcpkg package of ftxui the following error occurs:

```
cmake.exe -DCMAKE_BUILD_TYPE=Debug "-DCMAKE_MAKE_PROGRAM=C:/Program Files/JetBrains/CLion 2022.1.2/bin/ninja/win/ninja.exe" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -G Ninja -S C:\project -B C:\project\cmake-build-debug
-- Configuring done
-- Generating done
-- Build files have been written to: C:/project/cmake-build-debug

Problems were encountered while collecting compiler information:
	cc1plus.exe: fatal error: /utf-8: No such file or directory
```

The corresponding `CMakeLists.txt` file looks like this:

```cmake
cmake_minimum_required(VERSION 3.22)
project(main)
set(CMAKE_CXX_STANDARD 17)
find_package(ftxui CONFIG REQUIRED)
add_executable(main main.cpp)
target_link_libraries(main PRIVATE ftxui::dom ftxui::screen ftxui::component)
```
When using CMake FetchContent everything works as expected.

Could it be a bug in the vcpkg package or am doing it incorrectly?

**Comment by ArthurSonzogni** [comment]
This probably refers to these lines:
https://github.com/ArthurSonzogni/FTXUI/blob/master/cmake/ftxui_set_options.cmake#L46-L50

This is inside the "MSVC" condition, meaning it should apply only when using the Microsoft visual c++ compiler.
It seems to me `cc1plus` is not `MSVC`. This explains your problem.

Many people are using Windows and VCPKG and reported no problem. I guess you are trying to do something weird?
I am not using neither VCPKG nor Windows, so I can't help diagnose further the problem. Could you please post how you fixed it when you found the issue?

**Comment by stnkl** [comment]
I am using CLion which in turn uses Ninja as the default generator. Once I configure it in a way that it doesn't pass a generator explicitly it works. I don't know why CLion would set `MSVC` though. That really feels like unexpected behavior.

Using Visual Studio right away also works as expected.

Thanks for your answer and help in diagnosing it further!
