### ISSUE TITLE
[Bug] - Incorrect menu entry highlighting when multiple menus use same MenuOption

### ISSUE THREAD

**Issue by XNUConner** [ArthurSonzogni/FTXUI#426]
### Bug
In [menu_multiple.cpp](https://github.com/ArthurSonzogni/FTXUI/blob/master/examples/component/menu_multiple.cpp) navigating between menus works as expected.

However, if you change lines 43-45 to initialize each `Menu` in the initializer list with the **same** `MenuOption`
```cpp
  // This is buggy
  MenuOption opt;
  
  auto menu_global = Container::Vertical(
      {
          Window("Menu 1", Menu(&menu_entries[0], &menu_selected[0], &opt)),
          Window("Menu 2", Menu(&menu_entries[1], &menu_selected[1], &opt)),
          Window("Menu 3", Menu(&menu_entries[2], &menu_selected[2], &opt)),
      },
      &menu_selected_global);
```
Navigating between menus will result in the **highlighting** and the `>`  to not be in sync until a subsequent keypress.
I've attached a video of this behavior [here](https://user-images.githubusercontent.com/72773002/175837975-58fb3e11-bfc9-4b29-a779-7b4b58c0e546.mp4).

### A workaround
Using different `opt`s works fine, but I would expect that I would be able to share one `MenuOption` between multiple menus:
```cpp

  // This works
  MenuOption opt;
  MenuOption opt2;
  MenuOption opt3;
  
  auto menu_global = Container::Vertical(
      {
          Window("Menu 1", Menu(&menu_entries[0], &menu_selected[0], &opt)),
          Window("Menu 2", Menu(&menu_entries[1], &menu_selected[1], &opt2)),
          Window("Menu 3", Menu(&menu_entries[2], &menu_selected[2], &opt3)),
      },
      &menu_selected_global);

```

**Comment by avighnac** [comment]
I'm able to replicate this issue, but can't understand the mechanism by which FTXUI components render their children. Why does the render function (in `component.cpp`) return an `Element` array? Which part of the code deals with the specific rendering of the foreground and '> '?

**Comment by avighnac** [comment]
I tried coming up with a fix that works for the above mentioned issue, but fails two test cases, one of which is this.
```cpp
TEST(MenuTest, AnimationsHorizontal) {
  ...
  selected = 1;
  {
    Screen screen(4, 3);
    Render(screen, menu->Render());
    EXPECT_EQ(
        screen.ToString(),
        "\x1B[7m1\x1B[27m \x1B[1m2\x1B[22m "
        "\r\n\x1B[97m\x1B[49m\xE2\x94\x80\x1B[90m\x1B["
        "49m\xE2\x95\xB6\xE2\x94\x80\xE2\x94\x80\x1B[39m\x1B[49m\r\n    ");
  }
  animation::Params params(2s);
  menu->OnAnimation(params);
  {
    Screen screen(4, 3);
    Render(screen, menu->Render());
    EXPECT_EQ(
        screen.ToString(),
        "\x1B[7m1\x1B[27m \x1B[1m2\x1B[22m "
        "\r\n\x1B[90m\x1B[49m\xE2\x94\x80\xE2\x95\xB4\x1B[97m\x1B["
        "49m\xE2\x94\x80\x1B[90m\x1B[49m\xE2\x95\xB6\x1B[39m\x1B[49m\r\n    ");
  }
}
```
Which is understandable, but what I did was change this:
```cpp
      const bool is_focused = (focused_entry() == i) && is_menu_focused;
      const bool is_selected = (*selected_ == i);
```

to this:
```cpp
      const bool is_focused = (selected_focus_ == i) && is_menu_focused;
      const bool is_selected = (*selected_ == i);
```

What's the difference between `focused_entry()` and `selected_focus_`?
