### ISSUE TITLE
Add alert widget

### ISSUE THREAD

**Issue by VedantParanjape** [ArthurSonzogni/FTXUI#43]
Hey Arthur,
It would be great if there would be a alert widget, on the lines of `flash()` in JS. It pops up in the center of screen and alerts user and disappears on pressing a key.
If this hasn't been implemented yet and if you approve, I would like to contribute this !

Regards,
Vedant Paranjape

**Comment by ArthurSonzogni** [comment]
Thanks you!

I initially hoped we could get this using the "dbox" Element.
This is a container (like hbox, vbox) that superpose the elements.

It turns out I also needed some few more features:
- Adding the TakeFocus() function to component.
- Adding the clear_under Element

I just added an example: ./examples/component/modal_dialog.cpp
This is on the dev branch.

This give me:
[![asciicast](https://asciinema.org/a/mYewKe3Lz4xdE2sqrpjbeXcDE.svg)](https://asciinema.org/a/mYewKe3Lz4xdE2sqrpjbeXcDE)

**Comment by ArthurSonzogni** [comment]
This is mostly included in this pull request:
https://github.com/ArthurSonzogni/FTXUI/pull/44

**Comment by VedantParanjape** [comment]
Ohhh, Great man !!

I thought I would be able to contribute this 😄

**Comment by ArthurSonzogni** [comment]
Yes, sorry.
I had a predefined idea about how this should be implemented and wanted to complete it. Thanks for filling this issue, this forced me to complete it.

**Comment by lanza** [comment]
Have you thought about baking this modal functionality into the `ComponentBase` such that you'd always have the functionality to call `showModal(ModalComponent component)` where we have something like `using ModalComponent = std::shared_ptr<ModalComonentBase>`? And then dismiss could be just on the `ModalComponent` and it held a reference to its host `ComponentBase` which would toggle the `depth` variable for us.

**Comment by ArthurSonzogni** [comment]
What about creating an API like this;
```cpp
auto main_component  = ...;
auto modal = ...;

bool show_modal = false;
auto main_component_and_modal = Modal(main_component, modal, &show_modal);
```

Alternatively we are now supporting "nested" InteractiveScreen. So you can already use right now:
```cpp
void ShowModal() {
  auto modal_screen = ...;
  auto modal_component = ...;
  modal_screen.Loop(modal_component);
}

void main() {
  auto main_screen = ...;
  auto main_component = ... (show_modal);
  main_screen.Loop(main_component);
}
```

**Comment by ArthurSonzogni** [comment]
I added `Modal` in the PR. What do you think of it?

**Comment by lanza** [comment]
Yup, looks good to me! Thanks!
