### ISSUE TITLE
Thread-safety issues in an example

### ISSUE THREAD

**Issue by dedlocc** [ArthurSonzogni/FTXUI#430]
I suspect the "homescreen" example to be non-thread-safe. `refresh_ui_continue` is being written to by one thread and (potentially) simultaneously read from another, while not being atomic.

https://github.com/ArthurSonzogni/FTXUI/blob/0abaab626859efbe5e45b63cd6d2db5312396cbf/examples/component/homescreen.cpp#L502-L513

**Comment by ArthurSonzogni** [comment]
That's true. There are no consequence here, but still. It would be nice showing some considerations and post a task to be executed in the UI thread. I will make an update.
