### ISSUE TITLE
Inconsistent documentation for the basic tutorial.

### ISSUE THREAD

**Issue by Hunter-Zolomon** [ArthurSonzogni/FTXUI#434]
The mainpage.md file that contains the build instructions and simple tutorial examples has numerous bugs. Additionally, there are missing descriptions, references to actual documentation, and markdown syntax errors.

**Comment by ArthurSonzogni** [comment]
Thanks!

Now, the documentation and examples are rebuilt after every new commits, instead of new version. Happy to merge additional PR if anybody feels this could help others.
