### ISSUE TITLE
Frame is not scrollable for texts

### ISSUE THREAD

**Issue by fridenmf** [ArthurSonzogni/FTXUI#443]
Using the following code snippet you can draw a scrollable frame of buttons:

```cpp
auto components = ftxui::Container::Vertical({});
for (auto i = 0, s = 10; i < s; ++i)
{
    auto component = ftxui::Button(std::string("button ") + std::to_string(i), []() {});
    components->Add(component);
}

auto renderer = ftxui::Renderer(components, [&]
{
    return components->Render()
        | ftxui::vscroll_indicator
        | ftxui::frame
        | ftxui::borderLight
        | ftxui::size(ftxui::WIDTH, ftxui::LESS_THAN, 24)
        | ftxui::size(ftxui::HEIGHT, ftxui::LESS_THAN, 6);
});

auto screen = ftxui::ScreenInteractive::FixedSize(80, 25);

screen.Loop(renderer);
```

Looking like this when started:
```
┌────────────────────────┐
│┌──────────────────────┃│
││button 0              ╹│
│└────────────────────── │
│┌────────────────────── │
││button 1               │
│└────────────────────── │
└────────────────────────┘
```

And like this when scrolled to the bottom:
```
┌────────────────────────┐
│┌────────────────────── │
││button 8               │
│└────────────────────── │
│┌────────────────────── │
││button 9              ╻│
│└──────────────────────┃│
└────────────────────────┘
```

But when replacing the component creation from buttons to texts:
```cpp
auto component = ftxui::Renderer([=]() { return ftxui::text(std::string("text ") + std::to_string(i)) | ftxui::border; });
```

It starts correctly like this:
```
┌────────────────────────┐
│╭──────────────────────┃│
││text 0                ╹│
│╰────────────────────── │
│╭────────────────────── │
││text 1                 │
│╰────────────────────── │
└────────────────────────┘
```

But it's not scrollable. Is this a bug or is there any known workarounds?

And as a side note, is there a more convenient way to add elements to components like the vertical container other than creating a Renderer just returning the element? This is a very minimal reproducing code snippet but our full code base is full of "Renderer wrappers" just to fit things into interactable containers.

Thanks in advance

**Comment by ArthurSonzogni** [comment]
It is because after transforming the UI into `Element`, we don't know which part we don't know which part of the frame to put the focus on. One of them need to use the `focus` decorator.

So, you can use this:
```cpp
auto component = ftxui::Renderer([=](bool focused) {
  auto element =
      ftxui::text(std::string("text ") + std::to_string(i)) | ftxui::border;

  if (focused)
    element |= focus;
  return element;
});
```

This is what `Button` is using:
https://github.com/ArthurSonzogni/FTXUI/blob/d9241435ce9fa3d81f0ea5a0d34c3048883629ee/src/ftxui/component/button.cpp#L82

**Comment by fridenmf** [comment]
Aah, I get it. Thanks for the quick response, the focused lambda overload works great!
