### ISSUE TITLE
Can't figure out how to build using CMake, while following tutorial

### ISSUE THREAD

**Issue by WhereAmO** [ArthurSonzogni/FTXUI#444]
I'm desperately attempting to learn how to use this since I find it so very neat, but I've been stumped on how to build it due to the tutorial not being as specific as I'd desire.

I'm getting the error listed down below, no matter if I try and run this from within a downloaded copy of FTXUI, the Starter Project, or just an empty folder. I'm not sure what I'm doing wrong. I also previously had an issue where it could not find a "main.cpp", but I threw the example one in the [tutorial](https://arthursonzogni.github.io/FTXUI/) into the the scr folder, which was not a step listed anywhere, and it started working..ish, now I have this issue, where it seemingly can't find a makefile. Would very much appreciate some help! Or a better guide to follow..

> D:\Hobbies\UI Attempt\FTXUI\build>cmake ..
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19043.
-- The CXX compiler identification is MSVC 19.16.27045.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Various Programs/MicrosoftVisualStudio/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
-- Found Threads: TRUE
-- clang-tidy not found.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
Doxygen need to be installed to generate the doxygen documentation
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19043.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Hobbies/UI Attempt/FTXUI/build
D:\Hobbies\UI Attempt\FTXUI\build>make -j
make: *** No targets specified and no makefile found.  Stop.

**Comment by ArthurSonzogni** [comment]
Hello,
I believe your are using cmake wrongly ;-)

CMake generate native makefiles and workspaces that can be used in the compiler environment of your choice. I believe in your case, it generated workspace for Visual Studio 15 2017. It has not generated any Makefile.

I made the tutorial for Linux users, who are using cmake and make. Developement on Windows is difficult compare to Linux.

In your case, I believe Microsoft visual studio should be "smart" enough to configure the project by opening the CMakeLists.txt.
You can follow the tutorial here:
https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170

Could you please let me know if you resolved your issue?

**Comment by ValerianCoelho** [comment]
Hi Arthur,
I am trying to use the FTXUI library and I am having a lot of issues. This is my First time using an opensource project from git, and also my first time with cmake files.

I tried generating the and building using the CmakeLists file by following some tutorials from youtube. Now I have a BUILD folder and some files and folders in that, but I am Getting some errors while trying to run the example files that your had provided.

I am using 
Operating System : Windows
IDE : Visual Studio 2019 community (was also wondering if it is possible to use this library in vs code)

I think I am probably doing something wrong, but I cant figure out what it is. If you have the time, I would really appreciate if you made a video or step by step guide explaining how to use the library.

**Comment by ArthurSonzogni** [comment]
Hello @ValerianCoelho,
Just open a new project in visual studio by selecting the CMakeLists.txt file. It should be able to understand how to build it.

**Comment by ValerianCoelho** [comment]
Thanks Arthur, It worked.

**Comment by ArthurSonzogni** [comment]
Nice!
You are welcome!
