### ISSUE TITLE
Support for RGB Colors

### ISSUE THREAD

**Issue by KerDelos** [ArthurSonzogni/FTXUI#45]
Hi !

From what I understand there's only 16 colors available in FTXUI for now. Some terminals are able to display a lot more than 16 colors though and it would be great if FTXUI could also support.

I imagine you already now much more than I do about terminal color handling but I'm putting those two link as a reference purpose.
http://jafrog.com/2013/11/23/colors-in-terminal.html
https://tforgione.fr/posts/ansi-escape-codes/
Since I didn't knew how to handle color on a terminal before reading them I figure they can also be useful to somebody else looking at this issue.

**Suggested implementation :**
Transforming the Color enum into a class.
Creating an enum for the color mode. So the Color instance can know if it is a basic color, a 256 color or an RGB color and print the corresponding escape code. (Only supporting RGB colors would be more elegant but I'm not certain it would work the same on every terminal)
Then, depending on how much you want the library to support older code, I can think of two ways to ensure the least amount of external code would have to be rewritten. Either having constructors for the 16 colors already available or having a static instance for each of these colors in the class.

I'd love to work on a pull request for this feature if you're okay with that !

Have a nice day !
Damien.

ps : I've began using FTXUI for a personal project and I like it a lot ! Thank you for creating it :)

**Comment by ArthurSonzogni** [comment]
Thanks for this suggestion!

I would be happy to receive pull request for this feature.
Before starting, do we have a way to check if the current terminal support 16colors/256colors/16Mcolors?
I would suggest reading: https://gist.github.com/XVilka/8346728.
Maybe proceeding like this:
- Checking the env variable $COLORTERM (truecolor => 256
- [fallback] Checking the environment variable $TERM if it contains "256.
- [fallback] Use 16colors.

Alternatively, maybe we can try to read the terminfo?
https://invisible-island.net/ncurses/man/terminfo.5.html

Ideally:
- [ ] On terminal not configured for 256colors, it should fallback gracefully by selecting the closest 16colors.
- [ ] The new API should preserve compatibility with the current FTXUI version.
- [ ] Be cross-platform?

**Comment by KerDelos** [comment]
Cool I'll start working on it then ! Not sure how long it will take me though. It will depend on how much free time I have in the upcoming days/weeks.

Thanks for the links ! I'll take a look and test how we can check color support on terminals.

About the last three points : 
* `On terminal not configured for 256colors, it should fallback gracefully by selecting the closest 16colors.` Since one can override the 16 basic colors of the terminal we'll need to check whether we can get the correct rgb color code from the terminal. Also, the part in the link you sent (https://gist.github.com/XVilka/8346728#terminals-that-parse-ansi-color-sequences-but-approximate-them-to-256-palette) about color approximation and how the correct formula could be performance intensive worries me a little.
* `The new API should preserve compatibility with the current FTXUI version.` I'm not sure how it could be 100% compatible without becoming a little less clear. If we consider the case where someone was casting an int into a Color enum I'm not sure the API could be compatible without keeping the old color enum around and overriding the operator=. That's not necessarily a problem but having a Color enum and an RGBColor(or some other name) class could be confusing.
* `Be cross-platform` I only have a linux at home but I was planning to test it on various terminals. Do you have a list of terminals you regularly test on ?

**Comment by ArthurSonzogni** [comment]
> Also, the part in the link you sent (https://gist.github.com/XVilka/8346728#terminals-that-parse-ansi-color-sequences-but-approximate-them-to-256-palette) about color approximation and how the correct formula could be performance intensive worries me a little.

Let's see first how it goes without optimization, if there are performance issues, we can still install a tiny cache to this function.

> * `The new API should preserve compatibility with the current FTXUI version.` I'm not sure how it could be 100% compatible without becoming a little less clear. If we consider the case where someone was casting an int into a Color enum I'm not sure the API could be compatible without keeping the old color enum around and overriding the operator=. That's not necessarily a problem but having a Color enum and an RGBColor(or some other name) class could be confusing.

An int shouldn't have been casted into the enum class. If someone did this, they will be broken by their fault. This won't be an issue for us.

I think the enum class can be transformed into a class with an enum.
```
class Color {
  // The 16 standard colors
  enum Enumerated {
     
  }

  Color(Enumated) // Implicit constructor to transform Color::Enumated into Color.
  static Color RGB(int r, int g, int b)
}
```

This way, people will still be able to use Color::Red, but also Color::RGB(255,0,0)

> * `Be cross-platform` I only have a linux at home but I was planning to test it on various terminals. Do you have a list of terminals you regularly test on ?

Let's say Windows will fallback on 16 colors initially.
