### ISSUE TITLE
The focus moves when an item is selected

### ISSUE THREAD

**Issue by ArthurSonzogni** [ArthurSonzogni/FTXUI#453]
### Discussed in https://github.com/ArthurSonzogni/FTXUI/discussions/452

<div type='discussions-op-text'>

<sup>Originally posted by **Alexandring** August  8, 2022</sup>
Hello. I am faced with the following problem.
Select an item in the menu with the mouse and the selected item moves to the middle of the window. The same thing happens when I use containers. How do I disable this feature? I want the selected element to remain in its place and scrolling does not happen.</div>

**Comment by ArthurSonzogni** [comment]
Hello @Alexandring,

That's because we put the focus on the selected element:
https://github.com/ArthurSonzogni/FTXUI/blob/master/src/ftxui/component/menu.cpp#L115-L120

That's what you usually want to do when doing a keyboard navigation. This is conflicting with mouse navigation, where you usually don't want to scroll the view when clicking on an element.

Not sure what do do. Maybe we can maintain a "keyboard" and "mouse" index and put the focus only on the keyboard one. That's probably a good task to work on.

**Comment by Alexandring** [comment]
Can I somehow change the behavior of the menu so that it works throughout the application as I want?

**Comment by ArthurSonzogni** [comment]
> @ArthurSonzogni
Can I somehow change the behavior of the menu so that it works throughout the application as I want?

This would require modifying the FTXUI library.
You can try doing the change I explained above, or wait for me to do it.

Alternatively, you can create your own Menu class, behaving the way you would like.
