### ISSUE TITLE
Multi threading safety for updating entries

### ISSUE THREAD

**Issue by stefandxm** [ArthurSonzogni/FTXUI#478]
Sorry if there is already a solution for this, could not find it!

I am trying to update entries used by the Render functions implicitly - such as menu entries, from a worker thread.
I can find no way to lock/make a hook to where i should do this, and making sure the render loop wont run to crash and burn.

I suggest to introduce a mutex somehow into the render loop. The render loop should use a shared lock, and the updater should use a unique lock for this. To minimize over head this mutex or lock could be supplied as a function or via some kind of pointer logic. Meaning if the mutex is null, no locking will be used by the loop. 

Or we have an update data callback/function that we can trigger by posting an event.

**Comment by ArthurSonzogni** [comment]
> Sorry if there is already a solution for this, could not find it!

Did you consider posting a task to the UI thread?
```cpp
screen.Post([] {
  entries.push_back("test");
})
```

**Comment by stefandxm** [comment]
LOL! I really could not find that. I will test it out immediately! :)

**Comment by ArthurSonzogni** [comment]
It was added recently, so that's probably why ;-)

**Comment by stefandxm** [comment]
This should do the trick. I assume its not blocking and queued now, right? I will have to refactor some of my code but that's not a problem :)

**Comment by ArthurSonzogni** [comment]
Yes, it is queued

**Comment by stefandxm** [comment]
Great, then I know what to do. Feel free to close this "issue"! :)
