### ISSUE TITLE
[Windows] F1-F4 events can't be used

### ISSUE THREAD

**Issue by jdfa** [ArthurSonzogni/FTXUI#492]
Looks like on Windows F1-F4 keys generates slightly different codes:

```
(27 79 80) F1
(27 79 81) F2
(27 79 82) F3
(27 79 83) F4
```

While predefined values are:
  ```
(27 91 79 80) F1
(27 91 79 81) F2
(27 91 79 82) F3
(27 91 79 83) F4
```

For F5-F12 it is the same, except that F11 produces ( 27 91 50 51 126 ).

**Comment by ArthurSonzogni** [comment]
What terminal are you using on windows?

**Comment by jdfa** [comment]
Same result in cmd, powershell and in WindowsTerminal hosting cmd and powershell.

**Comment by ArthurSonzogni** [comment]
Fixed ;-)
