### ISSUE TITLE
WideChar on GNOME Terminal

### ISSUE THREAD

**Issue by SanJ2312** [ArthurSonzogni/FTXUI#5]
I faced a issue with text output where all text was being displayed in chinese. I could fix the problem locally by changing wstring converter to  <std::codecvt_utf8<wchar_t>> in string.cpp . May i know if this is the correct way ? Thanks.

**Comment by ArthurSonzogni** [comment]
HI,
Thanks for reporting this issue !
Could you please show how to reproduce your problem? What do you get?

I expect the gnome terminal to send UT8 encoded characters. Then inside ftxui, everything is utf16. That's why there are conversion when entering and leaving ftxui.

**Comment by SanJ2312** [comment]
`#include <iomanip>
#include <iostream>
#include <codecvt>
#include <locale>
using namespace std;

wstring to_wstring1(const string& s)
{
  wstring_convert<codecvt_utf8_utf16<wchar_t>> converter;
  return converter.from_bytes (s);
}

wstring to_wstring2(const string& s)
{
  wstring_convert<codecvt_utf8<wchar_t>> converter;
  return converter.from_bytes (s);
}

int main()
{
  string myString = "String";
  wstring wideconversion1 = to_wstring1 (myString);
  wstring wideconversion2 = to_wstring2 (myString);
  wcout << wideconversion1 << " " << wideconversion2 << std::endl;
  return 0;
}

`
This code will help in reproducing the issue on GNOME Terminal.

**Comment by ArthurSonzogni** [comment]
Sorry I would like to help, but I don't understand. Could you please describe your issue?

**Comment by SanJ2312** [comment]
The problem is with using older version of gcc . I was using gcc 6.3. Which might not have implemented the codecvt correctly. 

Thanks
