### ISSUE TITLE
Components as Elements ?

### ISSUE THREAD

**Issue by Darleanow** [ArthurSonzogni/FTXUI#503]
Hello,
I wanted to know if there was any way to cast Comonents as Elements, for example for submenus, you can make a menu with a submenu, but i'm trying to make submenus under submenus, or is there any way to do it ?

Thanks, Darleanow

**Comment by ArthurSonzogni** [comment]
Hello and welcome!

> cast Comonents as Elements

To produce an `Element` from a `Component`, this is the Render function.
```cpp
component->Render()
```

> you can make a menu with a submenu

What about using a first `Menu`, whose index is used to select the right submenu from a  `Container::Tab()` containing all the submenu?
I think you can try the example:
https://github.com/ArthurSonzogni/FTXUI/blob/master/examples/component/tab_vertical.cpp

and replace all the `Radiobox` with the sub `Menu`.

**Comment by Darleanow** [comment]
Hello sir,
Thanks for replying this fast,

I actually did something like this, my code isn’t on a github repo but it’ll be soon ! 

And yeah basically I have a vertical tab, with another menu ! And I can get the parameters from it, so i just made a if else and will be generating the elements from it

Regards, Hugonnier Enzo

**Comment by ArthurSonzogni** [comment]
I think we can close this issue, isn't it?

**Comment by Darleanow** [comment]
Indeed,
Thanks
