### ISSUE TITLE
Backspace is not working in Input example when using ssh

### ISSUE THREAD

**Issue by Saigut** [ArthurSonzogni/FTXUI#508]
Client os: Windows 10
SSH client: xshell, Motaxterm

Remote os: ubuntu 18.04, ubuntu 20.04
Remote terminal: bash, fish-shell, zsh

Example: [Input](https://github.com/ArthurSonzogni/FTXUI/blob/master/examples/component/input.cpp)

When I run this Input example via ssh, the Backspace key is not working.

**Comment by ArthurSonzogni** [comment]
Hello,
Thanks for reporting this!
This is a rather unusual setup for me you are using.

Could you try running the example: `examples/components/ftxui_example_print_key_press` ?
https://github.com/ArthurSonzogni/FTXUI/blob/master/examples/component/print_key_press.cpp

Could you please check what is the key associated sent by the terminal when typing backspace, and compare it with the webassembly version?
https://arthursonzogni.github.io/FTXUI/examples/?file=component/print_key_press

**Comment by Saigut** [comment]
Hello, I just tested that. I ran `print_key_press` example and press `BackSpace` key, then:
SSH terminal output:
```
( 8 ) -> (special) 
```
WebAssembly output:
```
( 127 ) -> Event::Backspace
```

**Comment by Saigut** [comment]
And in addition, when I run ssh terminal, the mouse events all have no reaction, including moving cursor, left/right click, scrolling mouse wheel, etc.

**Comment by ArthurSonzogni** [comment]
Hello,
I believe I might have fixed the issue. Does it work?

**Comment by Saigut** [comment]
> Hello, I believe I might have fixed the issue. Does it work?

It works! :thumbsup:

By the way, do you have any idea on why mouse events do not work on ssh terminal?
