### ISSUE TITLE
Compiler warning triggered with -O3 flag

### ISSUE THREAD

**Issue by WinstonPrivacy** [ArthurSonzogni/FTXUI#509]
Hello,

FTXui has been working quite well so far. However, I just turned on -O3 and am receiving the following compilation error on Linux. Note that FTXui turns on -WError.

`    inlined from ‘void ftxui::ScreenInteractive::SigStop()’ at /ftxui/src/ftxui/component/screen_interactive.cpp:661:7:
/usr/local/include/c++/12.2.0/bits/cow_string.h:315:14: warning: ‘((std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider*)((char*)&<unnamed> + offsetof(std::Task, std::variant<ftxui::Event, std::function<void()>, ftxui::AnimationTask>::<unnamed>.std::__detail::__variant::_Variant_base<ftxui::Event, std::function<void()>, ftxui::AnimationTask>::<unnamed>.std::__detail::__variant::_Move_assign_base<false, ftxui::Event, std::function<void()>, ftxui::AnimationTask>::<unnamed>.std::__detail::__variant::_Copy_assign_base<false, ftxui::Event, std::function<void()>, ftxui::AnimationTask>::<unnamed>.std::__detail::__variant::_Move_ctor_base<false, ftxui::Event, std::function<void()>, ftxui::AnimationTask>::<unnamed>.std::__detail::__variant::_Copy_ctor_base<false, ftxui::Event, std::function<void()>, ftxui::AnimationTask>::<unnamed>.std::__detail::__variant::_Variant_storage<false, ftxui::Event, std::function<void()>, ftxui::AnimationTask>::_M_u)))[4].std::basic_string<char>::_Alloc_hider::_M_p’ may be used uninitialized [-Wmaybe-uninitialized]
  315 |       struct _Alloc_hider : _Alloc
      |              ^~~~~~~~~~~~
.../ftxui/src/ftxui/component/screen_interactive.cpp: In member function ‘void ftxui::ScreenInteractive::SigStop()’:
.../ftxui/src/ftxui/component/screen_interactive.cpp:661:7: note: ‘anonymous’ declared here

  661 |   Post([&] {
  662 |     Uninstall();
  663 |     std::cout << reset_cursor_position;
  664 |     reset_cursor_position = "";
  665 |     std::cout << ResetPosition(/*clear=*/true);
  666 |     dimx_ = 0;
  667 |     dimy_ = 0;
  668 |     Flush();
  669 |     std::raise(SIGTSTP);
  670 |     Install();
  671 |   });
cc1plus: all warnings being treated as errors
`

I also note that CLion/GCC is showing an error on the lambda capture function as well ("Attempt to use a deleted function"):

[https://imgur.com/sgrRMMH.png](https://imgur.com/sgrRMMH.png)

**Comment by WinstonPrivacy** [comment]
Turning off -Werror doesn't help, unless -O1 is set in which case the code compiles without error.

**Comment by ArthurSonzogni** [comment]
Hello!
Thanks for using FTXUI.

This function catch SIGTSTP, uninstall FTXUI, execute the standard SIGTSTP handler pausing the application, then reinstall FTXUI.

Do you know what is causing the error you are seeing?
For me to investigate, I would need to find a way to reproduce. What are you using to use FTXUI. Are you using CMake?

**Comment by WinstonPrivacy** [comment]
I ended up rebuilding my environment so it appears that this bug was triggered by a legacy compiler. Using GCC 11.2 , the -O3 flag is working with ftxui now.
