### ISSUE TITLE
Unable to build with the latest versions of Emscripten due to codecvt deprecation.

### ISSUE THREAD

**Issue by ObjectOops** [ArthurSonzogni/FTXUI#514]
The latest versions of Emcsripten, 3.1.25 and higher, appear to use an updated version of LLVM which deprecates the `codecvt` header. Warnings are being treated as errors, so the build process is stopped while compiling the library.
![image](https://user-images.githubusercontent.com/92550885/203855540-51c02d0b-7ff1-4de2-87fa-df2fc6e50992.png)
Related: #498
Versions below 3.1.25 work fine.

**Comment by ArthurSonzogni** [comment]
Thanks!
It looks like we are going to implement it ourselve :-(
