### ISSUE TITLE
Mouse click not working over PuTTY

### ISSUE THREAD

**Issue by CHN-beta** [ArthurSonzogni/FTXUI#523]
To reproduce:

1. Write a simple program, for example:
```
# include <ftxui/component/component.hpp>
# include <ftxui/component/screen_interactive.hpp>

int main()
{
	auto screen = ftxui::ScreenInteractive::Fullscreen();
	auto button = ftxui::Button("Click me!", [&](){screen.ExitLoopClosure()();});
	screen.Loop(button);
}
```
2. Setup an SSH server at local machine. `ssh localhost` and run the program, click the button using mouse, the button works.
3. Install PuTTY on localhost or on an windows machine, ssh to the machine that has the simple program. Run it, and found the button not response to mouse click.
4. However, some other programs response to mouse correctly, such as `htop`.

I have searched the internet and found nothing useful. [Someone](https://superuser.com/a/517166/1021863) suggested to disable "xterm-style mouse reporting", but it makes situation worse. Actually, after disabling "xterm-style mouse reporting", even `htop` could not response to mouse click.

Could you please give me some hints to solve this problem?

**Comment by CHN-beta** [comment]
I have found a workaround from [here](https://github.com/tinmarino/mouse_xterm/blob/b9a7470132300bc3fc50f3f3e8bc233667f074c9/README.md?plain=1#L38) and [here](https://stackoverflow.com/a/69253856/10766846), by print some "magic string" before and after screen loop:

```
# include <ftxui/component/component.hpp>
# include <ftxui/component/screen_interactive.hpp>
# include <iostream>

int main()
{
	auto screen = ftxui::ScreenInteractive::Fullscreen();
	auto button = ftxui::Button("Click me!", [&](){screen.ExitLoopClosure()();});

	std::cout << "\x1b[?1000;1006;1015h" << std::endl;
	screen.Loop(button);
	std::cout << "\x1b[?1000;1006;1015l" << std::endl;
}
```

**Comment by ArthurSonzogni** [comment]
Thanks!

FTXUI is using:
https://github.com/ArthurSonzogni/FTXUI/blob/master/src/ftxui/component/screen_interactive.cpp#L571-L576

which correspond to: `\x1b[?1000,1005,1006h`

See:
```cpp
enum class DECMode {
  kLineWrap = 7,
  kMouseX10 = 9,
  kCursor = 25,
  kMouseVt200 = 1000,
  kMouseAnyEvent = 1003,
  kMouseUtf8 = 1005,
  kMouseSgrExtMode = 1006,
  kMouseUrxvtMode = 1015,
  kMouseSgrPixelsMode = 1016,
  kAlternateScreen = 1049,
};
```

So, 1015 correspond to `kMouseUrxvtMode`.  I guess I can start using it?

**Comment by CHN-beta** [comment]
Sorry, I am not familiar with these stuff, I could not decide is there any side effect to switch to `kMouseUrxvtMode`.

I have noticed that, although mouse click works over putty by print `\x1b[?1000;1006;1015h` before screen loop, mouse move (hover on the component but not click) still not work. I am worrying that switch to `kMouseUrxvtMode` might cause the tui not response to mouse move even directly call from localhost (not over putty).

It might be better to add a switch (for example, `Loop(ftxui::Component layout, bool CompatibleWithXtermStyle)`), before we confirm that there is no drawback to switch to `kMouseUrxvtMode`.

**Comment by ArthurSonzogni** [comment]
I merged a fix. Could you please let me know if this fixed the problem?

**Comment by mordante** [comment]
The patch improved the mouse handling in the urxvt terminal. The mouse press gets registered, but the mouse release doesn't. In the function `TerminalInputParser::ParseCSI` both the press and release will use the 'M' case in the switch. The following patch fixes the release mouse in urxvt

```
--- a/src/ftxui/component/terminal_input_parser.cpp
+++ b/src/ftxui/component/terminal_input_parser.cpp
@@ -318,11 +318,11 @@ TerminalInputParser::Output TerminalInputParser::ParseMouse(  // NOLINT
   }
 
   (void)altered;
+  (void)pressed;
 
   Output output(MOUSE);
-  output.mouse.button = Mouse::Button((arguments[0] & 3) +          // NOLINT
-                                      ((arguments[0] & 64) >> 4));  // NOLINT
-  output.mouse.motion = Mouse::Motion(pressed);                     // NOLINT
+  output.mouse.button = Mouse::Button(((arguments[0] & 64) >> 4));  // NOLINT
+  output.mouse.motion = Mouse::Motion((arguments[0] & 3) == 0);     // NOLINT
   output.mouse.shift = bool(arguments[0] & 4);                      // NOLINT
   output.mouse.meta = bool(arguments[0] & 8);                       // NOLINT
   output.mouse.x = arguments[1];                                    // NOLINT
```
Clearly this is not a proper generic solution. Do you know how to detect whether or not the terminal is urxvt-like so the proper evaluation can be used?
