### ISSUE TITLE
[Question] Sliders for `std::uint16_t`

### ISSUE THREAD

**Issue by TorstenRobitzki** [ArthurSonzogni/FTXUI#524]
Hi,
I have a couple of std::uint16_t values, that I want to display and set with sliders. From what I've got, there is only support for `int`, `float` and `long`. Is there a way to directly display 16 bit values (currently, I would have to copy a lot of data, or add support for uint16 to slider.cpp)

Is there a reason, why `SliderBase<>` is a template, but hidden in the cpp-file?

best regards,
Torsten

**Comment by ArthurSonzogni** [comment]
Hi!
Sorry for the delay!

I would like to avoid exposing the implementation of components. Maybe I can just add all the datatype implementations in the .cc instead? I made a patch.

You should be able to use this with the general function:
```cpp
auto slider = Slider({
  .value = &value,
  .min = 0,
  .max = 100,
  .increment= 20,
});
```

Does this looks good to you? WDYT?

**Comment by TorstenRobitzki** [comment]
Thanks a lot. I will look at your commit when I'm back in the office. I couldn't use the general form, because it doesn't provide the label parameter.
