### ISSUE TITLE
Compiling Library With Msys2 MingW Throws Error  

### ISSUE THREAD

**Issue by Dhananjay-JSR** [ArthurSonzogni/FTXUI#526]
`$ cmake --build .`

`[65/213] Building CXX object FTXUI/CMakeFiles/c...c/ftxui/component/terminal_input_parser.cpp.obj
FAILED: FTXUI/CMakeFiles/component.dir/src/ftxui/component/terminal_input_parser.cpp.obj
C:\msys64\usr\bin\c++.exe -DFTXUI_MICROSOFT_TERMINAL_FALLBACK -DUNICODE -D_UNICODE -IC:/msys64/home/Dhananjay/Desktop/buildUI/FTXUI/src -isystem C:/msys64/home/Dhananjay/Desktop/buildUI/FTXUI/include  -MD -MT FTXUI/CMakeFiles/component.dir/src/ftxui/component/terminal_input_parser.cpp.obj -MF FTXUI\CMakeFiles\component.dir\src\ftxui\component\terminal_input_parser.cpp.obj.d -o FTXUI/CMakeFiles/component.dir/src/ftxui/component/terminal_input_parser.cpp.obj -c C:/msys64/home/Dhananjay/Desktop/buildUI/FTXUI/src/ftxui/component/terminal_input_parser.cpp
In file included from /usr/lib/gcc/x86_64-pc-msys/11.3.0/include/c++/string:55,
                 from C:/msys64/home/Dhananjay/Desktop/buildUI/FTXUI/src/ftxui/component/terminal_input_parser.hpp:5,
                 from C:/msys64/home/Dhananjay/Desktop/buildUI/FTXUI/src/ftxui/component/terminal_input_parser.cpp:1:
/usr/lib/gcc/x86_64-pc-msys/11.3.0/include/c++/bits/basic_string.h: In instantiation of ΓÇÿstatic _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = std::basic_string<char>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]ΓÇÖ:
/usr/lib/gcc/x86_64-pc-msys/11.3.0/include/c++/bits/basic_string.h:5201:27:   required from ΓÇÿstatic _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = std::basic_string<char>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]ΓÇÖ
/usr/lib/gcc/x86_64-pc-msys/11.3.0/include/c++/bits/basic_string.h:3736:28:   required from ΓÇÿstd::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&) [with _InputIterator = std::basic_string<char>; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]ΓÇÖ
C:/msys64/home/Dhananjay/Desktop/buildUI/FTXUI/src/ftxui/component/terminal_input_parser.cpp:24:2:   required from here
/usr/lib/gcc/x86_64-pc-msys/11.3.0/include/c++/bits/basic_string.h:5179:76: error: no type named ΓÇÿiterator_categoryΓÇÖ in ΓÇÿstruct std::iterator_traits<std::basic_string<char> >ΓÇÖ
 5179 |           typedef typename iterator_traits<_InIterator>::iterator_category _Tag;
      |                                                                            ^~~~
[78/213] Building CXX object FTXUI/examples/com...xui_example_custom_loop.dir/custom_loop.cpp.obj
ninja: build stopped: subcommand failed.`

---------------------------------------------------------------------------------------------------------------------------------------------
**cmake version 3.24.2**
**g++ (GCC) 11.3.0**

**Comment by Dhananjay-JSR** [comment]
Any comment on the following issue? So I can try with different toolchain if the existing ones aren't supported

**Comment by ArthurSonzogni** [comment]
Thanks for reporting this!
I think I fixed the compiler issue. Please let me know if it isn't fixed.

**Comment by Dhananjay-JSR** [comment]
Thanks a Lot The Issue is Fixed Now , Closing It also great work on library 🎉🎉
