### ISSUE TITLE
What a bad design！

### ISSUE THREAD

**Issue by fox-wangguodong** [ArthurSonzogni/FTXUI#527]
----------------------------
int main(void) {
  auto document = hbox({
      separator(),
      text("left"),
      separatorVSelector(2, 5, Color::White, Color::Blue),
      text("middle"),
      separatorHSelector(2, 5, Color::White, Color::Blue),
      text("right"),
      separator(),
  });
  auto screen = Screen::Create(Dimension::Full(), Dimension::Full());
  Render(screen, document);
  screen.Print();
}
---------------------------
The above code seems pretty comfortable, but the following code looks so bad!
This method `Renderer` is very uncomfortable to use.
---------------------------
  int value = 50;
  auto buttons = Container::Horizontal({
      Button("Decrease", [&] { value--; }),
      Button("Increase", [&] { value++; }),
  });
  auto component = Renderer(buttons, [&] {
    return vbox({
               text("value = " + std::to_string(value)),
               separator(),
               gauge(value * 0.01f),
               separator(),
               buttons->Render(),
           }) |
           border;
  });
  auto screen = ScreenInteractive::FitComponent();
  screen.Loop(component);
-------------------------

**Comment by ArthurSonzogni** [comment]
Hello,
What's your question?

**Comment by ArthurSonzogni** [comment]
I am going to close, given there are no replies. Feel free to reopen if you believe something can be improved.
