### ISSUE TITLE
Testssuite fails to build: it can't find googletest

### ISSUE THREAD

**Issue by yurivict** [ArthurSonzogni/FTXUI#551]
```
===>  Testing for ftxui-3.0.0.69
-- clang-tidy not found.
CMake Error at cmake/ftxui_test.cmake:18 (add_subdirectory):
  add_subdirectory given source
  "/usr/ports/devel/ftxui/work/FTXUI-3.0.0-69-g90dfcee/_deps/googletest-src"
  which is not an existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:149 (include)


CMake Error at cmake/ftxui_benchmark.cmake:13 (add_subdirectory):
  add_subdirectory given source
  "/usr/ports/devel/ftxui/work/FTXUI-3.0.0-69-g90dfcee/_deps/googlebenchmark-src"
  which is not an existing directory.
Call Stack (most recent call first):
  cmake/ftxui_test.cmake:83 (include)
  CMakeLists.txt:149 (include)


-- Configuring incomplete, errors occurred!
```

googletest doesn't get fetched, and it doesn't use the pre-installed googletest either.

Version: 3.0.0-69-g90dfcee
clang-14
FreeBSD 13.1

**Comment by ArthurSonzogni** [comment]
I should probably check for clang tidy and add a better error message to explain what happened.

**Comment by yurivict** [comment]
No, I didn't enable FTXUI_CLANG_TIDY

**Comment by ArthurSonzogni** [comment]
Okay. Then, I will take a look more closely. Thanks for reporting this!

**Comment by arrowd** [comment]
@yurivict This might has something to do with the fact that our `cmake.mk` always passes `-DFETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON` in `CMAKE_ARGS`.

**Comment by yurivict** [comment]
It should be possible to build tests with pre-installed googletest.

**Comment by arrowd** [comment]
Yes, sure, I'm just guessing why @ArthurSonzogni  may not seen this before.

**Comment by yurivict** [comment]
I see.

**Comment by yurivict** [comment]
> gtest from packages does not come with GTestConfig.cmake to find the library.

Yes it does:
```
$ pkg info -l googletest | grep GTestConfig
	/usr/local/lib/cmake/GTest/GTestConfig.cmake
	/usr/local/lib/cmake/GTest/GTestConfigVersion.cmake
```

It can be made optional to use externally installed GTest.

**Comment by ArthurSonzogni** [comment]
Not on my distribution unfortunately:
https://packages.ubuntu.com/jammy/all/googletest/filelist

If you want, I can add optional support, but I won't be able to test locally. I will make a patch and let you confirm it worked.

**Comment by ArthurSonzogni** [comment]
@yurivict / @arrowd
Could you please confirm [this](https://github.com/ArthurSonzogni/FTXUI/pull/552) fixes: https://github.com/ArthurSonzogni/FTXUI/issues/551

(I can't test it locally myself, because the ubuntu package manager do not provide the proper cmake finder)
