### ISSUE TITLE
Node getters and setters should be available

### ISSUE THREAD

**Issue by hun-nemethpeter** [ArthurSonzogni/FTXUI#554]
I just wondering why every node is just handled as Element and not a concrete type such as `shared_ptr<Text>` or something like that?

If we can introduce an extra inheritance to the Node class then we can give back real node types.

`class Node : public std::enable_shared_from_this<Node>`

And later we can give back
```
// --- Widget ---
std::shared_ptr<Text> text(std::string text);

class Text : public Node
{
public:
...
    std::shared_ptr<Text> fontSize(int size);
...
};

...
std::shared_ptr<Text> Text::fontSize(int size)
{
    m_fontSize = size;
    return std::static_pointer_cast<Text>(shared_from_this());
}
```
...
so we can write
`hbox(text("selected = ")->fontSize(12) | center) ...`

With this change every node can have real setters/getters. Ok, fontSize() doesn't make any sense actually, but this is just an example.

**Comment by ArthurSonzogni** [comment]
Hello! :wink: 
This allows updating the implementation, without breaking the API.
This also force shaping the API into a more functional way. That is to say, the parameters must be provided when calling the function, instead of as a side effect later on.
