### ISSUE TITLE
Offset cursor in Input when using FitComponent

### ISSUE THREAD

**Issue by timeopochin** [ArthurSonzogni/FTXUI#559]
**The bug**
The terminal cursor is offset by 1 when typing in an Input component

**Observations**
- This bug only seems to occur when using [FitComponent](https://arthursonzogni.github.io/FTXUI/classftxui_1_1ScreenInteractive.html#a4f458e443ed672c2aea9fdd96531a621).
- Once the text reaches the same length as the max size of the component, the offset disappears.
- As the bug also shows up on the asciinema recording, I assume it means it comes from FTXUI itself.

**The bug in action**

[![asciicast](https://asciinema.org/a/LJJ61ZLu74zTKGydjraMzyivF.svg)](https://asciinema.org/a/LJJ61ZLu74zTKGydjraMzyivF)

**My device**
OS: Arch Linux x86_64
Kernel: 6.1.6-zen1-2-zen
WM: sway
Terminal: foot

**My code**
```cpp
#include "ftxui/component/component.hpp"
#include "ftxui/component/screen_interactive.hpp"

using namespace ftxui;

int main() {
  std::string value;
  auto input = Input(&value, "");
  auto renderer = Renderer(input, [&] {
    return hbox(text("Input: "), input->Render());
  });

  auto screen = ScreenInteractive::FitComponent();
  screen.Loop(renderer);
}
```

_P.S. thanks for a great library!_

**Comment by ArthurSonzogni** [comment]
Hello @timeopochin 
You found a bug. Thanks for the report!
