### ISSUE TITLE
[Feature request] s̵t̵r̵i̵k̵e̵t̵h̵r̵o̵u̵g̵h̵ (strikethrough) element

### ISSUE THREAD

**Issue by timeopochin** [ArthurSonzogni/FTXUI#560]
This is a feature request to add a `strike`/`strikethrough` element to go with `underlined`, `bold`, `dim`, `blink` and `inverted`

This seems like it would really complete the set of styling tools and I can't imagine that it would be that hard to implement (though please correct me if I'm wrong!)

I think it probably doesn't need much explaining but basically
```cpp
vbox({
  strike(text("strikethrough")),
  text("strikethrough") | bold | strike
});
```
would give something like
> ~strikethrough~
> ~**strikethrough**~

I've not looked too much into the library's codebase, but potentially I could try to implement it and submit a pull request. Though I'm not sure how soon I would dedicate time for it.

**Comment by ArthurSonzogni** [comment]
Thanks!
We probably should. It is not clear to me why I decided not to. Maybe this is not widely supported. I will take a look ang get back to you.

**Comment by ArthurSonzogni** [comment]
Done!
Does it works good enough for you?
