### ISSUE TITLE
Coloring borders

### ISSUE THREAD

**Issue by ArthurSonzogni** [ArthurSonzogni/FTXUI#564]
### Discussed in https://github.com/ArthurSonzogni/FTXUI/discussions/563

<div type='discussions-op-text'>

<sup>Originally posted by **mavam** January 22, 2023</sup>
Is there a way to colorize borders? Adding `| border` alone doesn't give the desired control. I'm catching myself now doing things like `separator() | color(...)`, but that workaround only works in rare occasions. Have you ever considered adding color parameter to `border`?

Here's an example screenshot of a data analytics TUI I'm building:

<img width="1614" alt="image" src="https://user-images.githubusercontent.com/53797/213917775-c8b2713c-429b-4b60-912a-2b5cb24ffcc3.png"></div>

**Comment by Oleksii-Kshenskyi** [comment]
Hey @ArthurSonzogni ! Could you let me know what the status on this is? I'm creating a pretty basic text adventure game with FTXUI, but I would like to have colored borders for different situations in the game like low HP, warning the player about stuff, attracting player's attention to some issue etc. Would be great to have this.

**Comment by ArthurSonzogni** [comment]
I will prioritize this during this week.
