### ISSUE TITLE
Feature: ResizableSplit with custom separator

### ISSUE THREAD

**Issue by pllee4** [ArthurSonzogni/FTXUI#580]
I am enjoying using `ResizableSpilt` for layout. Feels like in some cases, it would be good to have custom separator, for example, if I would like to have the separator invisible, I can simply pass element of `separatorEmpty()`.

Thinking perhaps it would be good if we can have one more option for the interface.

**Comment by mavam** [comment]
Another use case: colorize the separator in a lighter grey tone so that it doesn't show up so much.

**Comment by ArthurSonzogni** [comment]
Thanks! This is grealy appreciated!
I like it. I wonder if there are other ways to make it customizable easily.

I think I will take your patch, but modify the interface to allow more.

**Comment by mavam** [comment]
Great to see this merged. Thanks a lot! 🙏
