### ISSUE TITLE
[Feature requests] Nix build system support

### ISSUE THREAD

**Issue by dev-null-undefined** [ArthurSonzogni/FTXUI#598]
Would you be interested into adding nix build support for this project? I would love to use this and I would prefer to add it as nixpkg dependency.

I can try create some flake.nix, but I would love to know if it will get merged or if I will be just wasting my time before hand.

https://github.com/NixOS/nixpkgs
https://github.com/NixOS/nix
https://repology.org/

Thanks for reply.

**Comment by ArthurSonzogni** [comment]
I would be happy to.

What would be the cost of maintaining it? What needs to happen in this repository?

**Comment by dev-null-undefined** [comment]
Well there are 2 options either packaging it directly in here which would mean probably 3-4 files in root directory and once in a while while making release recalculating hashes.
Benefit of this is instant updates.

Or there is the option going directly into nixpkgs which would mean that nothing would change in hear the package would be easier to install for other nix users, but you would be relying on nixpkgs mainteiners to merge updates and patches.


I would prefer both, to get the flexibility and at the same time the easy installation for those who do not need cutting edge version.

**Comment by dev-null-undefined** [comment]
I will try to create PR later today.

**Comment by ArthurSonzogni** [comment]
Sounds good to me! Thanks for looking at it!
