### ISSUE TITLE
Switch master branch to main

### ISSUE THREAD

**Issue by LostInCompilation** [ArthurSonzogni/FTXUI#599]
Since most repos implemented the new guidelines I thought I would also bring this topic to FTXUI for more consistency across repos.

Current guidelines suggest and newly created repos are using `main` as the name for the main branch, instead of `master`. Maybe considering switching from `master` to `main` would be possible.

**Comment by ArthurSonzogni** [comment]
I wouldn't be against, mostly because I got used to using origin/main.

(I will do it)
