### ISSUE TITLE
Question : How can I get a new line after exiting from the txui

### ISSUE THREAD

**Issue by SanJ2312** [ArthurSonzogni/FTXUI#6]
![screenshot](https://user-images.githubusercontent.com/35691360/64610264-7f1f2180-d3ec-11e9-9cba-0b1c59c0f772.png)

**Comment by ArthurSonzogni** [comment]
It looks like a big to me. I will take a look.

**Comment by ArthurSonzogni** [comment]
Thanks for reporting this issue! I think I fixed it.
Could you confirm it works correctly now?

**Comment by SanJ2312** [comment]
yeah It works now.
Thanks
