### ISSUE TITLE
ScreenInteractive::PostMain prints unnecessary(?) newline

### ISSUE THREAD

**Issue by Parranoh** [ArthurSonzogni/FTXUI#609]
When I call `screen.ExitLoopClosure()` on a `ScreenInteractive screen` and the program terminates (like in `examples/component/with_restored_io.cpp`), a newline is printed to stdout.

I would like to avoid this because the program cleans itself up nicely otherwise.

If I delete this line, the newline isn't printed anymore. Nothing else changes as far as I can tell. I have only tested it with alacritty 0.10.1.
https://github.com/ArthurSonzogni/FTXUI/blob/eed7e2ea7046fcef2de15e18a24735d8adc46c4a/src/ftxui/component/screen_interactive.cpp#L465

Is this newline necessary to reset the terminal properly? If not, I suggest removing it.

**Comment by ArthurSonzogni** [comment]
I think it depends on whether the frame drawn was filling the whole screen or not.

If it doesn't, we should add a new line, otherwise the prompt will appear next to the previous frame.

I think I have an idea how to fix it.

**Comment by ArthurSonzogni** [comment]
Please let me know if this fixed your issue. I hope it did.
