### ISSUE TITLE
ColorInfoSorted2D Problem

### ISSUE THREAD

**Issue by Eleshz** [ArthurSonzogni/FTXUI#615]
Long story short, I'm learning c++ and starting my first project. I searched up a TUI for the cmd prompt and found this. In about 2 days I went from not even knowing what a library or Cmake or vcpkg is, to installing FTXUI.

Anyway, I was running the example scripts you have, so I copy-pasted a couple of them in to test, they all work…

Except when any of them mention
 `#include "../dom/color_info_sorted_2d.ipp"  // for ColorInfoSorted2D`

It says it `“cannot open source file "../dom/color_info_sorted_2d.ipp”`
and therefore `“ColorInfoSorted2D”` is undefined...

Sorry if this is some noob stupid question- I don't want to waste anyone's time but if somebody knows how to remedy this then please tell me.

Thanks.

**Comment by Eleshz** [comment]
![image](https://user-images.githubusercontent.com/79333862/230905048-535d20ea-8319-4246-b90d-1c890f2e342b.png)

Even within the example it doesn't seem to point to anything

**Comment by ArthurSonzogni** [comment]
> Long story short, I'm learning c++ and starting my first project. I searched up a TUI for the cmd prompt and found this. In about 2 days I went from not even knowing what a library or Cmake or vcpkg is, to installing FTXUI.

Impressive! Welcome to C++!

---

The file is defined in FTXUI examples:
https://github.com/search?q=repo%3AArthurSonzogni%2FFTXUI+color_info_sorted&type=code

I guess you don't have the same file in the same location?

**Comment by Eleshz** [comment]
I'm sorry, 
![image](https://user-images.githubusercontent.com/79333862/230926771-8fcf8b42-b3fe-4bb5-a73d-c42e7171c481.png)
Your link doesn't show anything?

**Comment by Eleshz** [comment]
I see, so do I take these, or anything like them that throws an error, and add them to where they should be? I thought these were-well examples, so I didn't need them.

**Comment by Eleshz** [comment]
I'm sorry, I'm just new to all this

**Comment by ArthurSonzogni** [comment]
I think you can copy the content of:
https://github.com/ArthurSonzogni/FTXUI/blob/4bdbf6352dfa5aeb61cd0467fd4de6a302790bf7/examples/dom/color_info_sorted_2d.ipp#L4

and remove the include?
