### ISSUE TITLE
SliderOption members named "min" and "max" cause compiler error without NOMINMAX defined on Windows

### ISSUE THREAD

**Issue by njk42** [ArthurSonzogni/FTXUI#618]
On Windows/MSVC, macro NOMINMAX must be #define'd otherwise the min() and max() expressions on line 174 of component_options.hpp (FTXUI 4.0.0) are misinterpreted as calls to the minimum and maximum math function macros in windows.h, rather than calling operator()() of the ConstRef<T> min and ConstRef<T> max member variables.  The resulting compiler error is:

Error C2760 syntax error: ')' was unexpected here; expected 'expression'	<>\out\build\x64-Release\_deps\ftxui-src\include\ftxui\component\component_options.hpp	174

Suggest using min.operator()() and max.operator()() to explicitly call ConstRef<T>::operator().

**Comment by Eleshz** [comment]
I think there's a work-around where you can disable the windows min/max functions

https://forum.kde.org/viewtopic.php?f=74&t=26099

![image](https://user-images.githubusercontent.com/79333862/232260488-aa74baef-57b3-4a4b-9c51-ae10bb8182c2.png)

Ignore that this is from 2009 lol, it still works

![image](https://user-images.githubusercontent.com/79333862/232260516-5bd251f4-6a75-4215-83b9-5a505702ac4c.png)

**Comment by ArthurSonzogni** [comment]
FTXUI doesn't have any headers including `windows.h`. So I guess it shouldn't be FTXUI responsability to manage the problem. Isn't it?

It should be the responsability of the user who are using it.
Is there anything you believe FTXUI should do?

I know FTXUI is already doing some qwirks to fix Windows problems:
- https://github.com/ArthurSonzogni/FTXUI/blob/1397c1023434f63bf1aa5eeea2e6d6943178a745/include/ftxui/dom/canvas.hpp#L12-L16
- https://github.com/ArthurSonzogni/FTXUI/blob/1397c1023434f63bf1aa5eeea2e6d6943178a745/include/ftxui/screen/color.hpp#L8-L12

And does correctly import windows.h in its private sources:

https://github.com/ArthurSonzogni/FTXUI/blob/1397c1023434f63bf1aa5eeea2e6d6943178a745/src/ftxui/screen/screen.cpp#L12-L18

**Comment by njk42** [comment]
@ArthurSonzogni  Sorry, didn't mean to imply it was necessarily FTXUI responsibility to mitigate this or even document it.  But less experienced Windows users unaware of the NOMINIMAX "fix" may encounter the compiler error and assume the library is broken or spend a lot of time tracking it down.  Hopefully this Github Issue helps save time for others who might come across the same problem and need to #define NOMINMAX before including windows.h, or make sure FTXUI headers are #included before windows.h.

**Comment by RaphaelMaschinsen** [comment]
@njk42  Thank you, this Github Issue actually did save me a lot of time :)
