### ISSUE TITLE
CMakeLists.txt issue when git is not installed or master.zip from github is used

### ISSUE THREAD

**Issue by std-any-emplace** [ArthurSonzogni/FTXUI#62]
The supplied CMakeLists.txt fails if either git is not installed or the master.zip from github is used (and therefore the unpacked source does not contain a git repository).
Change the top to:
```
find_package(git QUIET)
if (git_FOUND)
  execute_process(
  COMMAND git rev-list --count HEAD
  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
  OUTPUT_VARIABLE git_version
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
else()
  set(git_version 0)
endif()
```

Setting `git_version` to 0 may not be the best solution, but at least it works.

**Comment by std-any-emplace** [comment]
TBH c&p is probably less a hassle...

**Comment by ArthurSonzogni** [comment]
Yeah, I realized I asked someone reporting a bug happening when git isn't
installed, to submit a fix using git.

I will do it when I will be back in front of a computer tonight.

Le ven. 20 nov. 2020 à 13:01, std-any-emplace <notifications@github.com> a
écrit :

**Comment by ArthurSonzogni** [comment]
Done. Thanks!
