### ISSUE TITLE
Non-focusable CatchEvent in Container doesn't work

### ISSUE THREAD

**Issue by shishitoh** [ArthurSonzogni/FTXUI#623]
When I use CatchEvent that is wrapping other non-focusable Component its event works, bat when it is wrapped by Container like Container::Vertical or Container::Tab its event not works.

```C++
auto comp = Renderer([]{return text("hi!");});
comp |= CatchEvent(foo);
screen.Loop(comp); // foo is called
```

```C++
auto tmp = Renderer([]{return text("hi!");});
tmp |= CatchEvent(foo);
int select = 0;
auto comp = Container::Vertical({tmp}, &select);
screen.Loop(comp); // foo is not called
```

**Comment by ArthurSonzogni** [comment]
Hello,
Thanks for this bug report!

This is working as expected. Indeed `comp` is not focusable, so when wrapped with `CatchEvent`, it is still not focusable.

Indeed this is an inert element that doesn't show something different when focused to show the user where they are. You can use this form with the boolean parameter:
```cpp
auto tmp = Renderer([](bool focused) {
  return focused
    ? text("hi (unfocused)")
    : text("hi (focused)");
})
```

`Container::Vertical` do not forward keyboard event when it is not focused. To be focused, it needs to be focusable. To be focusable, it needs to contain a focusable element.
