### ISSUE TITLE
Node boxes can sometimes fold over themselves / have negative width

### ISSUE THREAD

**Issue by OrfeasZ** [ArthurSonzogni/FTXUI#624]
Sometimes, depending on the layout, it seems like its possible to make node boxes "fold over" themselves when the window size is not big enough. This basically means that their internal `_box.x_max` becomes smaller than their `_box.x_min`.

I'm not sure if this affects any other layout combinations, but in my case I happened to come across this while drawing a graph inside nested windows, and resized the screen until the graph was completely outside of the view, which caused the graph function to start receiving negative numbers for the `width` parameter (and resulted in a crash after being passed to the `std::vector` constructor).

I've created a small repro here: https://github.com/OrfeasZ/ftxui-negative-box-bug

To reproduce the issue, run this and resize the console window from the right to the left until the graph is out of view.

**Comment by ArthurSonzogni** [comment]
Thanks! I think I fixed the issue.

**Comment by OrfeasZ** [comment]
This fixes this issue with the graph but is the fact that x_max can be smaller than x_min still intended?

**Comment by ArthurSonzogni** [comment]
> This fixes this issue with the graph but is the fact that x_max can be smaller than x_min still intended?

Yes, empty interval have `x_max` < `x_min`.
