### ISSUE TITLE
Arrows not working - Event detects reset, not set

### ISSUE THREAD

**Issue by JosefLitos** [ArthurSonzogni/FTXUI#626]
Arrow keys (without other modifiers) are denoted with `O` at the beginning of escape sequence, but the `O` is missing from these lines:
https://github.com/ArthurSonzogni/FTXUI/blob/a60201317916f20da676cbd807169b9e543b2275/src/ftxui/component/event.cpp#L53-L56

(should be `\x1BOA`,`\x1BOB`,`\x1BOC`,`\x1BOD`)

Also (this is a nit pick, so please feel free to ignore) `Esc` keycode is usually written in the form `\033`, which is the same length and thanks to its number-only representation is slightly easier to distinguish from the rest of the escape sequence (like here, compare `\x1BOB` vs `\033OB`), this also avoids errors when for example `A` would begin the escape sequence as it would get compiled as part of the hex code.

**Comment by ArthurSonzogni** [comment]
Hello!
What terminal are you using?

**Comment by ArthurSonzogni** [comment]
I see! I guess your terminal or one of your app is setting it differently.

We can easily fix this. There are several ways.
