### ISSUE TITLE
Terminal-like box

### ISSUE THREAD

**Issue by herhor67** [ArthurSonzogni/FTXUI#629]
Hello,
first of all, this seems to be a great library with ease-of-use in mind :)

I have this code, which is basically few examples cobbled together:
```
	auto document =
		vbox({
			hbox({
				window(text("The window"), text("The element")) | flex,
				window(text("The window"), text("The element")) | flex
			}) | flex,
			hbox({
				window(text("The window"), text("The element")) | flex,
				window(text("The window"), text("The element")) | flex
			}) | flex,
		});

	auto screen = Screen::Create(Dimension::Full());
	Render(screen, document);
	std::string reset_position;

	while (true)
	{
		std::cout << reset_position;
		screen.Print();
		reset_position = screen.ResetPosition();
		std::this_thread::sleep_for(0.1s);
	}
```

My goal in this app is to separate the output from several threads, to make it more readable. What is be the best way to do this? It would be great to have the "innards" scrollable, like a small built-in terminal, but it's not a requirement.
Ideally, I could pass some kind of reference to the thread starter, so then instead of `cout <<` I could just do `some_stream_to_box <<`.
Reading through the headers, seems like I should be looking at `frame`?
Or is it impossible to update an element, and instead I need to recreate the document every time with a say, buffer of last N lines?

Also, is this the correct way to display the screen in one place (without duplicating the text one after another)?

**Comment by ArthurSonzogni** [comment]
Hello!

FTXUI is split into 3 libraries:
1. ftxui-screen: A `ftxui::Screen`. This is a grid of cells. You can "print" it on the terminal.
2. ftxui-dom: A set of DOM element that can "render" themselve to the screen.
3. ftxui-component: A set of component that can "render" DOM element. They have internal state and react to keyboard/mouse events.

For now, you have been using (1) and (2). You can continue doing so, but if you want to react to "mouse" events, you will have to start using (3).

Here is a good [example](https://github.com/ArthurSonzogni/FTXUI/blob/main/examples/component/checkbox_in_frame.cpp)
 [demo](https://arthursonzogni.github.io/FTXUI/examples/?file=component/checkbox_in_frame)

About "innards" scrollable, this is still implemented by (2), via the following element:
```cpp
// --- Frame ---
// A frame is a scrollable area. The internal area is potentially larger than
// the external one. The internal area is scrolled in order to make visible the
// focused element.
Element frame(Element);
Element xframe(Element);
Element yframe(Element);
Element focus(Element);
Element select(Element);
```

The `frame` provides an "inner" area potentially larger than the "outter" one, and it "center" the element decorated with `focus`.

Determining who is the "focused" element is normally implemented by built-in Component of (3). 

Note: If you don't really care about `ftxui::Component` and just want to have a scrollable area, you can import `Scroller` from:
https://github.com/ArthurSonzogni/git-tui/blob/master/src/scroller.hpp

**Comment by herhor67** [comment]
Thank you! So I would use a frame decorated with the scroller?
Any suggestions as to the other part, i.e. changing the text content of a node/element?

**Comment by ArthurSonzogni** [comment]
> Any suggestions as to the other part, i.e. changing the text content of a node/element?

FTXUI is more functional. We don't really "update" the text content of a node/element.

The node/element are single use. You create a new one for every frame. So you just have to plumb a different value. See: https://www.kn8.lt/blog/ui-is-a-function-of-data/

**Comment by herhor67** [comment]
Great, this is quite helpful as an idea. If I won't have any further questions, I will close the issue soon.
Ah, about printing the screen in a loop - I guess the code above is fine for delays like 1s etc, and Loop() is used only for event handling?

**Comment by ArthurSonzogni** [comment]
Yes, `ScreenInteractive::Loop` or `ftxui::Loop` are used for event handling.
