### ISSUE TITLE
Stall on exit due to parentless Component

### ISSUE THREAD

**Issue by nwfistere** [ArthurSonzogni/FTXUI#637]
I'm working on a chat server with a client that utilizes ftxui as the interface. I created several custom components that inherit from `BaseComponent`. I've ran into an issue that on shutdown, the client hangs. I've found it's due to one of my custom components having a TabContainer as a child, but the TabContainer does not have a parent. Causing an infinite loop in `DetachAllChildren()`.

Using gcc 12.2.1 on ubuntu

I made the following changes in component.cpp and this is the output I'm getting.

```diff
@@ -61,23 +61,29 @@ void ComponentBase::Add(Component child) {
 /// @see Parent
 /// @ingroup component
 void ComponentBase::Detach() {
+  std::cout << "Detach(): detaching " << this << "\n";
   if (parent_ == nullptr) {
+    std::cout << "Detach(): parent is nullptr " << this << "\n";
     return;
   }
   auto it = std::find_if(std::begin(parent_->children_),  //
                          std::end(parent_->children_),    //
                          [this](const Component& that) {  //
-                           return this == that.get();
+                            std::cout << "Detach(find_if)(): returning " << this << " == " << that.get() << " " << (this == that.get() ? "true" : "false") << "\n";
+                            return this == that.get();
                          });
   ComponentBase* parent = parent_;
   parent_ = nullptr;
+  std::cout << "Detach(): erasing " << *it << "\n";
   parent->children_.erase(it);  // Might delete |this|.
 }
 
 /// @brief Remove all children.
 /// @ingroup component
 void ComponentBase::DetachAllChildren() {
+  std::cout << "DetachAllChildren(): current object: " << this << "\n";
   while (!children_.empty()) {
+    std::cout << "DetachAllChildren(): detaching " << children_[0].get() << "\n";
     children_[0]->Detach();
   }
 }
```
**Output:**
My custom component is the parent (0x7a82b0) // Note the b vs 6 for the address, they are different.
TabContainer is 0x7a8260 
```bash
DetachAllChildren(): current object: 0x7a82b0
DetachAllChildren(): detaching 0x7a8260
Detach(): detaching 0x7a8260
Detach(): parent is nullptr 0x7a8260
DetachAllChildren(): detaching 0x7a8260
Detach(): detaching 0x7a8260
Detach(): parent is nullptr 0x7a8260
DetachAllChildren(): detaching 0x7a8260
Detach(): detaching 0x7a8260
Detach(): parent is nullptr 0x7a8260
DetachAllChildren(): detaching 0x7a8260
Detach(): detaching 0x7a8260
Detach(): parent is nullptr 0x7a8260
DetachAllChildren(): detaching 0x7a8260
Detach(): detaching 0x7a8260
Detach(): parent is nullptr 0x7a8260
DetachAllChildren(): detaching 0x7a8260
Detach(): detaching 0x7a8260
Detach(): parent is nullptr 0x7a826
... On and on and on ...
```

Couple thoughts: 
1. The Custom component I create that is the issue here does not call Container::Tab. I would expect my custom component to be the child of the TabContainer, as it's a custom modal which I created using examples/component/modal_dialog_custom.cpp as reference.
2. I deleted the Detach() function completely and it solved this issue. Running valgrind showed no memory leaks.
3. A possible fix would be to add a check in the DetachAllChildren() to validate the child has a parent before calling Child.Detach().

I'm working on getting a minimal example to recreate this issue. My current source requires a server to be running for the tui to actually initialize. I figured it wouldn't hurt to post this first in case anyone had any thoughts.

Thanks,

Nick

**Comment by nwfistere** [comment]
I figured it out. The symptom was odd for what was happening. In main, I was accidentally running a copy constructor on the main component that inherits from BaseComponent. Here's an example:

**Wrong way:**
```cpp
template<typename M, typename U, typename E, typename X>
class MainComponent : public ComponentBase {
// Contents including several other components.
}

int main() {
// ...
auto main_component = MainComponent(/*bunch of lambdas*/);
// ...
// This will call the copy construct, because object is being passed.
auto view = ftxui::Make<decltype(main_component)>(std::move(main_component));
// ...
}
```

**Corrected way:**
```cpp
template<typename M, typename U, typename E, typename X>
class MainComponent : public ComponentBase {
// Contents including several other components.
}

int main() {
// ...
// declare lambdas
auto lambda_1 = [] {};
auto lambda_2 = [] {};
auto lambda_3 = [] {};
auto lambda_4 = [] {};

// ...
auto view = ftxui::Make<MainComponent<decltype(lambda_1), decltype(lambda_2), decltype(lambda_3), decltype(lambda_4)>>(lambda_1, lambda_2, lambda_3, lambda_4);
// ...
}
```


The corrected approach allows my program to exit correctly.

I did a couple hours of debugging prior to this, I'm still not sure how the TabContainer became a child to a component that it should be the parent of.

Couple questions or comments:
 - Are Components intended to be copied? If not, setting the copy constructor to private on the ComponentBase might be appropriate.
 - During my debugging I attempted to create my own custom TabContainer. However, I had to add override destructors to both the TabContainer as well as ContainerBase. I also had to pull them into a header file. I could see a use case of allowing inheritance of containers.

Thank you for creating such a wonderful library!

Nick

**Comment by ArthurSonzogni** [comment]
Thanks!

I think we should indeed remove the copy constructors and copy operator= to avoid the next developer to have the same issue. I am reopening this issue for this reason.

I am not sure to understand the second question. Sorry.

**Comment by nwfistere** [comment]
Hi Arthur,

Thanks for taking a look. 

Apologies, let me reword my second statement:

The `TabContainer` and `ContainerBase` classes do not allow inheritance due to not declaring a destructor and being defined within a .cpp file. I think there's merit to making them inheritable and consumable by users of the library by adding them to a header file and including overridden destructors.

Since this all came about from the Detach() methods, I'd like to ask one more question while I'm already commenting.

My understanding of the Detach() methods that they were created to prevent memory leaks from circular dependencies. Is that correct? If that's the case, I recommend using a weak_ptr as the link from a child to the parent. That should allow all components to be deleted correctly without needing to detach them. If you like this idea, I can submit a pull request.

I created #638 for deleting the two methods.

Thanks,

Nick

**Comment by ArthurSonzogni** [comment]
> The TabContainer and ContainerBase classes do not allow inheritance due to not declaring a destructor and being defined within a .cpp file. I think there's merit to making them inheritable and consumable by users of the library by adding them to a header file and including overridden destructors.

FTXUI used to expose the classes of each component directly. I decided very quickly at the beginning to turn everything into functions instead and to hide the implementations. This allowed me to improve the implementations without breaking users of the public API.

My feeling is that you should be able to use use composition instead of inheritance?
Moreover the `ComponentBase` implementation delegates by default to the first children; so you could `Add(container_base)` and override only the methods you need. For instance:
```cpp
class MyComponent : ftxui::ComponentBase {
  private:
    Component inner_1 = ???;
    Component inner_2 = ???;
    Component container_ = Container::Vertical({
      inner_1,
      inner_2,
    });
  public:
    MyComponent() {
      Add(container_);
    }

    Element Render() final {
      return ComponentBase::Render() | bold;
    }
}
```

Pleas let me know if composition is not something working for you.

----

> My understanding of the Detach() methods is that they were created to prevent memory leaks from circular dependencies. Is that correct? If that's the case, I recommend using a weak_ptr as the link from a child to the parent. That should allow all components to be deleted correctly without needing to detach them. If you like this idea, I can submit a pull request.

The parent "owns" the children. The children reference the parent. We don't really need a weak_ptr. The private implementation should be sufficient to ensure this to work correctly. I consider https://github.com/ArthurSonzogni/FTXUI/pull/638 to fix a bug.
