### ISSUE TITLE
Implement OSC 8 hyperlink support

### ISSUE THREAD

**Issue by aaleino** [ArthurSonzogni/FTXUI#662]
Is it possible to add terminal hyperlinks, see e.g. [this link](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda )

For example this works:

```
#include <iostream>
#include <string>
  
  int main() {
      std::wstring hyperlink = L"\033]8;;http://example.com\007This is a link\033]8;;\033\n";
      std::wcout << hyperlink;
      return 0;
  }
```

But feeding this string to FTXUI does not seem to work

**Comment by ArthurSonzogni** [comment]
I didn't know about this. It seems a lot of terminal supports it.
It sounds like a good idea!

**Comment by aaleino** [comment]
Would be handy, for example, in my todo manager project for storing links to supporting web pages, hand-written notes or the kind. I tried a bit on an older version of FTXUI, but the escape sequence seemed not to arrive to terminal.
