### ISSUE TITLE
on_enter event of Input doesn't work

### ISSUE THREAD

**Issue by 1024th** [ArthurSonzogni/FTXUI#666]
It seems that this commit https://github.com/ArthurSonzogni/FTXUI/commit/7de4f8683d530ff5573483f40b17df4b3c6ed736 changed the event handling order, making it impossible to trigger the on_enter event.

https://github.com/ArthurSonzogni/FTXUI/blob/7de4f8683d530ff5573483f40b17df4b3c6ed736/src/ftxui/component/input.cpp#L367-L412

**Comment by ArthurSonzogni** [comment]
Thanks! You are right!

**Comment by ArthurSonzogni** [comment]
Congrats for bug 666!

**Comment by ArthurSonzogni** [comment]
Fixed. Thanks for reporting it!
