### ISSUE TITLE
Is the library able to render on ADB shell?

### ISSUE THREAD

**Issue by Biobots** [ArthurSonzogni/FTXUI#67]
I've tried to build the example using ndk toolchain. The output on adb is blank however. The same code works well on windows.

windows:
![windows](https://user-images.githubusercontent.com/13270130/104534389-2a7a5f00-564f-11eb-847a-37ee6fa080c8.png)

adb:
![android](https://user-images.githubusercontent.com/13270130/104534422-39611180-564f-11eb-8074-5d6cf07f9c2d.png)

**Comment by Biobots** [comment]
I tried the following code:
```cpp
        auto document =  //
	vbox({
			gauge(0.5)
	});

	document = document | size(WIDTH, LESS_THAN, 80);

	auto screen = Screen::Create(Dimension::Full(), Dimension::Fit(document));
	Render(screen, document);

	std::cout << screen.ToString() << std::endl;
```

And `screen` is empty, so is there any way to check the value of `document`?

**Comment by ArthurSonzogni** [comment]
Interesting. You are the first trying it on Android.

Questions:
1) Does ```std::cout << "test" << std::endl;``` print something on the Android shell?
2) Maybe the terminal size isn't available on Android.
What returns:
```
screen.dimx()
screen.dimy()
```
Maybe one of them is zero?

What happens if you replace:
```cpp
	auto screen = Screen::Create(Dimension::Full(), Dimension::Fit(document));
```
by
```cpp
	auto screen = Screen::Create(Dimension::Fit(document), Dimension::Fit(document));
```
or even:
```cpp
	auto screen = Screen::Create(Dimension::Fixed(30), Dimension::Fixed(30))
```

**Comment by Biobots** [comment]
Q1: As you can see on the screenshots above, both platforms printed `end`, so `std::cout` works well.
Q2: the value of `dimx()` and `dimy()` is always 0 when using the first statement. However the second one printed the rendered document. It seems that only fixed width and height are available on ADB shell.
