### ISSUE TITLE
[feature request] IP Input component

### ISSUE THREAD

**Issue by mohsenomidi** [ArthurSonzogni/FTXUI#672]
@ArthurSonzogni 
Thanks for your amazing library 

I am wondering to know, is there any plan to add ip address input component separated by .

Thanks 🙏

**Comment by ArthurSonzogni** [comment]
Hi @mohsenomidi 

This is quite specific, and there are many exotic ways to write an IP address. Not sure if this is something easy to do perfectly.

Ideally, I would like to reference some "component" libraries for FTXUI. An IP input one would be great:
https://github.com/ArthurSonzogni/FTXUI/issues/672

If you have a good idea how it should behave maybe you could share an implementation?

**Comment by mohsenomidi** [comment]
Thanks for your reply, I will thinking about it, and will share if I find the way

One more thing, it seems, the link you provided is not referenced to the mentioned component

**Comment by ArthurSonzogni** [comment]
The correct link is:
https://github.com/ArthurSonzogni/FTXUI#libraries-for-ftxui

**Comment by mingsheng13** [comment]
Hi, if I were to implement one, what's the way that you prefer? Should I add an InputOption such as InputOption::IP? Or a new cpp file: IpInput.cpp? Thanks.

**Comment by mohsenomidi** [comment]
Completed 👍
