### ISSUE TITLE
Incorrect and potentially sketchy link in the FTXUI library's README

### ISSUE THREAD

**Issue by avighnac** [ArthurSonzogni/FTXUI#673]
This part of the README:
...
 * Support for [UTF8](https://en.wikipedia.org/wiki/UTF-8) and [fullwidth chars](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms) (→ 测试)
 * Support for animations. [Demo 1](https://arthursonzogni.github.io/FTXUI/examples/?file=component/menu_underline_animated_gallery), [Demo 2](https://arthursonzogni.github.io/FTXUI/examples/?file=component/button_style)
 * Support for drawing. [Demo](https://arthursonzogni.github.io/FTXUI/examples/?file=component/canvas_animated)
 * No dependencies
 * **Cross platform**: Linux/MacOS (main target), WebAssembly, Windows (Thanks to contributors!).
 * Learn by [examples](#documentation), and [tutorials](#documentation)
 * Multiple packages: CMake [FetchContent](https://bewagner.net/programming/2020/05/02/cmake-fetchcontent/) (preferred), vcpkg, pkgbuild, conan.
 * Good practises: documentation, tests, fuzzers, performance tests, automated CI, automated packaging, etc...
...

contains a sketchy link.

The link that FetchContent leads to does not seem to be the intended one, and instead leads to this website:
![image](https://github.com/ArthurSonzogni/FTXUI/assets/74564976/0f7c464e-520f-4208-9b00-801851872695)

**Comment by ArthurSonzogni** [comment]
Thanks!
It looks like the link is broken. I used another one.
