### ISSUE TITLE
Draggable components.

### ISSUE THREAD

**Issue by ArthurSonzogni** [ArthurSonzogni/FTXUI#682]
Suggested by @yrashk in discussion:
https://github.com/ArthurSonzogni/FTXUI/discussions/680

We woud like to wrap some component inside some kind of `Window`. The window
should:
- Be Draggeable using the mouse.
- (Optionally) Have a title bar
- (Optionally) Have a close button

The `WindowContainer` should allow to stack multiple `Window` on top of each
others. Clicking on a window should bring it to the top.

If possible we should find a way to make it possible to control the window
by the keyboard too.

API proposal:
```cpp
// Minimal window filled with default values:
auto win_0 = Window({
    .inner = component_1,
    .title = "Minimal example",
});

// Example with parameters with default value:
auto win_1 = Window({
    .inner = component_1,
    .title = "Example initial values",
    .left = 10,
    .right = 10,
    .width = 40,
    .height = 20,
    .closeable = false,
    .closed = false,
});

// Example with some parameters passed by reference:
int component_2_left = 10;
int component_2_right = 10;
int component_2_width = 40;
int component_2_height = 20;
auto win_2 = Window({
    .inner = component_2,
    .title = "Example with external values referenced from outside",
    .left = &component_2_left,
    .right = &component_2_right,
    .width = &component_2_width,
    .height = &component_2_height,
    .closeable = true,
    .closed = false,
};

auto win_container = WindowContainer({
  win_0,
  win_1,
  win_2,
});
```

This might be a little too "opinionated" for this to be part of FTXUI. At first,
it might be some kind of official extensions.

**Comment by yrashk** [comment]
Thank you for opening an issue. Do you think we can break this down to some primitives to make any element "tell" FTXUI where it wants to be rendered (maybe a coordinates offset?)

**Comment by yrashk** [comment]
As for the window component, it is definitely opinionated and should likely be external to the library. That being said, I still think that it would be essential to have primitives to build this kind of functionality. 

For example, it can be the ability for elements to tell their coordinates (or offsets), to have a `draggable` component that wraps another component and knows how to be dragged, etc.

**Comment by ArthurSonzogni** [comment]
> Thank you for opening an issue. Do you think we can break this down to some primitives to make any element "tell" FTXUI where it wants to be rendered (maybe a coordinates offset?)

It is already available via the `reflect` element. See this reply: https://github.com/ArthurSonzogni/FTXUI/issues/521#issuecomment-1336250274

**Comment by yrashk** [comment]
I am not yet sure how `reflect` can be used to tell FTXUI where **to** render? If I am not mistaken, `reflect` stores the information on where the element **is** rendered.

**Comment by ArthurSonzogni** [comment]
I started something:
https://twitter.com/arthursonzogni/status/1670092556753928193

https://github.com/ArthurSonzogni/FTXUI/assets/4759106/346f665f-35b2-4ca0-8006-8e3697612e52

-----------

>  I am not yet sure how reflect can be used to tell FTXUI where to render? If I am not mistaken, reflect stores the information on where the element is rendered.

It is used only to reflect into a `ftxui::Box` the location where the element was drawn into the screen. This is not really about specifying where to draw something.

You can write your own element, or combine existing ones like this:
```cpp
      auto element = inner
                     | size(WIDTH, EQUAL, width())
                     | size(HEIGHT, EQUAL, height());

      auto padding_left = 
      auto padding_top = emptyElement() | size(HEIGHT, EQUAL, top());

      return vbox({
          padding_top,
          hbox({
              padding_left,
              element,
          }),
      });
```

**Comment by yrashk** [comment]
The window component video is amazing! I would love to see it materialize soon, and I want to learn how you did it, as the code snippet you have provided makes sense for placing a single element on the screen, but I am failing to understand how to do this right for multiple elements like those windows in the demo above. Any chance you can show the gist of it?

**Comment by ArthurSonzogni** [comment]
Here is the work in progress implementation:
https://github.com/ArthurSonzogni/ftxui-window/blob/main/include/ftxui-window/ftxui-window.hpp

I think I might push it into FTXUI if I am happy with it at the end.

**Comment by yrashk** [comment]
Thank you!

**Comment by ArthurSonzogni** [comment]
I am progressively moving into FTXUI.

Ideally, this component should offer ways for the users to customize how the window looks like.

Here are two attempt about highlighting the borders are resizeable:

https://github.com/ArthurSonzogni/FTXUI/assets/4759106/9035001a-6dcd-4393-bef3-163d5289acbc




https://github.com/ArthurSonzogni/FTXUI/assets/4759106/a2ba9cda-a838-4484-a85d-24046436765d

**Comment by ArthurSonzogni** [comment]
Implemented!
