### ISSUE TITLE
Clarification in Canvas documentation

### ISSUE THREAD

**Issue by ayoshi007** [ArthurSonzogni/FTXUI#694]
Hello, thanks for the great library!
I apologize if this is pedantic, but I was looking through the documentation for the Canvas struct [here](https://arthursonzogni.github.io/FTXUI/structftxui_1_1Canvas.html#a6a78dda2095054ffa03f215f0153bdbb) says that a cell is a 2x8 braille dot.
I think it would be better to say it is a 2x4 braille dot.

**Comment by ArthurSonzogni** [comment]
Thanks you for reporting this! I fixed it in https://github.com/ArthurSonzogni/FTXUI/commit/79f8293a0df9fd88f56f0035e70233adbee4ab51
