### ISSUE TITLE
Support for Mouse Events

### ISSUE THREAD

**Issue by SanJ2312** [ArthurSonzogni/FTXUI#7]
I was wondering if there is also support for mouse events here !!!

**Comment by ArthurSonzogni** [comment]
That would be a nice feature! 
I can configure the terminal to send mouse events, then forward the events using the mechanism we already have.

I will take a look!

**Comment by xiaohuahou** [comment]
Yeah, I am also looking for mouse support.

**Comment by ArthurSonzogni** [comment]
Difficulty is the component doesn't know the area it renders. It just output some DOM element, and the elements are drawing themselves on the screen in a responsive manner.

I have some ideas to be tried in mind.

**Comment by ArthurSonzogni** [comment]
I am almost done with mouse support! Add mouse support was a great idea! It feels awesome!
I would appreciate folks to give me feedback and check how well non-linux OS are handling this.

This is on the branch:
https://github.com/ArthurSonzogni/FTXUI/tree/feature/mouse-support

**Comment by Daniel-Boll** [comment]
Just tested in Arch (with alacritty), so smooth, working just fine. I can also ask a friend of mine to test it out on Windows even though on wsl2 is usually kinda glitchy might just be the interface renderer there.

**Comment by ArthurSonzogni** [comment]
Thanks @Daniel-Boll !

I am going to work on a slider component, controllable by keyboard and mouse. This might require being able to "capture" mouse events to avoid releasing slider when the mouse leave the component when moving the slider.

**Comment by ArtificialOwl** [comment]
Is it supposed to work in a `tty` terminal ?
