### ISSUE TITLE
Should Screen class have const accessors?

### ISSUE THREAD

**Issue by niosus** [ArthurSonzogni/FTXUI#700]
the `Screen` class has accessors for the pixel color and methods like `ToString()`, which are not marked as `const`. Is there a reason why they are not? I'd say that there should be these methods (among other ones like them):
```cpp
const Pixel& PixelAt(int x, int y) const;

std::string ToString() const;
```

Am I missing something?

**Comment by ArthurSonzogni** [comment]
The value returned from PixelAt belong to the Screen, so it has to be const if Screen is const. Otherwise this looks good to me?

We would get this API:
```cpp
const Pixel& PixelAt(int x, int y) const;
Pixel& PixelAt(int x, int y);
std::string ToString() const;
```

Do you want to make a pull request? Or should assign this to me?

**Comment by niosus** [comment]
Oh yeah, sorry, I mistyped. I meant a const ref return of course. I can make a PR today or tomorrow, sure.
