### ISSUE TITLE
On resizing the window the ui (visually) breaks

### ISSUE THREAD

**Issue by VogelPapaFinn** [ArthurSonzogni/FTXUI#702]
Hi,
when I resize the console window my application runs in the ui breaks. Usually its only visual and buttons and stuff is still functional but its pretty annoying.  
I tried the `screen.Clear()` function but there is no effect. Any ideas how I can fix this issue? 

How it should look like:
![grafik](https://github.com/ArthurSonzogni/FTXUI/assets/38922171/8f448002-aa46-42f8-aad3-573e8b7938f1)

Example of how it looks after resizing:
![grafik](https://github.com/ArthurSonzogni/FTXUI/assets/38922171/21887790-6614-4840-be92-d21fce679412)

**Comment by ArthurSonzogni** [comment]
Hello!

Are you using:
```
  auto screen = ScreenInteractive::Fullscreen();
```
If not, could you try and tell if this improves what you see?

**Comment by Xie-jie-jie** [comment]
Hi,
I also meet this problem when resizing the window or moving the window to another display.
I found that `auto screen = ScreenInteractive::Fullscreen()` solved this problem.
However,  `ScreenInteractive::FitComponent()` and  `ScreenInteractive::TerminalOutput();` will cause this problem.

**Comment by VogelPapaFinn** [comment]
Hi,
this makes the ui worse but thats okay for me. I probably need to change my code a bit so it looks better. Thanks!
I do have another problem tho but for that I will create a new issue.
