### ISSUE TITLE
Performance improvement by refactoring pixel styles

### ISSUE THREAD

**Issue by clement-roblot** [ArthurSonzogni/FTXUI#703]
Hi everyone,

My brain is exploding because of how cool this lib is, it uses basically no RAM, but it is nevertheless happy with CPU usage. I started looking into it and got some ideas, here is the first.

In my test program (the downloader example with some changes), I can see that most of the CPU time is spent in the Screen::Print method, one of the methods that takes more time than I would expect inside is the pixel comparison that is happening between each consecutive pixels at every frame (inside of UpdatePixelStyle):

```
bool Pixel::operator==(const Pixel& other) const {
  return character == other.character &&                //
         background_color == other.background_color &&  //
         foreground_color == other.foreground_color &&  //
         blink == other.blink &&                        //
         bold == other.bold &&                          //
         dim == other.dim &&                            //
         inverted == other.inverted &&                  //
         underlined == other.underlined &&              //
         automerge == other.automerge;                  //
}
```

In the context of UpdatePixelStyle we don't need to compare the character and as for the rest we compare colors and the bit fields for the style. By storing that bit field into a union we can make the compare between pixel styles a 1 operation step (instead of testing each element of style one by one). The union looks like this:
```
  typedef union
  {
      struct
      {
        uint8_t blink : 1;
        uint8_t bold : 1;
        uint8_t dim : 1;
        uint8_t inverted : 1;
        uint8_t underlined : 1;
        uint8_t underlined_double : 1;
        uint8_t strikethrough : 1;
        uint8_t automerge : 1;
      } bit;
      uint8_t all;
  } Style;
```
And with those modification, I can create a pixel comparison method that looks like that:
```
bool Pixel::isSameStyle(const Pixel& other) const {
  return style.all == other.style.all &&  //
         background_color == other.background_color &&  //
         foreground_color == other.foreground_color;
}
```

The effects regarding performance is that one my test app that is mostly the downloader example, using perf to get numbers, I can see that the original == operator took between 8% and 9% of the CPU used, with my changes we are between 2.5% and 3%.

Does this sound like an improvement that would be approved if I properly and cleanly implement it in a pull request?

**Comment by clement-roblot** [comment]
BTW half of the CPU usage inside of my Pixel::isSameStyle is for comparing colors, and a similar mechanism could be implemented there too, so this approach can yield even more benefits than what is described above. :wink:

**Comment by ArthurSonzogni** [comment]
> My brain is exploding because of how cool this lib is
Thanks for those kind words ;-)

---

> Does this sound like an improvement that would be approved if I properly and cleanly implement it in a pull request?

Yes, it would! Thanks for proposing it!

I was hoping the compiler to be smart enough to optimize this. Before merging your patch, I am going to work on adding some performance tests, so that I can quantify the performance improvement and make sure we are not doing premature optimizations.
