### ISSUE TITLE
Under some circumstances the console is filled with data on mouse movement

### ISSUE THREAD

**Issue by VogelPapaFinn** [ArthurSonzogni/FTXUI#706]
Hey,
when I use the ui via ssh on a raspberrypi and the pi suddenly turns off/crashes or whatever, on mouse movement the command line is filled with random "data". I saw [this](https://github.com/ArthurSonzogni/FTXUI/issues/617) issue where the author described the same problem. The weird part:
When the ssh connection closes due to timeout the bug still persists. Even on my local computer the console fills itself when I move the mouse. I need to completely restart my console to fix it.
Is there a way to fix this? Its quite annoying :|
Thx!

**Comment by VogelPapaFinn** [comment]
So there is no known fix?

**Comment by ArthurSonzogni** [comment]
> So there is no known fix?

Indeed.
