### ISSUE TITLE
Amazing, just amazing! I'm building something similar in TypeScript...

### ISSUE THREAD

**Issue by colinta** [ArthurSonzogni/FTXUI#711]
Long ago I found the [blessed](https://github.com/chjj/blessed) library and thought it was really cool, but never cared for the box model (absolute x/y, width/heights) and the OO style. At one point I had fun creating a [declarative terminal UI in Swift](https://github.com/colinta/Ashen), but these days I'm mostly writing React-Native & TypeScript...

And so, grabbing from Blessed the parts I needed, and `rm -rf` the rest, I created [wretched][https://github.com/wretched-tui/wretched)

I've been looking around for design inspiration, and FTXUI is the #1 thing I've found out there. Actually, I would love to know how you implement "raw mode like" without having to go full screen. Is that something I could easily implement? (the hard part – measuring components and only drawing the necessary area – is already done).

**Comment by colinta** [comment]
Oh, and I'd like to imitate some of your UI – especially the animations for tabs and buttons. Would you be offended if I stole those from you!? I will gladly link back to your repo, of course!

**Comment by ArthurSonzogni** [comment]
Thanks for those kind words!

> Actually, I would love to know how you implement "raw mode like" without having to go full screen. Is that something I could easily implement?

It is a matter of clearing the correct lines and setting the cursor position correctly.

Let's say you have draw the previous frame (prev) and you want to draw the one. Then you would:
1. Repeat `prev.height` times: Move up and clear line.
2. Repeat `prev.height` times: Move down.
3. Repeat `next.height` times: Move up.
4. Draw `next`.

There are some additional difficulties to handle users for users with IME (input method editor), but you get the idea.

> Oh, and I'd like to imitate some of your UI – especially the animations for tabs and buttons. Would you be offended if I stole those from you!? I will gladly link back to your repo, of course!

Sure! I wouldn't be offended at all! About the animations for tabs, @willmcgugan is the one who got the original idea. See: https://www.youtube.com/watch?v=59CVt9gVcvo

**Comment by ArthurSonzogni** [comment]
I guess I might be able to close this issue?

**Comment by colinta** [comment]
👍
