### ISSUE TITLE
Splitting the terminal into two streaming parts and a fixed control part

### ISSUE THREAD

**Issue by afpgit** [ArthurSonzogni/FTXUI#714]
First of all, what an amazing library is FTXUI! I just love it! 

I have a datastream application where I read data from two different hardware and process them in real-time. I want to see if I can use FTXUI to split the screen into 3 parts (all visible at the same time to the user):

1. Printing information about hardware#1 in part 1 of the screen (scrollable to see the history of what happened to hardware#1).
2. Printing information about hardware#2 in part 2 of the screen (scrollable to see the history of what happened to hardware#2).
3. Lastly, in part 3, a few controls like radio buttons, and push buttons to change the way the software interacts with the two hardware. These controls are all static and let the user apply some changes to the software in real-time without the need for restarting the software.

I use Google glog (https://github.com/google/glog) to (A) print the data received from hardware to the terminal and (B) save the history into a log file.

Is this something FTXUI can help? I hope I have explained the request clearly, if not, please let me know.

Looking forward to hearing from you.

Thank you very much.

**Comment by ArthurSonzogni** [comment]
Hi @afpgit!

Thanks for using FTXUI. I think what you describe would work perfectly.

- You might want to import: https://github.com/ArthurSonzogni/git-tui/blob/master/src/scroller.hpp to be able to scroll over a component.

- Not sure what you want to do with glog, but you would have to find a way to get back the strings and plumb them into FTXUI.

- Depending of how many entries you have, if you have several thousand, you might have to display a slice of it to avoid ftxui to do extensive layout computations. When you will have the problem, don't hesitate to ask.

**Comment by ArthurSonzogni** [comment]
I guess this issue can be closed ;-)
