### ISSUE TITLE
Strange character displayed on quitting

### ISSUE THREAD

**Issue by benoitdudu** [ArthurSonzogni/FTXUI#716]
![ftxui](https://github.com/ArthurSonzogni/FTXUI/assets/54201651/970a18df-f868-4a29-b250-6163f0aecca7)

Hello,

I got a strange character displayed when quitting ftxui.
After trying to find why this character was displayed, I found that it comes from https://github.com/ArthurSonzogni/FTXUI/blob/main/src/ftxui/component/screen_interactive.cpp#L575.

My terminal is 'MATE Terminal 1.16.3' on Centos 7.

Any idea why I have this behavior?
It seems that 'Fullscreen' application don't have the problem.

**Comment by ArthurSonzogni** [comment]
Hello!
I guess mate-terminal has a bug?

On ubuntu based distro, I installed `mate-terminal`. I can't reproduce the issue you are describing:

https://github.com/ArthurSonzogni/FTXUI/assets/4759106/88f5f654-4ad4-4db2-85ad-b6f1cbb612e8

**Comment by benoitdudu** [comment]
Yes it is maybe a bug of my mate-terminal.
