### ISSUE TITLE
Allow selecting and copying text

### ISSUE THREAD

**Issue by StefanRvO** [ArthurSonzogni/FTXUI#725]
Hi

In my application, it is useful to be able to use the mouse to select and copy some of the text in the UI and copy it somewhere else.

However, currently, that is not possible unless I comment out these lines: https://github.com/ArthurSonzogni/FTXUI/blob/main/src/ftxui/component/screen_interactive.cpp#L583-L586

This also disables grabbing of mouse events, but that is OK for me as i don't use the mouse in my application.

Would it be possible to implement some kind of toggle, maybe as an argument to the ScreenInteractive constructors that disables mouse events so that it is possible to select text in the UI? Or is there a more smooth way you can think of doing this? It may also be that an option already exists and i just haven't noticed it :) .

I'm willing to give it a go to do the changes, just want to test the waters a bit first :)

**Comment by ArthurSonzogni** [comment]
I think we could. I need to figure out what is the best way to build a `ScreenInteractive` with some options.

**Comment by StefanRvO** [comment]
I have made a suggestion of how i think it could be done in #726 :)

**Comment by StefanRvO** [comment]
Closing as this was merged in #726
