### ISSUE TITLE
Can you use DOMs and Components together in one application?

### ISSUE THREAD

**Issue by VogelPapaFinn** [ArthurSonzogni/FTXUI#736]
Hey,
I need to use two tables in my application but I cant get them to run. To be more specific to be shown. At the start of the application I can see the data for a split of a second but after that I cant see them at all. My components are rendering fine.

Im using a thread to update the screen every 0.05s seconds as shown in the docs:
```
std::thread refreshUiThread([&] {
        while (allThreadsShouldContinue) {
            using namespace std::chrono_literals;
            std::this_thread::sleep_for(0.05s);

            // The |shift| variable belong to the main thread. `screen.Post(task)`
            // will execute the update on the thread where |screen| lives (e.g. the
            // main thread). Using `screen.Post(task)` is threadsafe.
            screen.Post([&] { shift++; });

            Render(screen, guiSendDataTable.Render());

            // After updating the state, request a new frame to be drawn. This is done
            // by simulating a new "custom" event to be handled.
            screen.Post(Event::Custom);
        }
    });
```

In my main renderer I placed the table at the position I want with `guiSendDataTable.Render(),`.

I created the screen as follows:

```
// Main Window
auto screen = ScreenInteractive::Fullscreen();

// Here starts the thread see above

screen.Loop(mainRenderer);
```

Am I doing something wrong?
Thanks already!

**Comment by VogelPapaFinn** [comment]
I just found out two things:
1. The refreshUiThread 'kills' the table
2. Removing the refreshUiThread fixes the issue until the window is resized. Then the table disappears again.
Any idea what I am doing wrong?

**Comment by ArthurSonzogni** [comment]
Hello!

The table is meant to be used only once.
FTXUI is meant to be "functional". You should create a function: state -> UI.

You should get rid of `guiSendDataTable` and instead call the new function repeatedly for every new frame.

Happy to help more if you are willing to provide some source code.

**Comment by VogelPapaFinn** [comment]
Hmm... So the table should be created every frame or what do you mean with "new function"?
But in conclusion this means there cant be two tables at the same time displaying two different things?

**Comment by ArthurSonzogni** [comment]
> Hmm... So the table should be created every frame or what do you mean with "new function"?

I mean creating two functions returning the table as an `ftxui::Element`:
```cpp
#include <ftxui/dom/elements.hpp>
#include <ftxui/dom/table.hpp>
#include <ftxui/screen/screen.hpp>

using namespace ftxui;

Element Table1(int shift) {
  Table table;
  //[...]
  return table.Render();
}

Element Table2() {
  //[...]
}

// Render two table side by side.
class MyComponent : public ComponentBase {
 public:
  Impl(int* shift) : shift_(shift) {}

 private:
  Element Render() override {
    return hbox({
        Table1(*shift),
        Table2(),
    });
  }
  int* shift_;
};

int main(int argc, const char* argv[]) {
  int shift = 0;
  auto component = Make<MyComponent>(&shift);
  auto screen = ScreenInteractive::Fullscreen();

  Loop loop(&screen, component);

  while (!loop.HasQuitted()) {
    loop.RunOnce();

    shift++;
    std::this_thread::sleep_for(std::chrono::milliseconds(10));
  }

  return 0;
}
```

> But in conclusion this means there cant be two tables at the same time displaying two different things?

Just create the two table as Element, and compose them together using the `vbox` / `hbox` Elements.


---

Note: I don't understand why you are using `Render` on a ScreenInteractive. This is almost certainly very wrong.

**Comment by VogelPapaFinn** [comment]
Ah okay now I understood, thank you!

> Note: I don't understand why you are using Render on a ScreenInteractive. This is almost certainly very wrong.
Oh shoot, that is old code I've forgot to remove. Thanks for the advice.
