### ISSUE TITLE
ResizableSplit showing up but not working

### ISSUE THREAD

**Issue by VogelPapaFinn** [ArthurSonzogni/FTXUI#740]
Heyho its me again :|

Im trying to get the ResizableSplit(Left) to work. The visual part works but the mouse part doesnt:
![grafik](https://github.com/ArthurSonzogni/FTXUI/assets/38922171/f2d93aff-43aa-40dc-b8dc-ea28f233a5b1)

Dragging the edge between "Left" and "middle" has absolutely no effect. I even copied the example code but its not working. I'd it has something to do with my rendering. As you probably know from my last issue, I use a thread to update my screen every 0.05s:

```
    int shift = 0;
    bool allThreadsShouldContinue = true;
    std::thread refreshUiThread([&] {
        while (allThreadsShouldContinue) {
            using namespace std::chrono_literals;
            std::this_thread::sleep_for(0.05s);

            // The |shift| variable belong to the main thread. `screen.Post(task)`
            // will execute the update on the thread where |screen| lives (e.g. the
            // main thread). Using `screen.Post(task)` is threadsafe.
            screen.Post([&] { shift++; });
            // After updating the state, request a new frame to be drawn. This is done
            // by simulating a new "custom" event to be handled.
            screen.Post(Event::Custom);
        }
    });
```

The code for the ResizableSplitLeft looks like this:

```
int left_size = 20;
auto middle = Renderer([] { return text("middle") | center; });
auto left = Renderer([] { return text("Left") | center; });
auto container = ResizableSplitLeft(left, middle, &left_size) | flex;

auto mainRenderer = Renderer(mainComponent, [&]{
[...]
  return vbox({
            [...]
            container->Render()
  });
}
```

**Comment by ArthurSonzogni** [comment]
Hello,
Could you please provide a full minimal example?

The FTXUI's is working well: https://arthursonzogni.github.io/FTXUI/examples/?file=component/resizable_split

**Comment by VogelPapaFinn** [comment]
Heyho,
I found the issue. Our code base got actually quite big and it seems like I added the container to the wrong "mainComponent". Therefore it was rendered but the logic didnt work.
Im terribly sorry for that!
Thanks (I found it while creating the full minimal example)!
