### ISSUE TITLE
Holding mouse1 and dragging the mouse clicks button multiple times

### ISSUE THREAD

**Issue by DuarteBarbosaRibeiro** [ArthurSonzogni/FTXUI#748]
If you hold down mouse1 and drag your mouse on a button, the on_click event is fired multiple times. I first noticed it on my machine (a VM with Linux Mint) with this exact [example code](https://arthursonzogni.github.io/FTXUI/examples_2component_2button_animated_8cpp-example.html#a13) but I also managed to replicate it on the web version of [termBreaker](url) by collecting 6000 coins (enough to make the first 2 purchases in the shop), then holding down mouse1 and dragging the mouse on the Buy 5 balls button.

**Comment by ArthurSonzogni** [comment]
It will be fixed by:
https://github.com/ArthurSonzogni/FTXUI/pull/774
