### ISSUE TITLE
Question: what is reflect and box?

### ISSUE THREAD

**Issue by mingsheng13** [ArthurSonzogni/FTXUI#756]
When reading the codes, I came across this multiple times and couldn't figure out what is it doing. 
` reflect(box) `
I've read through the documentation, but there are no detailed explanation.

**Comment by ArthurSonzogni** [comment]
When drawn, the dimensions of the drawn element will be written into `box`.

This is useful to implement something clickable. It means in the next iteration, you can compare the mouse position with the box.

Would you like to submit a patch improving the associated documentation?
