### ISSUE TITLE
`ScreenInteractive::Fullscreen` forces alternative screen

### ISSUE THREAD

**Issue by rbrugo** [ArthurSonzogni/FTXUI#766]
Hi,
I would like to preserve the output of my fullscreen program after its end, but I can't find a way to do that because [the implementation of `ScreenInteractive::Fullscreen`](https://github.com/ArthurSonzogni/FTXUI/blob/d4c9c5e22665692ddf6ea337df1217aa1b7a91d9/src/ftxui/component/screen_interactive.cpp#L361) forces the screen to alternate, cleaning the program output. Also, the constructor and the `Dimension` enum are private, so I can't construct the screen with those properties myself

**Comment by ArthurSonzogni** [comment]
Thanks for implementing this!
