### ISSUE TITLE
Color extraction out of Color object

### ISSUE THREAD

**Issue by clement-roblot** [ArthurSonzogni/FTXUI#770]
Hello there,

I'm making a system that allows for themes that requires me to save the colors chosen by the user to a file (I'm using `QSetttings` for that). To save the colors I need to, well, access the R, G and B values which is not currently possible (as far as I can see).

In `Color::Interpolate`, there is a lambda function that effectively does what I want (named: `get_color`). If I understand well it would go against the "spirit of the lib" to make this lambda a public method for the color object?

For my individual problem, I could use a `QColor` object for the saving and loading part and copy the `QColor` into a `ftxui::color` object when I want to render, but that feels complicated and dirty for no reason.

Here are my questions:
- Did I miss something that would allow me to get the R, G and B from a color object
- Did I not understand the spirit of the lib
- would making `get_color` public be accepted as an MR?

**Comment by jdfa** [comment]
Looks like it is related to #486

**Comment by clement-roblot** [comment]
Indeed the goal is the same, I'm closing this issue and continuing/grave-digging the conversation back up in #486.
