### ISSUE TITLE
Click and drag tiggers buttons and checkboxes repeatedly

### ISSUE THREAD

**Issue by clement-roblot** [ArthurSonzogni/FTXUI#773]
Hi there,

I made a video but for some reason it doesn´t look like the real deal. But here it is anyway:

![2023-10-23 21-19-00](https://github.com/ArthurSonzogni/FTXUI/assets/2040179/d87b3392-480f-4922-ae79-4f16497a3544)

If you click on a checkbox or a button and keep your left mouse button pressed and start drawing the mouse sideways, it will toggle on and off the checkbox (or repeatedly click the button). This behavior leads to sometimes having a button triggering the onClick event twice even though I though I clicked it only once.

I would like to add an option to the button object (and also to the checkbox object) that would enable a mechanism looking for a released to press motion to trigger an OnClick event, rather than just looking for press events as it is now. Here is a quick example that works for me for a button:

![image](https://github.com/ArthurSonzogni/FTXUI/assets/2040179/6ed284a4-91bf-4d5e-b393-76cf282bdacb)

Does such an implementation look valid, should I go forth with a PR?

**Comment by ArthurSonzogni** [comment]
It might. Would you like to propose a pull request?
