### ISSUE TITLE
Add an image display component

### ISSUE THREAD

**Issue by ljrrjl** [ArthurSonzogni/FTXUI#782]
Hi, I think FTXUI might be able to display images on the command line, here's a simple implementation of mine. [image-view-ftxui](https://github.com/ljrrjl/image-view-ftxui.git)

**Comment by ArthurSonzogni** [comment]
Thanks!

@ljrrjl, adding some kind of support builtin into FTXUI would require adding dependencies on some image loading libraries. I don't believe this would benefits most users.

Maybe we can think about a FTXUI extension? Something similar to:
https://github.com/ArthurSonzogni/FTXUI#libraries-for-ftxui

What do you think?

**Comment by ljrrjl** [comment]
Thanks for your reply, I am going to add this [project](https://github.com/stefanhaustein/TerminalImageViewer) to the dependency to display color images on the command line. When I'm done I'll submit a PR to add it to https://github.com/ArthurSonzogni/FTXUI#libraries-for-ftxui.
