### ISSUE TITLE
how to get a mdal dialog window (Stacked)?

### ISSUE THREAD

**Issue by walkthetalk** [ArthurSonzogni/FTXUI#786]
in other words, does ftxui has concept of dialog window?

**Comment by ArthurSonzogni** [comment]
Sure!

Did you see the examples:
- https://arthursonzogni.github.io/FTXUI/examples/?file=component/modal_dialog
- https://arthursonzogni.github.io/FTXUI/examples/?file=component/modal_dialog_custom
- https://arthursonzogni.github.io/FTXUI/examples/?file=component/window

See the components:
- `Modal` => [Example](https://github.com/ArthurSonzogni/FTXUI/blob/main/examples/component/modal_dialog.cpp#L78).
- `Maybe` => [Example](https://github.com/ArthurSonzogni/FTXUI/blob/main/examples/component/maybe.cpp).
- `Window` => [Window](https://github.com/ArthurSonzogni/FTXUI/blob/main/examples/component/window.cpp).

**Comment by walkthetalk** [comment]
:+1:
