### ISSUE TITLE
No definition for `Component Checkbox(CheckboxOption options)` method

### ISSUE THREAD

**Issue by ParticleG** [ArthurSonzogni/FTXUI#795]
There's no definition for [`Component Checkbox(CheckboxOption options)`](https://github.com/ArthurSonzogni/FTXUI/blob/a7b678542074722022ca31553c7eb47fa0dc4936/include/ftxui/component/component.hpp#L54C11-L54C19)

Which would cause a link error: `error LNK2019: unresolved external symbol "class std::shared_ptr<class ftxui::ComponentBase> __cdecl ftxui::Checkbox(struct ftxui::CheckboxOption)"`

**Comment by ArthurSonzogni** [comment]
Hello,
Could you please specify how you are compiling FTXUI?
Are you using cmake?

**Comment by ArthurSonzogni** [comment]
Ho I think you are right! I will take a look.

**Comment by ParticleG** [comment]
> Ho I think you are right! I will take a look.

I just created a fork. Or you could fix it very easily

**Comment by ParticleG** [comment]
See #796
