### ISSUE TITLE
Checkbox does not `TakeFocus()` when clicked

### ISSUE THREAD

**Issue by jason-e** [ArthurSonzogni/FTXUI#798]
When clicking a Checkbox component, its state changes as expected, but it does not call `TakeFocus()`. This means some other component will still have focus and will receive keyboard input. It also means that the only way to toggle a Checkbox with the space or enter keys is by first navigating to it with the keyboard.

**Comment by ArthurSonzogni** [comment]
Thanks for reporting this! Would you like to submit a PR fixing this?

**Comment by jason-e** [comment]
Done!

**Comment by ArthurSonzogni** [comment]
Thanks!
