### ISSUE TITLE
ftxui_set_options.cmake: unable to compile on windows.

### ISSUE THREAD

**Issue by nyyakko** [ArthurSonzogni/FTXUI#801]
Hello guys. I've ran into an issue when trying to link agaisnt FTXUI on windows with CMake, LLVM and Ninja as generator. 

The issue seems arise because of [this line](https://github.com/ArthurSonzogni/FTXUI/blob/d0634e1ca0ba4a157e27e3ab2e95e6c796eb0ad6/cmake/ftxui_set_options.cmake#L49)  in ftxui_set_options.cmake file:

```cmake
# . . .
  if (MSVC)
    target_compile_options(${library} PUBLIC "/utf-8") # <-- the faulty one.
  endif()
# . . .
 ```
 
It seems that when making this patching, clang actually doesn't like it and simply refuses to to compile the code and produces the following output:

![image](https://github.com/ArthurSonzogni/FTXUI/assets/36525792/fec9ff76-90ff-4018-bd61-7efec1d6f3af)

If I remove the option ``/utf-8`` manually from the generated build.ninja, it compiles just fine, producing the following output:

![image](https://github.com/ArthurSonzogni/FTXUI/assets/36525792/1dac530a-697c-4378-961a-44fe2bcf5c91)

I think a better way would be to use the ``CMAKE_CXX_COMPILER_ID`` flag to detect the compiler and properly decide as to feed or not the flag, because if kept the way it is right now i am unable to actually use the library outside from linux with my current setup. Unless there's an option I am missing and that I should enable, if thats the case, i'd like to know what i should do properly use this library.

**Comment by ArthurSonzogni** [comment]
Thanks!

The suggestion solution works for me. Would you like to submit a PR replacing `MSVC` by `CMAKE_CXX_COMPILER_ID STREQUAL "MSVC"`?

**Comment by nyyakko** [comment]
> Thanks!
> 
> The suggestion solution works for me. Would you like to submit a PR replacing `MSVC` by `CMAKE_CXX_COMPILER_ID STREQUAL "MSVC"`?

done!
