### ISSUE TITLE
ButtonBase::OnClick ordering

### ISSUE THREAD

**Issue by lukester1975** [ArthurSonzogni/FTXUI#804]
Hi

Really nice library!

I've tripped over an issue with the ordering of `ButtonBase::OnClick`:

```cpp
  void OnClick() {
    on_click();
    animation_background_ = 0.5F;  // NOLINT
    animation_foreground_ = 0.5F;  // NOLINT
    SetAnimationTarget(1.F);       // NOLINT
  }
```

As written, an `on_click` handler can't drop the ref count for the button to 0. Would you consider moving the `on_click` invocation to be the last statement in `ButtonBase::OnClick`? Right now I've got a custom button class just to reorder that function, which is a shame!

Or alternatively, increment the ref count before invoking any user callbacks (probably safest but a pain with having to `std::enable_shared_from_this` the type). I'm sure I could avoid the issue with posting an event inside the `on_click` handler rather than dropping the ref count immediately, but seems a bit unnecessary...

Thanks!

**Comment by ArthurSonzogni** [comment]
Thanks!
I addressed your suggestion.
