### ISSUE TITLE
How create the library

### ISSUE THREAD

**Issue by SergeyYaroslawzew** [ArthurSonzogni/FTXUI#83]
How do I create statistical libraries from your project files? I really want to start writing programs using your wonderful library, but I do not know how to connect it to the code as in the examples. I use VS code and OS Windows 64x

**Comment by ArthurSonzogni** [comment]
In the README.md, I put instructions about how to start using it. There is even a start project.
- [Starter example project](https://github.com/ArthurSonzogni/ftxui-starter)
- [Build using CMake](https://arthursonzogni.com/FTXUI/doc/#build-using-cmake)

I would recommend using cmake. If you want
I am not familiar with VS code. How do you import libraries usually?
Maybe you can try to build ftxui-starter into VS code?

I have seen:
https://github.com/microsoft/vcpkg/issues/16327
Would adding a FTXUI config to VCPKG help you?

**Comment by SergeyYaroslawzew** [comment]
Thank you so much for your advice. It helped me a lot. I wish you success in your projects.

**Comment by ArthurSonzogni** [comment]
Thanks!
