### ISSUE TITLE
Allow Canvas re-use for optimization

### ISSUE THREAD

**Issue by WildRackoon** [ArthurSonzogni/FTXUI#836]
My current workflow requires to incrementally draw a few dots on a canvas alongside the ones drawn in the previous frames, to this end, my program has to redraw everything each frame and keep track of previously drawn primitives/pixels separately (outside the `Canvas`).

Unless another solution that I am not aware of exists, this issue focuses on the following things:

Currently there is no way to re-use a ftxui::Canvas accross frames using the available dom `canvas(...)` overloads:
See (https://github.com/ArthurSonzogni/FTXUI/blob/main/src/ftxui/dom/canvas.cpp#L852C1-L895C1)
- The `ConstRef<Canvas> canvas` overload moves the given `Canvas`, we cannot repaint on it afterwards.
- The `std::function<void(Canvas&)> fn` always recreates a temp `Canvas`on which our lambda must paint on.

I think one of the following solutions could be appropriate:
- Have some kind of `Ref<Canvas> canvas` overload, ressource management is manual though
- Have a `std::function<void(Canvas&)> fn` overload, use a re-useable`std::shared_ptr<Canvas>`
- Have a  `std::function<void(Screen&)> fn` overload, to paint directly on `Screen`

Slightly off-topic note: having the ability to override `ComputeRequirement()` in the  `std::function<void(Canvas&)> fn` overload would be a nice addition to dynamically change the `Canvas` size without changing the dom entirely.

**Comment by Epixu** [comment]
I have just proposed a [pull-request](https://github.com/ArthurSonzogni/FTXUI/pull/834) that probably fixes part of your problem
I've asked for a bit more time to bulletproof it, but I think it is mergable atm, if Arthur decides so.
I'm a bit busy currently, so I can do another PR later down the line.

**Comment by WildRackoon** [comment]
Oh I see, I did not look too deeply to discover that this `from_reference` syntax existed, this definitely solves this issue of using a Canvas as a proper framebuffer object.

As for #834, its definitely going in the right direction to get something similar to `ImGui::Image()`.

Will later if I really need a dynamic `ComputeRequirement()` or not though.

Many thanks.
