### ISSUE TITLE
[HELP] - Menu inside frame goes to the top when unfocused

### ISSUE THREAD

**Issue by blackpill0w** [ArthurSonzogni/FTXUI#841]
Here is a video that shows the problem:

[tmupp_prblm-2024-04-12_10.45.10.webm](https://github.com/ArthurSonzogni/FTXUI/assets/103550574/00bdbb5d-ecbe-47f7-82aa-dcae39dff909)

Here is the code:
[https://github.com/blackpill0w/tmupp/blob/5f00759b8e99573f1ce92084cf4676e6a2c36fdc/src/main.cpp]()

How do I keep the menu from focusing on the top items when the menu itself isn't focused?
Thank you.

**Comment by blackpill0w** [comment]
I changed
```c++
// ...
left_menu_->Render() | frame
//...
```
to this:
```c++
// ...
left_menu_->Render() | focusPosition(0, left_menu_selected)  | frame
//...
```
and now it seems to be working, I am not sure this is the best solution though.

**Comment by ArthurSonzogni** [comment]
Thanks for reporting this! This looks like a bug added mistakenly. I will take a look.

**Comment by ArthurSonzogni** [comment]
This has been fixed!
