### ISSUE TITLE
how to make Dropdown without border

### ISSUE THREAD

**Issue by ClemenceCc** [ArthurSonzogni/FTXUI#852]
i need a Dropdown with border 
Is it possible to make the border disappear with Render
if true ,how to

**Comment by ArthurSonzogni** [comment]
Hello @ClemenceCc
Yes, it is possible.
See:
- https://arthursonzogni.github.io/FTXUI/examples/?file=component/dropdown_custom
- https://github.com/ArthurSonzogni/FTXUI/blame/main/examples/component/dropdown_custom.cpp
- https://github.com/ArthurSonzogni/FTXUI/pull/826
