### ISSUE TITLE
Simulate a timeline

### ISSUE THREAD

**Issue by tchen-aurora** [ArthurSonzogni/FTXUI#854]
Hi, I'm trying to figure out if there is a way to render a "timeline" with existing elements from ftxui. A "timeline" is a horizontal bar, that encodes interesting things with color. For example,
![Screenshot 2024-04-30 at 11 54 05](https://github.com/ArthurSonzogni/FTXUI/assets/79223847/f66b5ef2-6768-4688-bb35-24cfea869cd5)
in this timeline, white portion denotes events A, and red portion denotes event B. There is an arrow showing what event users is inspecting. They are able to move left or right, to "seek" to interesting events. Note that, a white segment may contain more than one "white" events.

I'm thinking about using multiple gauges horizontally (with 1) and color them but I don't know how I can overlay an arrow to indicate the current position. Is there any other way to compose existing elements to achieve this?

It would be nice to also supporting scrolling the timeline bar if there are tons of events.
Thanks!

**Comment by ArthurSonzogni** [comment]
You can consider implementing your [own Element](https://github.com/ArthurSonzogni/FTXUI/blob/main/include/ftxui/dom/node.hpp#L33-L44) and draw it manually.

> I don't know how I can overlay an arrow to indicate the current position

What about `dbox` (aka depth box)? to stack two elements?

> It would be nice to also supporting scrolling the timeline bar if there are tons of events.

You can put a `focused` or `selected` element representing where the focus should be put. If drawn inside a `frame`, you will get scrolling.

Note that I recently added support for [horizontal scrolling events](https://github.com/ArthurSonzogni/FTXUI/blob/main/include/ftxui/component/mouse.hpp#L19-L20).

Hoping it helps.

**Comment by tchen-aurora** [comment]
thanks! I will look into these
