### ISSUE TITLE
Blinking in windows terminal

### ISSUE THREAD

**Issue by aaleino** [ArthurSonzogni/FTXUI#86]
Thank you for the library. I use WSL and windows terminal. In this terminal, many of the examples blink excessively. For example:

![issue](https://user-images.githubusercontent.com/8149013/116812621-49e2bc80-ab58-11eb-971e-3a62200f86a8.gif)

I think that this issue could be avoided by updating only the characters that have changed between frames. Unless this is already the case? It could also lead to better performance in other terminals. I suspect that using std::cout for the drawing might be slow. Although I haven't tested its performance compared to other standard methods.

**Comment by ArthurSonzogni** [comment]
@aaleino I believe I fixed the issue.
Could you please try on Windows to confirm?

**Comment by aaleino** [comment]
The flicker is gone. Thanks!

**Comment by ArthurSonzogni** [comment]
Thanks!
