### ISSUE TITLE
dropdown example bugs

### ISSUE THREAD

**Issue by ClemenceCc** [ArthurSonzogni/FTXUI#861]
in the branch main 
example dropdown
No matter what you choose, the default title "Checkbox" will be displayed.
when i try to debug the code ,i find ,in the radiobox ,selected() is correct ,but in the  dropdown component  func Render selected() always get 0
How to resolve it

**Comment by ArthurSonzogni** [comment]
Thanks!
The bugs were introduced by:
https://github.com/ArthurSonzogni/FTXUI/commit/3c9fa60d28fb0e4cd1c29d215a7bcea1b4002c15

I am going to fix them.

**Comment by ArthurSonzogni** [comment]
Thanks! This should be fixed by the title above. Please let me know if it isn't.
