### ISSUE TITLE
From ftxui::Element to std::string or char*

### ISSUE THREAD

**Issue by DanuulKa03** [ArthurSonzogni/FTXUI#870]
Is it possible to extract text from an object of type `ftxui::Element` if, for example, `ftxui::text("28.05.24")` is stored in `ftxui::Element`?
I'm not a professional in programming, but I think if the Text class in your library were inheritable and could be used, you could write something like this:
```cpp
auto date = ftxui::text("28.05.24");
std::string log = static_cast<Text>(date).text_
```

**Comment by ArthurSonzogni** [comment]
It is not possible, by design.

Ideally, you would provide a function mapping your data toward the UI.

Then updating your data would be "automatically" reflected in the UI without extra work of synchronizing the two.

Sorry for the "you are using FTXUI wrongly" reply 😅. I would be happy to suggest how to refactor your code to show  you how this was envisioned. Feel free to post a link.

**Comment by DanuulKa03** [comment]
Unfortunately, I cannot provide a link to the project because it is a commercial project, and you will not have access to it.

I believe I am using your project correctly. My task is to save the entire log displayed on the screen within the application to the clipboard when a certain key combination is pressed. My question to you was to find a more optimized way to do this (as I believe). But since this possibility does not exist, I will come up with another optimal method.

**Comment by ArthurSonzogni** [comment]
I was thinking about using it this way:

```cpp
// Application data from which the UI is derived from:
std::string data;

// A function: (data => UI)
auto ui = Renderer([&data]() {
  return paragraph(data);
})

// Event handler:
// - Return: Copy `data` into the Clipboard.
// - ...
ui |= CatchEvent([&data](Event& event) {
  if (event == Event::Return) {
    SaveToClipBoard(data);
    return true;
  }

  return false;
})

// Display the UI.
screen.Loop(ui);

```


There are no real need for a function (UI => data). This is only one-way (data => UI)
