### ISSUE TITLE
focus problem

### ISSUE THREAD

**Issue by dty2** [ArthurSonzogni/FTXUI#872]
this is my codes...
when I press space , cr_search will show, it works well.
but when I press f/d/s, there is nothing happen...
```
 // some other codes is here......
  // -------------------
  //    status time
  // -------------------
  std::atomic<bool> refresh_time = true;
  std::string logo_time;
  std::thread timeupdate([&]{
    while(refresh_time) {
      std::time_t now = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
      std::tm* now_tm = std::localtime(&now);
      std::string time(std::asctime(now_tm));
      logo_time = "   " + time.substr(11, 8) + " ";
      std::this_thread::sleep_for(std::chrono::seconds(1));
      screen.PostEvent(Event::Custom);
    }
  });

  // -------------------
  //       page
  // -------------------
  auto c_page = Container::Tab({
    cre_chat_page,
    c_friend_page,
    c_user_page,
  }, &selected_page);
  auto cr_page = Renderer(c_page, [&]{
    Element show = vbox(
      c_page->Render() | flex,
      hbox(
        text(input_toggle ? " CHAT " : " NORAML ")
          | (input_toggle ? bgcolor(Color::Green) : bgcolor(Color::Blue)),
        text("") | flex | bgcolor(Color::RGB(30, 32, 48)),
        text(logo_time) | bgcolor(Color::Blue)
      )
    );
    return show;
  });
  auto cre_page = CatchEvent(cr_page, [&](Event event)->bool{
    if(event == Event::Character("f")) {
      cre_chat_page->TakeFocus();
      selected_page = chat_page;
      return true;
    } else if(event == Event::Character("d")) {
      c_friend_page->TakeFocus();
      selected_page = friend_page;
      return true;
    } else if(event == Event::Character("s")) {
      c_user_page->TakeFocus();
      selected_page = user_page;
      return true;
    } else return false;
  });

  // -------------------
  //     search
  // -------------------
  auto c_search = Container::Vertical({});
  auto cr_search = Renderer(c_search, [&]{
    c_search->DetachAllChildren();
    for(auto& value : friendlist) {
      c_search->Add(Button(value.friendname, [&]{ chatid = value.friendid; }, ButtonOption::Ascii()));
    }
    return c_search->Render();
  });

  // -------------------
  //      main
  // -------------------
  auto c_main = Container::Tab({ cre_page, cr_search }, &search_toggle);
  auto cr_main = Renderer(c_main, [&]{
    Element show = cre_page->Render();
    if(search_toggle)
      show = dbox( cre_page->Render(), cr_search->Render() | clear_under | center);
    return show;
  });
  auto cre_main = CatchEvent(cr_main, [&](Event event)->bool{
    if(event == Event::Character(" ")) {
      search_toggle = search_toggle ? 0 : 1;
      return true;
    } else return false;
  });

  // -------------------
  //    start loop
  // -------------------
  screen.Loop(cre_main);
  refresh_time = false;
  timeupdate.join();
}
```
I already write the below codes to make the event solved. but to my surprise...
cre_page is not focused... I tried the "TakeFocuse" function, but it still not work.
```
  auto cre_page = CatchEvent(cr_page, [&](Event event)->bool{
    if(event == Event::Character("f")) {
      cre_chat_page->TakeFocus();
      selected_page = chat_page;
      return true;
    } else if(event == Event::Character("d")) {
      c_friend_page->TakeFocus();
      selected_page = friend_page;
      return true;
    } else if(event == Event::Character("s")) {
      c_user_page->TakeFocus();
      selected_page = user_page;
      return true;
    } else return false;
  });
```
if I change   screen.Loop(cre_main);   to   screen.Loop(cre_page);
the f/d/s will work too.
I check the source code of FTXUI, but I don't got any useful message for me...
I think it is the focus problem, but I don't know how to solved it...

**Comment by dty2** [comment]
Oh my god! I find the problem!!! ,
c_friend_page and c_user_page is empty vertical container... so they will return false to their parent event handle. and it will lead A chain reaction which will lead the bugs...
I'm a chinese collage students, I'm going to use this lib to make a TUI chat software. 
Must to tell the author of this lib
I like FTXUI very very much!!!
After completion my software by ftxui, I will try to write a user guide of this lib in chinese (   when the guide is done, I will show you :)   ) then I will try to make a video at bilibili(chinese youtube???) to show this lib for more and more chinese who like tui !!!

**Comment by ArthurSonzogni** [comment]
Hi @dty2,

Thank you for sharing your detailed code and the issue you encountered with focus handling in FTXUI. It's great to hear that you have resolved the problem on your own and identified the cause as empty vertical containers leading to event handling issues. Your determination and approach to debugging are commendable!

I appreciate your enthusiasm for FTXUI and your plans to contribute by creating a user guide in Chinese and making a tutorial video on Bilibili. Such resources will undoubtedly help more users, especially those in the Chinese-speaking community, to better understand and utilize this library.

If you have any further questions or need additional assistance as you continue developing your TUI chat software, feel free to ask. We are always here to support fellow developers.

Best of luck with your project, and we look forward to seeing your contributions!

Best regards,
