### ISSUE TITLE
Running tests alters the terminal state

### ISSUE THREAD

**Issue by yurivict** [ArthurSonzogni/FTXUI#878]
All tests pass, but after the tests the typed text in the terminal isn't visible.
"reset" resets the state back.

rev. a715a76

**Comment by ArthurSonzogni** [comment]
What is this exactly?
The only potential problem I see is:
```
[       OK ] ScreenInteractive.Signal_SIGSEGV (20 ms)
[ RUN      ] ScreenInteractive.Signal_SIGINT
^[[52;1R
[       OK ] ScreenInteractive.Signal_SIGINT (20 ms)
[ RUN      ] ScreenInteractive.Signal_SIGILL
```
where some "^[[52;1R" is printed when running ScreenInteractive.Signal_SIGINT is executed. Is this what you are talking about?

**Comment by yurivict** [comment]
I can't reproduce the problem of disappearing text now.
It mist have been caused by something else.

Sorry!
