### ISSUE TITLE
[feature request] Scatter plots

### ISSUE THREAD

**Issue by yurivict** [ArthurSonzogni/FTXUI#880]
FTXUI should be able to plot scatter plots, like this:
![image](https://github.com/ArthurSonzogni/FTXUI/assets/271906/29b57de5-50af-4768-9728-5655bea3e75e)

The above plot is produced using the Rust RataTUI library.
However, Rust is much more difficult to use, requires a lot more code for the same functionality, and is therefore more bug prone.

I would much rather have a nice C++ interface, like FTXUI generally provides.

**Comment by ArthurSonzogni** [comment]
Thanks for those nice words about FTXUI!

Maybe you can try drawing toward a [`Canvas`](https://github.com/ArthurSonzogni/FTXUI/blob/main/examples/dom/canvas.cpp)?
It supports drawing using braille dots and you can adds colors.

You can draw the UI manually with the Canvas too, but you can also add an overlay with `dbox` (aka depth box).

Links:
- [Documentation](https://arthursonzogni.github.io/FTXUI/structftxui_1_1Canvas.html)
- [Demo 1](https://arthursonzogni.github.io/FTXUI/examples/?file=component/canvas_animated)
- [Demo 2](https://arthursonzogni.github.io/FTXUI/examples/?file=dom/canvas) => [(source)](https://github.com/ArthurSonzogni/FTXUI/blob/main/examples/dom/canvas.cpp)
