### ISSUE TITLE
Compression priority when rendering a vbox with inadequate space.

### ISSUE THREAD

**Issue by FraserLee** [ArthurSonzogni/FTXUI#887]
Hi. I have the following sort of situation:

```c++
vbox({
    window(
        // contents here really don't matter
    ),
    window(
        // contents here matter *a lot* and should be shown if at all possible
    ),
    window(
        // contents here, again, don't matter
    )
})
```
If I'm rendering on a screen *smaller* than the size the contents would naturally take up, is some way to bias things such that windows 1 and 3 compress first, with 2 remaining full size?

If not, is there some way to check if the vbox is being compressed, so I can replace it with another element containing a message instructing the user to increase their terminal size?

Cheers

**Comment by ArthurSonzogni** [comment]
Hello! Did you consider combining 'flex_shrink' and 'flex_grow'

- Both would expand for 1 share of the extra space if they are both decorated with 'flex_grow'.
- Only one would shrink for 1 share of the lacking space if only one decorated with 'flex_shrink'.


The flex_* doesn't define that, but you should also be able to define taking more than 0 or 1 share by defining your own element/decorator or by copy-pasting-tweaking the flex_* decorators.

**Comment by FraserLee** [comment]
That seems to solve it, thanks!
