### ISSUE TITLE
Color support of window element

### ISSUE THREAD

**Issue by sentientbottleofwine** [ArthurSonzogni/FTXUI#922]
Is it possible to make a colored `window` elements but not the content inside of them . It doesn't seem like the current implementation allows for this:
https://github.com/ArthurSonzogni/FTXUI/blob/5a9ef876a14b91a3cc5b0313cfdaf6b5527eccf4/include/ftxui/dom/elements.hpp#L82

If this not possible I'm happy to make a PR for this.

**Comment by ArthurSonzogni** [comment]
Hello,
Wouldn't this be fixed by applying the transformation early (to the content), as opposed to later (to the window)?
```cpp
auto colored_outside = window(a,b) | color(c)
auto colored_inside = window(a, b | color(c))
```

**Comment by sentientbottleofwine** [comment]
I'm not sure if I understood you correctly, but this makes the contents inside of the window colored, not the border. I'm sorry if I expressed my intentions confusingly. 
The proposed solution:
![20240827_18h05m21s_grim](https://github.com/user-attachments/assets/65cc5ac1-9c69-4700-839b-d72eeb1ee57f)
The desired effect:
![20240827_18h05m37s_grim](https://github.com/user-attachments/assets/253446a4-3a7a-4e7f-bda0-8552129bec1e)

**Comment by sentientbottleofwine** [comment]
Oh never mind I'm being silly as always. I forgot that I can use ft::color property both on the inside and the outside of the window:
```cpp
auto = window(a,b | color(c)) | color(d);
```

**Comment by thomthom** [comment]
I was trying to apply a color to the border, but not the content. Setting the content color to Default seems to make no effect, it still inherit the frame (window) color.
