### ISSUE TITLE
How to update the ui when the menu selector changes

### ISSUE THREAD

**Issue by sentientbottleofwine** [ArthurSonzogni/FTXUI#931]
In my application I need to automatically change the selected entry in a menu when a certain entry is selected. If I try to do that the ui stays on the previously selected entry and updates only(at I least speculate) when ui needs to be rerendered again(not when the selector changes) meaning that for example when I press j,k,l... to navigate to a next entry only then ui is updated and the selected entry is highlighted.
```cpp
#include<ftxui/component/component.hpp>
#include<ftxui/component/event.hpp>
#include<ftxui/component/screen_interactive.hpp>

namespace ft = ftxui;

int main() {
	auto screen = ft::ScreenInteractive::Fullscreen();
	const std::vector<std::string> test_vars = {"One", "Two", "Three"};
	int selector = 0;

	auto test_tab = ft::Container::Tab({
		ft::Button(test_vars[0], []{}),
		ft::Button(test_vars[1], []{}),
		ft::Button(test_vars[2], []{})
	}, &selector);

	auto test_menu = ft::Menu(&test_vars, &selector, ft::MenuOption::HorizontalAnimated())
	| ft::CatchEvent([&](ft::Event e) {
			if(selector == 2)
				selector = 0;
			return false;
		}
	);

	auto render = ft::Container::Vertical({
		test_menu,
    	        test_tab
	});

	screen.Loop(ft::Renderer(render, [&]{ return render->Render(); }));
}
```
I tried to use to `screen.RequestAnimationFrame()` and `screen.PostEvent(ft::Event::Custom)` but that also didn't work.

**Comment by herring-swe** [comment]
I would do it like this. Post event in Menu event hook and let menu do it's work.

```c++
auto test_menu = Menu(&test_vars, &selector, MenuOption::HorizontalAnimated());
test_menu |= CatchEvent([&](Event e) {
    screen.PostEvent(Event::Special("CheckSel"));
    return false;
});
```

Then capture event in main loop and process it when selection has been updated properly.

```c++
auto eventloop = CatchEvent(render, [&](Event event) {
    if (event == Event::Special("CheckSel"))
    {
        if (selector == 2)
            selector = 0;
        return true;
    }
    return false;
});

screen.Loop(eventloop);
```

However, there seems to be a bug when updating selector. Which is why I lurk this GIT...
"Three" is still active, which looks fine with mouse still hovering the item, but when using keyboard it is wrong and the menu will handle next arrow keys as if "One" is selected.

**Comment by sentientbottleofwine** [comment]
Thanks for the reply. Your solution worked for me! I also noticed the bug you mentioned. Will you create an issue for it?.  I wonder why it is working only when we change the selector in response to an event generated by menu, if doing it in the first eventhook attached to menu technically seems to be the same thing?
