### ISSUE TITLE
Menu item selection not drawn the whole way

### ISSUE THREAD

**Issue by herring-swe** [ArthurSonzogni/FTXUI#932]
I want to achieve so that each menu item when selected is rendered the whole width of the menu.
I tried to fix it  by padding the string with spaces, excluding the "> " part that is added to menu item (can I change this??)

```c++
fmt::format("{: <{}s} ", "../", total_w - 2);
```

But when rendering it is as if the string is trimmed. What can I do to achieve what I want?

![image](https://github.com/user-attachments/assets/b33aa4d0-1679-412b-a0dc-61f5b37650c8)

**Comment by ArthurSonzogni** [comment]
Hello @herring-swe !

I think you can populate a `MenuOption`, and pass it to the Menu function?

Specifically `menu_option.entry_option.transform`.

The default implementation is:
```cpp
auto menu_option = MenuOption::Vertical(); 
menu_option.entry_option.transform = [](const EntryState&) {
  std::string label = (state.active ? "> " : "  ") + state.label;  // NOLINT
  Element e = text(std::move(label));
  if (state.focused) {
    e = e | inverted;
  }
  if (state.active) {
    e = e | bold;
  }
  return e;
}
auto menu = Menu(..., menu_option);
```

But you can tweak it to make the `Element` `e` flexible, before applying `inverted`.

I haven't try, but maybe:
```cpp
menu_option.entry_option.transform = [](const EntryState&) {
  std::string label = (state.active ? "> " : "  ") + state.label;  // NOLINT
  Element e = text(std::move(label));
  e |= x_flex;
  if (state.focused) {
    e = e | inverted;
  }
  if (state.active) {
    e = e | bold;
  }
  return e;
}
```

**Comment by herring-swe** [comment]
@ArthurSonzogni 

Thanks for the reply. Your suggestion got me going forward but xflex didn't work or any other flex option.

I added border and this is result (without flex) and this is result:
![image](https://github.com/user-attachments/assets/806b952f-9e16-4a17-bb06-64f641c76630)

So I then replaced `inverted` with `|= bgcolor(Color::White) | color(Color::Black);` and that did the trick. 
So problem is with inverted for some reason.

**Comment by herring-swe** [comment]
@ArthurSonzogni 

Another request. Can you add index to struct EntryState? This way I can move all logic to transform function instead of updating the menu with strings containing info in intermediate format.

**Comment by ArthurSonzogni** [comment]
Sounds like a good idea. I passed a struct to allow forward compatible changes.

So you want to submit a PR?

**Comment by herring-swe** [comment]
> Sounds like a good idea. I passed a struct to allow forward compatible changes.
> 
> Do you want to submit a PR?

See PR [#933](https://github.com/ArthurSonzogni/FTXUI/pull/933)

**Comment by ArthurSonzogni** [comment]
Thanks!

**Comment by herring-swe** [comment]
ftxui_example_menu

https://github.com/user-attachments/assets/1c4f8f82-0ea9-40ba-a321-d3ed1933c2d1

**Comment by herring-swe** [comment]
Further testing reveal it's a problem when running in vscode (ps or cmd terminal).
Running it directly renders fine.
