### ISSUE TITLE
Integrating FTXUI in an application with an existing logging system

### ISSUE THREAD

**Issue by w8floosh** [ArthurSonzogni/FTXUI#947]
Hello, I would like to know if it is possible to use this library with existing C++ applications that already use an own logging system. I am extending the functionalities of some SDK application which outputs lots of logs into stdout (and stderr sometimes). When I use these functionalities, I would like to use FTXUI to split the terminal in two sections, one just prints the logs generated by the application in the standard output/error and the other one prints some stats I choose.

Is it possible to "redirect" the existing application's standard output **without** modifying the way the application logs things and print it in that separate section of the terminal?

Thank you in advance.

**Comment by Epixu** [comment]
I wanted to do something similar, see #778 so you know what kind of issues I encountered while doing so
I'm will start work on some optimizations that will hopefully make this feasible by december, it has been long overdue

**Comment by ArthurSonzogni** [comment]
1. Call the wrapped app as a subprocess [(example 1)](https://github.com/ArthurSonzogni/git-tui/blob/master/src/log.cpp#L41)
2. `Pipe` the wrapped app [(example 2)](https://github.com/ArthurSonzogni/chrome-log-beautifier/blob/master/src/main.cpp#L44-L54)

In particular, in (example 2), you see `stdin` is redirected:
```cpp
  // Save the original stdin:
  int original_stdin_file_descriptor = dup(fileno(stdin))
  
  // Change stdin to handle user input instead of the piped software:
  stdin = freopen("/dev/tty", "r", stdin);

  // TODO("Do something with `original_stdin_file_descriptor")
```

Does (1) or (2) fits your intents?

**Comment by w8floosh** [comment]
I think creating a subprocess would better suit my case. 
I have write access to the logging source code but it is a SDK code and it wouldn't make sense to touch it at all, because my feature is secondary and I don't want it to alter the original source code used in the whole application. 
Furthermore, as the SDK I am working on is multithreaded, I may need to work with locks and race conditions on the stdout, as both FTXUI and the SDK print there.

I will try this sooner or later, as it is not a high priority work at the moment.

Thank you all for such valuable information 🙏🏻
Have a nice day

**Comment by ArthurSonzogni** [comment]
You are welcome!
