### ISSUE TITLE
Compiling to web assembly

### ISSUE THREAD

**Issue by AbdelwahedTahri** [ArthurSonzogni/FTXUI#969]
i tried to compiel to web assembly, use only ftxui, nothing related to file system or threads the cmake look like
```cmake
	add_executable(todo
		main.cpp
		src/Application.cpp
		...
	)

	target_include_directories(todo 
		PRIVATE include
	)

	target_link_libraries(todo
		PRIVATE ftxui::screen
		PRIVATE ftxui::dom
		PRIVATE ftxui::component
	)
	set(CMAKE_EXECUTABLE_SUFFIX ".html")
```
i use to compile:
 `emcmake cmake  -S . -B build`
 `cmake --build build`
 the programe get compiled but then the todo.js and todo.html throw an error idk why?
 the prog works very fine when copiled to  c++ bin
 
 can smeone help me pls

**Comment by ArthurSonzogni** [comment]
Hello!
Please take a look at ftxui-starter:
https://github.com/ArthurSonzogni/ftxui-starter?tab=readme-ov-file#webassembly-build

In particular, usage of threads and shared memory in web browsers requires COOP and COEP headers.

(there are others way via service workers to provide the headers if you don't own the server and can only use static files)
