### ISSUE TITLE
Online demos with web assembly do not show anything

### ISSUE THREAD

**Issue by AbdelwahedTahri** [ArthurSonzogni/FTXUI#973]
i think the title says it all,

what i want now is to test these demos on my local environnement how to compile them and test them?

Please Help

**Comment by ArthurSonzogni** [comment]
Hello, It works for me.

Do you see any error message in Devtools? What web browser do you use?

**Comment by AbdelwahedTahri** [comment]
i swear to god that it wasn't working, i use firefox btw 

can u please help me understand the steps to compile my program to web assembly an run it in a web terminal as you do with the examples.

thx a lot sir

**Comment by ArthurSonzogni** [comment]
> Do you see any error message in Devtools?

Did you try to see if you had any devtool message?


Here is an example project for using ftxui with webassembly:
https://github.com/ArthurSonzogni/ftxui-starter

**Comment by AbdelwahedTahri** [comment]
i get this 
![image](https://github.com/user-attachments/assets/420ff629-8ce3-4a89-a41e-4e47c392e02a)

**Comment by adrianniebla** [comment]
@AbdelwahedTahri are you running on Mac? I am getting the same problem haven't looked in depth into the problem but it seems the `ftxui_example_color_gallery` files `js`, `wasm` and `worker.js` arent' being generated for the example. I was able to get it running by copying those files from the online demo to `examples/dom`

**Comment by adrianniebla** [comment]
@AbdelwahedTahri I was able to run just follow the steps for [https://github.com/ArthurSonzogni/ftxui-starter](https://github.com/ArthurSonzogni/ftxui-starter) create to two build folders `build` and `build_emscripten` and run their respective build commands. But instead of running the examples folders got to `build_emscripten/examples` and run `./run_webassembly.py` from there.

**Comment by ArthurSonzogni** [comment]
Thanks!
I uploaded a new version.
Can you access the [examples](https://arthursonzogni.github.io/FTXUI/examples/) now?

**Comment by AbdelwahedTahri** [comment]
> Thanks! I uploaded a new version. Can you access the [examples](https://arthursonzogni.github.io/FTXUI/examples/) now?

It's working now 🎉 thanks a lot

**Comment by AbdelwahedTahri** [comment]
This problem is Fixed i have to close it i guess

**Comment by ArthurSonzogni** [comment]
Thanks!
